/**
 * TopicMap for ratio.txt - Ratio or the Quantitative Relation
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - ratio-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const RATIO_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/quantity/ratio/sources/ratio.txt',
  'Hegel\'s Science of Logic - Quantity',
  'Ratio or the Quantitative Relation',
  [
    createTopicMapEntry(
      'ratio-intro-qualitative-moment',
      'Ratio: quantum qualitatively determined',
      [6, 50],
      'Ratio: Infinite quantum is unity of quantitative/qualitative determinateness - ratio. Quantum qualitatively determined, referring to beyond. Each possesses determinateness in reference to other. In otherness, return into themselves. Quantum is itself posited as relation - self-enclosed totality, infinite within.',
      [
        'infinity',
        'quantum',
        'determined',
        'point',
        'negative',
        'beyond',
        'quantum',
        'beyond',
        'quantum',
        'within',
        'beyond',
        'qualitative',
        'moment',
        'general',
        'infinite',
        'quantum',
        'unity',
        'moments',
        'quantitative',
        'qualitative',
        'determinateness',
        'instance',
        'ratio',
        'ratio',
        'quantum',
        'merely',
        'indifferent',
        'determinateness',
        'qualitatively',
        'determined',
        'referring',
        'beyond',
        'continues',
        'beyond',
        'beyond',
        'other',
        'quantum',
        'essentially',
        'refer',
        'external',
        'quanta',
        'possesses',
        'determinateness',
        'reference',
        'other',
        'otherness',
        'returned',
        'themselves',
        'other',
        'other',
        'constitutes',
        'determinateness',
        'quantum',
        'self-transcendence',
        'quantum',
        'changed',
        'other',
        'abstract',
        'other',
        'abstract',
        'beyond',
        'attained',
        'determinateness',
        'other',
        'quantum',
        'finds',
        'quality',
        'quantum',
        'conceptual',
        'determinateness',
        'externality',
        'ratio',
        'quantum',
        'posited',
        'determinateness',
        'externality',
        'quantum',
        'beyond',
        'quanta',
        'stand',
        'connection',
        'scene',
        'connection',
        'magnitude',
        'quantum',
        'relation',
        'posited',
        'relation',
        'quantum',
        'qualitative',
        'determinateness',
        'relation',
        'ratio',
        'quantum',
        'expression',
        'self-enclosed',
        'totality',
        'indifference',
        'limit',
        'containing',
        'externality',
        'being-determined',
        'externality',
        'referred',
        'infinite',
        'within',
      ],
      { section: 'Introduction', order: 1 }
    ),

    createTopicMapEntry(
      'ratio-direct-intro',
      'Direct ratio: qualitative moment not yet explicit',
      [52, 74],
      'Direct ratio: Qualitative moment not yet explicit. Quantum posited as having determinateness in externality, still as quantum. Quantitative relation is contradiction of externality/self-reference. Contradiction sublates: (2) inverse ratio (negation co-posited), (3) ratio of powers (unity self-production) → measure.',
      [
        'ratio',
        'general',
        'direct',
        'ratio',
        'qualitative',
        'moment',
        'emerge',
        'explicitly',
        'quantum',
        'quantum',
        'posited',
        'determinateness',
        'externality',
        'quantitative',
        'relation',
        'contradiction',
        'externality',
        'self-reference',
        'persistence',
        'quanta',
        'negation',
        'contradiction',
        'sublates',
        'indirect',
        'inverse',
        'ratio',
        'negation',
        'quanta',
        'co-posited',
        'alteration',
        'variability',
        'direct',
        'ratio',
        'posited',
        'ratio',
        'powers',
        'unity',
        'difference',
        'refers',
        'proves',
        'simple',
        'self-production',
        'quantum',
        'qualitative',
        'moment',
        'finally',
        'posited',
        'simple',
        'determination',
        'identical',
        'quantum',
        'becomes',
        'measure',
      ],
      { section: 'Ratio in general', order: 2 }
    ),

    createTopicMapEntry(
      'ratio-direct-exponent',
      'Exponent: one determinateness of both quanta',
      [85, 90],
      'Direct ratio: Determinateness of each quantum lies in reciprocal determinateness of other. One determinateness/limit of both (itself a quantum) - the exponent.',
      [
        'ratio',
        'immediate',
        'direct',
        'determinateness',
        'quantum',
        'reciprocal',
        'determinateness',
        'determinateness',
        'limit',
        'quantum',
        'exponent',
        'ratio',
      ],
      { section: 'A. THE DIRECT RATIO', order: 3 }
    ),

    createTopicMapEntry(
      'ratio-direct-exponent-qualitative',
      'Exponent as qualitatively determined quantum',
      [92, 106],
      'Exponent: Some quantum, but qualitatively determined (difference/beyond/otherness in it). Difference is unit and amount. Unit is being-determined-for-itself; amount is indifferent fluctuation. In ratio, each moment appears as quantum on its own - delimitations.',
      [
        'exponent',
        'quantum',
        'referring',
        'itself',
        'otherness',
        'within',
        'qualitatively',
        'determined',
        'quantum',
        'difference',
        'beyond',
        'otherness',
        'difference',
        'quantum',
        'difference',
        'unit',
        'amount',
        'unit',
        'being-determined-for-itself',
        'amount',
        'indifferent',
        'fluctuation',
        'determinateness',
        'external',
        'indifference',
        'quantum',
        'unit',
        'amount',
        'moments',
        'quantum',
        'ratio',
        'quantum',
        'realized',
        'moments',
        'appears',
        'quantum',
        'determinations',
        'existence',
        'quantum',
        'delimitations',
        'external',
        'indifferent',
        'determinateness',
        'magnitude',
      ],
      { section: 'A. THE DIRECT RATIO', order: 4 }
    ),

    createTopicMapEntry(
      'ratio-direct-exponent-meaning',
      'Exponent: meaning of both determinations',
      [108, 132],
      'Exponent: Difference as simple determinateness - meaning of both determinations. (1) Quantum/amount: if unit is one, amount is quantum of exponent. (2) Simple determinateness as qualitative moment: one side determined, other determined by exponent. Ratio rests solely on exponent - unit remains unit, other remains same amount.',
      [
        'exponent',
        'difference',
        'simple',
        'determinateness',
        'meaning',
        'determinations',
        'immediately',
        'quantum',
        'amount',
        'side',
        'ratio',
        'unit',
        'expressed',
        'numerical',
        'value',
        'amount',
        'quantum',
        'exponent',
        'simple',
        'determinateness',
        'qualitative',
        'moment',
        'sides',
        'ratio',
        'quantum',
        'side',
        'determined',
        'determined',
        'exponent',
        'matter',
        'indifference',
        'determined',
        'meaning',
        'quantum',
        'determined',
        'other',
        'quantum',
        'altering',
        'determinateness',
        'ratio',
        'rests',
        'exponent',
        'side',
        'unit',
        'remains',
        'unit',
        'great',
        'becomes',
        'great',
        'remains',
        'amount',
        'unit',
      ],
      { section: 'A. THE DIRECT RATIO', order: 5 }
    ),

    createTopicMapEntry(
      'ratio-direct-incompleteness',
      'Incompleteness: each side only one moment',
      [134, 155],
      'Incompleteness: Two constitute one quantum. One side is unit (not amount), other is amount. They are not complete quanta. Incompleteness is negation - not general variability but determined: as one altered, other increases/decreases. Only unit altered; amount remains same quantum of units. Each side only one moment - self-subsistence negated, negative with respect to each other.',
      [
        'accordingly',
        'constitute',
        'quantum',
        'side',
        'value',
        'unit',
        'respect',
        'amount',
        'amount',
        'conceptual',
        'determinateness',
        'complete',
        'quanta',
        'incompleteness',
        'negation',
        'general',
        'variability',
        'assume',
        'magnitudes',
        'determined',
        'altered',
        'increased',
        'decreased',
        'corresponding',
        'measure',
        'indicated',
        'unit',
        'altered',
        'quantum',
        'side',
        'amount',
        'remains',
        'quantum',
        'units',
        'side',
        'retains',
        'value',
        'unit',
        'altered',
        'quantum',
        'side',
        'moments',
        'quantum',
        'self-subsistence',
        'characteristic',
        'negated',
        'qualitative',
        'combination',
        'posited',
        'negative',
        'respect',
      ],
      { section: 'A. THE DIRECT RATIO', order: 6 }
    ),

    createTopicMapEntry(
      'ratio-direct-transition-inverse',
      'Transition to inverse ratio: exponent as product',
      [157, 191],
      'Transition to inverse: Exponent ought to be complete quantum (determinations come together). But as quotient, only value of amount or unit. Not posited as determinant/qualitative unity. Sides are incomplete quanta - negation qualifying them. More real ratio arises: exponent as product of sides - inverse ratio.',
      [
        'exponent',
        'complete',
        'quantum',
        'determinations',
        'come',
        'together',
        'quotient',
        'exponent',
        'value',
        'amount',
        'unit',
        'available',
        'determining',
        'sides',
        'relation',
        'unit',
        'amount',
        'side',
        'quantum',
        'measured',
        'quantum',
        'unit',
        'quotient',
        'amount',
        'units',
        'amount',
        'quotient',
        'unit',
        'required',
        'amount',
        'quantum',
        'exponent',
        'quotient',
        'posited',
        'determinant',
        'ratio',
        'qualitative',
        'unity',
        'posited',
        'extent',
        'value',
        'unity',
        'moments',
        'unit',
        'amount',
        'sides',
        'quanta',
        'present',
        'explicated',
        'quantum',
        'ratio',
        'value',
        'specific',
        'sides',
        'ratio',
        'incomplete',
        'quanta',
        'counting',
        'qualitative',
        'moments',
        'posited',
        'negation',
        'qualifying',
        'arises',
        'ratio',
        'accordance',
        'definition',
        'exponent',
        'meaning',
        'product',
        'sides',
        'determinateness',
        'inverse',
        'ratio',
      ],
      { section: 'A. THE DIRECT RATIO', order: 7 }
    ),
  ],
  {
    sectionDescription: 'Ratio or the Quantitative Relation - Ratio (quantum qualitatively determined, self-enclosed totality, infinite within). Direct ratio (qualitative moment not yet explicit, contradiction of externality/self-reference). Exponent (one determinateness of both, qualitatively determined, meaning of both determinations). Incompleteness (each side only one moment, not complete quanta). Transition to inverse ratio (exponent as product).',
  }
);

