import type { DialecticIR, DialecticState } from '@schema/dialectic';

// Generated by src/tools/generate-becoming-essence-ir.ts
const stateBecomingEssence1InverseRatio: DialecticState = {
  "id": "becoming-essence-1-inverse-ratio",
  "title": "Indifference posited as inverse ratio",
  "concept": "IndifferenceInverseRatio",
  "phase": "quantity",
  "moments": [
    {
      "name": "substrateAndOneMeasure",
      "definition": "Indifference appears as one substrate whose measure is internally divisible yet indivisible as basis",
      "type": "determination"
    },
    {
      "name": "inverseRatioForm",
      "definition": "Differences relate inversely as determinations of one underlying indifferent whole",
      "type": "mediation",
      "relation": "contains",
      "relatedTo": "substrateAndOneMeasure"
    },
    {
      "name": "twoQualitiesEmergence",
      "definition": "The one relation unfolds into two qualities that maintain one connection through inversion",
      "type": "process"
    }
  ],
  "invariants": [
    {
      "id": "becoming-essence-1-inverse-inv-1",
      "constraint": "inverse relation belongs to one substrate",
      "predicate": "oneSubstrateInverseRelation(indifference)"
    },
    {
      "id": "becoming-essence-1-inverse-inv-2",
      "constraint": "qualitative difference is mediated through inverse quantity",
      "predicate": "qualityMediatedByInverseQuantity(relation)"
    }
  ],
  "forces": [
    {
      "id": "becoming-essence-1-inverse-force-1",
      "description": "The inverse relation externalizes as determinate existence and equilibrium tension",
      "type": "mediation",
      "trigger": "inverseRelation.becomesExistential = true",
      "effect": "equilibriumContradiction.explicit = true",
      "targetState": "becoming-essence-2"
    }
  ],
  "transitions": [
    {
      "id": "becoming-essence-1-inverse-trans-1",
      "from": "becoming-essence-1-inverse-ratio",
      "to": "becoming-essence-2",
      "mechanism": "mediation",
      "description": "From inverse-ratio articulation to contradiction of equilibrium"
    }
  ],
  "nextStates": [
    "becoming-essence-2"
  ],
  "previousStates": [
    "becoming-essence-1"
  ],
  "provenance": {
    "topicMapId": "be-b-1-inverse-ratio",
    "lineRange": {
      "start": 24,
      "end": 52
    },
    "section": "1.",
    "order": 3
  },
  "description": "Difference = quantitative and external. Two different quanta of same substrate = their sum (quantum). Indifference = fixed measure, absolute limit, not quantum, not in opposition. Abstract determinateness falls into indifference. Two quanta alterable, restricted by fixed limit of sum, related negatively = qualitative determination. Stand in inverse ratio. Differs from formal inverted ratio: limit = real substrate, each side = whole.",
  "keyPoints": [
    "consequently",
    "difference",
    "present",
    "at first",
    "essentially",
    "only",
    "quantitative",
    "external",
    "simply",
    "two different quanta",
    "one",
    "same substrate",
    "would",
    "thus",
    "their sum",
    "itself",
    "posited",
    "quantum",
    "indifference",
    "fixed measure",
    "implicitly",
    "existent",
    "absolute limit",
    "connected",
    "those differences",
    "would not",
    "itself",
    "quantum",
    "would not",
    "any way",
    "enter",
    "opposition",
    "others",
    "whether",
    "sum",
    "also",
    "exponent",
    "those others",
    "sums",
    "indifferences",
    "only",
    "abstract determinateness",
    "falls",
    "indifference",
    "two quanta",
    "order",
    "may",
    "posited",
    "moments",
    "alterable",
    "indifferent",
    "greater",
    "smaller",
    "relative",
    "one another",
    "however",
    "inasmuch",
    "restricted",
    "fixed limit",
    "their sum",
    "same time",
    "related",
    "each other",
    "not externally",
    "negatively",
    "now",
    "qualitative determination",
    "stand",
    "each other",
    "accordingly",
    "stand",
    "inverse ratio",
    "each other",
    "relation",
    "differs",
    "earlier",
    "formal",
    "inverted ratio",
    "inasmuch",
    "limit",
    "here",
    "real substrate",
    "each",
    "two sides",
    "posited",
    "having",
    "itself",
    "whole"
  ]
};
const stateBecomingEssence2: DialecticState = {
  "id": "becoming-essence-2",
  "title": "Contradiction of indifference in existence",
  "concept": "IndifferenceContradiction",
  "phase": "quantity",
  "moments": [
    {
      "name": "indifferenceAsExistence",
      "definition": "Indifference gains existence as articulated determinacies that emerge from the substrate relation",
      "type": "determination"
    },
    {
      "name": "equilibriumAsTension",
      "definition": "Qualitative equilibrium appears as internally unstable and contradiction-bearing",
      "type": "negation",
      "relation": "contains",
      "relatedTo": "indifferenceAsExistence"
    },
    {
      "name": "essencePressure",
      "definition": "Contradiction presses determinations toward a non-immediate reflective ground",
      "type": "process"
    }
  ],
  "invariants": [
    {
      "id": "becoming-essence-2-inv-1",
      "constraint": "indifference and determinacy are in unresolved tension",
      "predicate": "tension(indifference, determinacy)"
    },
    {
      "id": "becoming-essence-2-inv-2",
      "constraint": "equilibrium is contradiction, not final repose",
      "predicate": "equilibriumAsContradiction(indifference)"
    }
  ],
  "forces": [
    {
      "id": "becoming-essence-2-force-1",
      "description": "Contradiction manifests as explicit self-sublation of measure-being",
      "type": "sublation",
      "trigger": "contradiction.matures = true",
      "effect": "selfSublation.explicit = true",
      "targetState": "becoming-essence-3"
    }
  ],
  "transitions": [
    {
      "id": "becoming-essence-2-trans-1",
      "from": "becoming-essence-2",
      "to": "becoming-essence-3",
      "mechanism": "sublation",
      "description": "From contradiction to self-sublation manifested"
    }
  ],
  "nextStates": [
    "becoming-essence-3"
  ],
  "previousStates": [
    "becoming-essence-1-inverse-ratio"
  ],
  "provenance": {
    "topicMapId": "be-b-3-contradiction-essence",
    "lineRange": {
      "start": 197,
      "end": 229
    },
    "section": "3.",
    "order": 11
  },
  "description": "On basis of qualitative connection: no quantitative difference, no more of one quality. More exceeding other = unstable determination or other itself. In equality, neither there (existence rests on inequality). Each factor vanishes (exceeds or equal). Vanishing = disturbance of equilibrium, one factor greater, other quality sublated, first predominant, other diminishes, becomes self-subsistent factor, no longer two moments but one whole. Unity as totality of determining process, determined as indifference = contradiction all around. Must be posited as self-sublating contradiction, determined as subsistence existing for itself, unity immanently negative and absolute = essence.",
  "keyPoints": [
    "basis",
    "therefore",
    "qualitative connection",
    "question",
    "quantitative difference",
    "more",
    "one quality",
    "more",
    "one",
    "two connected moments",
    "would",
    "exceed",
    "other",
    "would",
    "only",
    "unstable determination",
    "would",
    "only",
    "other itself",
    "equality",
    "two",
    "neither",
    "would",
    "there",
    "existence",
    "would",
    "rest",
    "inequality",
    "quantum",
    "each",
    "supposed factors",
    "vanishes",
    "whether",
    "one factor",
    "assumed",
    "exceed",
    "other",
    "equal",
    "standpoint",
    "quantitative representation",
    "vanishing",
    "appears",
    "disturbance",
    "equilibrium",
    "one factor",
    "becoming",
    "greater",
    "other",
    "sublation",
    "quality",
    "other",
    "instability",
    "thus",
    "posited",
    "first factor",
    "becomes",
    "predominant",
    "other",
    "diminishes",
    "accelerated velocity",
    "overcome",
    "turn",
    "constitutes",
    "one self-subsistent factor",
    "however",
    "no longer",
    "two specific moments",
    "factors",
    "only",
    "one whole",
    "unity",
    "thus",
    "posited",
    "totality",
    "process",
    "determining",
    "itself",
    "determined",
    "process",
    "indifference",
    "contradiction",
    "around",
    "must",
    "therefore",
    "posited",
    "self-sublating contradiction",
    "determined",
    "subsistence",
    "existing",
    "itself",
    "one",
    "no longer",
    "merely",
    "indifferent unity",
    "result",
    "unity",
    "immanently",
    "negative",
    "absolute",
    "essence"
  ]
};

export const indifferenceInverseRatioIR: DialecticIR = {
  id: "indifference-inverse-ratio-ir",
  title: "Indifference and Inverse Ratio IR",
  section: "BEING - MEASURE - C. Becoming of Essence - Indifference and Inverse Ratio",
  states: [
    stateBecomingEssence1InverseRatio,
    stateBecomingEssence2,
  ],
  metadata: {
  "sourceFile": "indifference-inverse-ratio.txt",
  "totalStates": 2,
  "cpuGpuMapping": {
    "becoming-essence-1-inverse-ratio": "quantity",
    "becoming-essence-2": "quantity"
  }
},
};

export const indifferenceInverseRatioStates = {
  "becoming-essence-1-inverse-ratio": stateBecomingEssence1InverseRatio,
  "becoming-essence-2": stateBecomingEssence2,
};
