import type { DialecticIR, DialecticState } from '@schema/dialectic';

// Generated by src/tools/generate-actuality-substance-ir.ts
const stateSubB1: DialecticState = {
  "id": "sub-b-1",
  "title": "Substance as power posits cause and effect",
  "concept": "FormalCausality",
  "phase": "appearance",
  "moments": [
    {
      "name": "cause",
      "definition": "Substance existing for itself as originative determination",
      "type": "determination"
    },
    {
      "name": "effect",
      "definition": "Sublated substantiality as positedness",
      "type": "negation",
      "relation": "opposite",
      "relatedTo": "cause"
    }
  ],
  "invariants": [
    {
      "id": "sub-b-1-inv-1",
      "constraint": "cause and effect define formal causality",
      "predicate": "equals(formalCausality, relation(cause, effect))"
    },
    {
      "id": "sub-b-1-inv-2",
      "constraint": "cause is substance reflected into itself",
      "predicate": "equals(cause, reflectedPower(substance))"
    }
  ],
  "forces": [
    {
      "id": "sub-b-1-force-1",
      "description": "Identity pressure extinguishes cause/effect distinction",
      "type": "reflection",
      "trigger": "cause.actualityInEffect = explicit",
      "effect": "causalDistinction.sublated = true",
      "targetState": "sub-b-5"
    }
  ],
  "transitions": [
    {
      "id": "sub-b-1-trans-1",
      "from": "sub-b-1",
      "to": "sub-b-5",
      "mechanism": "reflection",
      "description": "From formal cause/effect to extinguished identity"
    }
  ],
  "nextStates": [
    "sub-b-5"
  ],
  "previousStates": [
    "sub-a-7"
  ],
  "provenance": {
    "topicMapId": "sub-b-1-substance-power-cause",
    "lineRange": {
      "start": 3,
      "end": 15
    },
    "section": "The Relation of Causality",
    "order": 1
  },
  "description": "Substance = power reflected into itself (not transitive, posits determinations, distinguishes from itself). Self-referring in determining = itself posited as negative/positedness. Positedness = sublated substantiality, merely posited = effect. Substance existing for itself = cause. Relation of causality = relation of cause and effect = formal relation of causality.",
  "keyPoints": [
    "substance",
    "power",
    "reflected into itself",
    "not transitive",
    "posits determinations",
    "distinguishes from itself",
    "self-referring",
    "determining",
    "negative",
    "positedness",
    "sublated substantiality",
    "merely posited",
    "effect",
    "substance existing for itself",
    "cause",
    "relation of causality",
    "cause and effect",
    "formal relation of causality"
  ]
};
const stateSubB5: DialecticState = {
  "id": "sub-b-5",
  "title": "Cause and effect identity extinguished into immediacy",
  "concept": "CausalityExtinguished",
  "phase": "appearance",
  "moments": [
    {
      "name": "extinguishedDifference",
      "definition": "Cause and effect lose formal distinction in their identity",
      "type": "sublation"
    },
    {
      "name": "indifferentImmediacy",
      "definition": "Causality appears as immediate and externally contingent",
      "type": "externality",
      "relation": "transforms",
      "relatedTo": "extinguishedDifference"
    }
  ],
  "invariants": [
    {
      "id": "sub-b-5-inv-1",
      "constraint": "cause extinguishes in effect",
      "predicate": "extinguishedIn(cause, effect)"
    },
    {
      "id": "sub-b-5-inv-2",
      "constraint": "immediacy is indifferent to causal relation",
      "predicate": "indifferentTo(immediacy, causalRelation)"
    }
  ],
  "forces": [
    {
      "id": "sub-b-5-force-1",
      "description": "Finite determinate causality exposes contingent side-being",
      "type": "contradiction",
      "trigger": "content.formDifference = external",
      "effect": "reciprocalCausality.prepared = true",
      "targetState": "sub-b-9"
    }
  ],
  "transitions": [
    {
      "id": "sub-b-5-trans-1",
      "from": "sub-b-5",
      "to": "sub-b-9",
      "mechanism": "contradiction",
      "description": "From extinguished formal causality to contingent side-being"
    }
  ],
  "nextStates": [
    "sub-b-9"
  ],
  "previousStates": [
    "sub-b-1"
  ],
  "provenance": {
    "topicMapId": "sub-b-5-identity-extinguished",
    "lineRange": {
      "start": 135,
      "end": 146
    },
    "section": "The Relation of Causality",
    "order": 5
  },
  "description": "In identity of cause/effect: form distinguishing (exists in itself/posited) = sublated. Cause extinguished in effect, effect extinguished (only determinateness of cause). Causality extinguished = immediacy (indifferent to relation, comes externally).",
  "keyPoints": [
    "identity of cause and effect",
    "form distinguishing",
    "exists in itself",
    "posited",
    "sublated",
    "cause extinguished in effect",
    "effect extinguished",
    "determinateness of cause",
    "causality extinguished",
    "immediacy",
    "indifferent to relation",
    "comes externally"
  ]
};
const stateSubB9: DialecticState = {
  "id": "sub-b-9",
  "title": "Contingent side-being drives to reciprocity",
  "concept": "FiniteCausalityLimit",
  "phase": "appearance",
  "moments": [
    {
      "name": "contingentSideBeing",
      "definition": "Cause includes contingent factors not entering causal identity",
      "type": "appearance"
    },
    {
      "name": "causalInsufficiency",
      "definition": "Single-line causality fails in living and spiritual determination",
      "type": "negation",
      "relation": "negates",
      "relatedTo": "contingentSideBeing"
    }
  ],
  "invariants": [
    {
      "id": "sub-b-9-inv-1",
      "constraint": "remote and aggregate causes undermine linear causality",
      "predicate": "undermines(linearCausality, remoteAndAggregateCauses)"
    },
    {
      "id": "sub-b-9-inv-2",
      "constraint": "occasion and stimulus point beyond finite causality",
      "predicate": "pointsBeyond(occasionStimulus, finiteCausality)"
    }
  ],
  "forces": [
    {
      "id": "sub-b-9-force-1",
      "description": "Finite causality sublates into reciprocity of action",
      "type": "passover",
      "trigger": "finiteCausality.selfContradiction = explicit",
      "effect": "reciprocity.emerges = true",
      "targetState": "sub-c-1"
    }
  ],
  "transitions": [
    {
      "id": "sub-b-9-trans-1",
      "from": "sub-b-9",
      "to": "sub-c-1",
      "mechanism": "passover",
      "description": "From finite causality to reciprocity of action"
    }
  ],
  "nextStates": [
    "sub-c-1"
  ],
  "previousStates": [
    "sub-b-5"
  ],
  "provenance": {
    "topicMapId": "sub-b-9-contingent-side-being",
    "lineRange": {
      "start": 227,
      "end": 340
    },
    "section": "The Relation of Causality",
    "order": 9
  },
  "description": "Cause has further content (contingent side-being) not entering into cause. Remote cause: alteration of form hides identity, several causes together contain complete effect. Shot not cause by itself, only moment of possibility. Inadmissible: causality to physico-organic/spiritual life. Living thing determines/alters/transmutes, sublates cause. Spirit does not admit originative principle, interrupts/transmutes. Effect cannot be greater than cause. Small causes/great effects = occasion/stimulus, spirit determines occasion. Conversion sublates causality.",
  "keyPoints": [
    "cause",
    "further content",
    "contingent side-being",
    "not entering into cause",
    "remote cause",
    "alteration of form",
    "hides identity",
    "several causes together",
    "contain complete effect",
    "shot",
    "not cause by itself",
    "moment of possibility",
    "inadmissible",
    "causality",
    "physico-organic",
    "spiritual life",
    "living thing",
    "determines",
    "alters",
    "transmutes",
    "sublates cause",
    "spirit",
    "does not admit originative principle",
    "interrupts",
    "transmutes",
    "effect cannot be greater than cause",
    "small causes",
    "great effects",
    "occasion",
    "stimulus",
    "spirit determines occasion",
    "conversion",
    "sublates causality"
  ]
};

export const relationCausalityIR: DialecticIR = {
  id: "relation-causality-ir",
  title: "Relation Causality IR: Formal Causality, Extinguishing, Reciprocity Passover",
  section: "ESSENCE - C. ACTUALITY - Absolute Relation - b. Causality",
  states: [
    stateSubB1,
    stateSubB5,
    stateSubB9,
  ],
  metadata: {
  "sourceFile": "relation-causality.txt",
  "totalStates": 3,
  "cpuGpuMapping": {
    "sub-b-1": "appearance",
    "sub-b-5": "appearance",
    "sub-b-9": "appearance"
  }
},
};

export const relationCausalityStates = {
  "sub-b-1": stateSubB1,
  "sub-b-5": stateSubB5,
  "sub-b-9": stateSubB9,
};
