packages:
  - reality
  - core
  - logic
  - model
  - task

ignoredBuiltDependencies:
  - '@firebase/util'
  - '@scarf/scarf'
  - esbuild
  - protobufjs

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
