/**
 * TopicMap for specifying-measure.txt - Specifying Measure
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - specifying-measure-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const SPECIFYING_MEASURE_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/measure/specific-quantity/sources/specifying-measure.txt',
  'Hegel\'s Science of Logic - Measure',
  'Specifying Measure',
  [
    createTopicMapEntry(
      'sq-b-intro-specifying-measure-structure',
      'Specifying measure — three moments',
      [3, 11],
      'Specifying measure: (1) rule, measure external to mere quantum, (2) specific quantity determining external quantum, (3) two sides as qualities relate as one measure.',
      [
        'specifying measure',
        'first',
        'rule',
        'measure external to mere quantum',
        'second',
        'specific quantity',
        'determining external quantum',
        'third',
        'two sides',
        'qualities',
        'specific quantitative determinacy',
        'relate to one another',
        'one measure',
      ],
      { section: 'Specifying Measure', order: 1 }
    ),

    createTopicMapEntry(
      'sq-b-a-1-the-rule',
      'The rule — unit determinate in itself',
      [15, 30],
      'Rule = magnitude determinate in itself, unit with respect to quantum of particular concrete existence. Quantum measured by rule = amount of unit. Comparison = external act. Unit = arbitrary magnitude, can be posited as amount. Measure not only external rule; as specific measure relates to its other (quantum).',
      [
        'rule',
        'standard',
        'magnitude',
        'determinate in itself',
        'unit',
        'with respect to quantum',
        'particular concrete existence',
        'quantum',
        'concrete existence',
        'other than something of rule',
        'measured by',
        'determined as amount',
        'comparison',
        'external act',
        'arbitrary magnitude',
        'posited as amount',
        'foot',
        'inches',
        'not only external rule',
        'specific measure',
        'intrinsic nature',
        'relates to its other',
        'quantum',
      ],
      { section: 'Specifying Measure', order: 2 }
    ),

    createTopicMapEntry(
      'sq-b-b-1-specifying-measure-determining',
      'Specifying measure — determining external magnitude',
      [34, 65],
      'Measure = specific determining of external magnitude (indifferent magnitude posited in measuring something by other concrete existence). Something of measure = quantum but qualitative side determining indifferent external quantum. Has being-for-other, fluctuation in size. Immanent measuring = quality. Something with internal measure: alteration from outside, does not take arithmetical aggregate, measure reacts as intensive measure, assimilates typically, alters externally imposed alteration, demonstrates for-itself. Specified aggregate = quantum dependent on other, alterable but not quantum as such = external quantum specified constantly. Measure = ratio, specificity = exponent.',
      [
        'measure',
        'specific determining',
        'external magnitude',
        'indifferent magnitude',
        'posited',
        'measuring something',
        'other concrete existence',
        'something of measure',
        'quantum',
        'qualitative side',
        'determining',
        'indifferent external quantum',
        'being-for-other',
        'fluctuation in size',
        'immanent measuring',
        'quality',
        'something',
        'confronted by same quality',
        'another something',
        'quality relative',
        'measureless quantum',
        'something determined as measuring',
        'internal measure',
        'alteration',
        'magnitude of quality',
        'comes from outside',
        'does not take on',
        'arithmetical aggregate',
        'measure reacts',
        'intensive measure',
        'assimilates',
        'typically its own',
        'alters externally imposed alteration',
        'makes something else',
        'specifying function',
        'for-itself',
        'specifically assimilated aggregate',
        'quantum',
        'dependent on other',
        'other aggregate',
        'external to it',
        'specified aggregate',
        'alterable',
        'not quantum as such',
        'external quantum',
        'specified in constant manner',
        'determinate existence',
        'ratio',
        'specificity',
        'exponent',
      ],
      { section: 'Specifying Measure', order: 3 }
    ),

    createTopicMapEntry(
      'sq-b-b-2-intensive-extensive-vs-specifying',
      'Intensive/extensive vs specifying measure — quantum alteration',
      [67, 78],
      'Intensive/extensive: same quantum, form of intensity vs extension. Underlying quantum not altered; difference = external form. Specifying measure: quantum in immediate magnitude, through exponent taken in another amount.',
      [
        'intensive',
        'extensive',
        'quantum',
        'same quantum',
        'form of intensity',
        'form of extension',
        'underlying quantum',
        'does not suffer alteration',
        'difference',
        'external form',
        'specifying measure',
        'quantum taken',
        'immediate magnitude',
        'through exponent',
        'ratio',
        'second instance',
        'another amount',
      ],
      { section: 'Specifying Measure', order: 4 }
    ),

    createTopicMapEntry(
      'sq-b-b-3-exponent-as-qualitative-moment',
      'Exponent as qualitative moment — power determination',
      [80, 104],
      'Exponent can appear as fixed quantum (quotient), but then = external quantum. Exponent = qualitative moment specifying quantum. Only immanent qualitative determination = exponent. Exponential determination constitutes ratio, internally existent, confronts externally constituted quantum. Principle = numerical one (internal determinateness). Mode of connection = external. Alteration = addition of numerical ones. External quantum alters arithmetically; qualitative nature produces series referring to first, ratio numerically incommensurable = power determination.',
      [
        'exponent',
        'element of specificity',
        'can appear',
        'fixed quantum',
        'quotient',
        'ratio',
        'external',
        'qualitatively determined quantum',
        'external quantum',
        'qualitative moment',
        'specifies quantum',
        'strictly immanent qualitative determination',
        'exponential determination',
        'constitutes ratio',
        'internally existent determination',
        'confronts',
        'externally constituted quantum',
        'principle',
        'numerical one',
        'internal determinateness',
        'mode of connection',
        'external',
        'alteration',
        'nature of immediate quantum',
        'addition',
        'numerical one',
        'external quantum alters',
        'arithmetical progression',
        'specifying reaction',
        'qualitative nature',
        'produces another series',
        'refers to first',
        'increases and decreases',
        'ratio determined by numerical exponent',
        'numerically incommensurable',
        'power determination',
      ],
      { section: 'Specifying Measure', order: 5 }
    ),

    createTopicMapEntry(
      'sq-b-c-1-relation-as-qualities',
      'Relation of two sides as qualities — indivisible unity',
      [108, 141],
      'Qualitative side exists only as reference to external quantitative side; specifying = sublating externality. Qualitative side has quantum as presupposition. Quantum qualitatively distinguished from quality; difference posited in immediacy of being. Two sides = qualitative existence for itself. Quantum = double being (external + specific). Each quantity has double determination, inextricably interwoven. Qualities posited as indivisible. Specific magnitude = qualitative unity. Measure = immanent quantitative relating of two qualities.',
      [
        'qualitative side',
        'quantum',
        'in itself determined',
        'exists only as reference',
        'external quantitative side',
        'specifying',
        'sublating externality',
        'quantum as such',
        'presupposition',
        'qualitatively distinguished',
        'quality',
        'difference',
        'posited',
        'immediacy of being',
        'characterizes measure',
        'two sides',
        'qualitative respect',
        'qualitative existence for itself',
        'internally indeterminate',
        'formal quantum',
        'quantum of something',
        'quantum of quality',
        'reciprocal reference',
        'determined as measure',
        'specific magnitude',
        'qualities',
        'stand in relation',
        'determination of measure',
        'exponent',
        'implicitly connected',
        'being-for-itself of measure',
        'double being',
        'external quantum',
        'specific quantum',
        'distinct quantities',
        'double determination',
        'inextricably interwoven',
        'qualities determined',
        'determinate being',
        'existing for each other',
        'posited as indivisible',
        'specific magnitude',
        'qualitative unity',
        'one determination of measure',
        'implicitly bound together',
        'concept',
        'immanent quantitative relating',
        'two qualities',
      ],
      { section: 'Specifying Measure', order: 6 }
    ),

    createTopicMapEntry(
      'sq-b-c-2-variable-magnitude',
      'Variable magnitude — ratio of powers',
      [143, 169],
      'Measure = essential determination of variable magnitude. Measure = sublated quantum; quantum as quantum and something other (qualitative element = relation of powers). Immediate measure: variability not posited, single quantum with quality. Specifying measure: alteration of external quantum by qualitative moment, distinctness of two magnitudes, plurality of measures. Differentiation of quantum from itself = real measure (one and same, diversified quantitative existence). Differentiation into diverse qualities = realized measure (two sides as qualitatively determined quanta).',
      [
        'measure',
        'essential determination',
        'variable magnitude',
        'sublated quantum',
        'quantum',
        'ought to be',
        'quantum as quantum',
        'something other',
        'qualitative element',
        'relation of powers',
        'immediate measure',
        'variability',
        'not posited',
        'single quantum',
        'quality attached',
        'specifying of measure',
        'preceding determination',
        'alteration',
        'merely external quantum',
        'qualitative moment',
        'distinctness',
        'two determinate magnitudes',
        'plurality of measures',
        'common external quantum',
        'differentiation',
        'quantum from itself',
        'real measure',
        'one and the same',
        'constant temperature',
        'medium',
        'diversified',
        'quantitative existence',
        'various temperatures',
        'bodies',
        'differentiation of quantum',
        'diverse qualities',
        'different bodies',
        'further form of measure',
        'two sides',
        'relate to each other',
        'qualitatively determined quanta',
        'realized measure',
      ],
      { section: 'Specifying Measure', order: 7 }
    ),

    createTopicMapEntry(
      'sq-b-c-3-genuine-alteration-power-determination',
      'Genuine alteration — power determination, extensive vs intensive',
      [171, 243],
      'Magnitude alterable (limit which is none). Genuine alteration = quantum as such. Variable magnitude = qualitative, determined by ratio of powers. Quantum has no value as such, only as determined qualitatively. Two sides: amount (arithmetical progression) vs unit (specifically determined). Extensive = externality within; intensive = exists in itself, negative. Amount = extensive (dividend/power); unit = intensive (divisor/root). External quantum = empirical; alteration arithmetical on unit (intensive); extensive alters in specified series. Direct ratio = formal, no concrete existence. Higher realization: both sides in higher powers (s^3 = at^2).',
      [
        'magnitude',
        'alterable',
        'determinateness',
        'limit which at the same time is none',
        'alteration',
        'affects',
        'particular quantum',
        'another posited',
        'genuine alteration',
        'quantum as such',
        'determination',
        'variable magnitude',
        'higher mathematics',
        'formal determination',
        'alteration',
        'variability',
        'simple determination of concept',
        'other of quantum',
        'qualitative',
        'genuine determination',
        'real variable magnitude',
        'qualitative',
        'determined by ratio of powers',
        'quantum has no value as such',
        'determined in conformity with its other',
        'qualitatively',
        'two sides',
        'abstract side',
        'qualities in general',
        'particular meaning',
        'space',
        'time',
        'determinacies of magnitude',
        'ratio of measure',
        'amount',
        'increases and decreases',
        'external arithmetical progression',
        'unit',
        'specifically determined',
        'other amount',
        'particular quality',
        'no way of distinguishing',
        'merely externally quantitative',
        'varying in quantitative specification',
        'root and square',
        'indifferent',
        'increasing or decreasing',
        'specific determination',
        'two qualities',
        'not indeterminate',
        'difference',
        'moments of measure',
        'qualification',
        'determinateness of qualities',
        'extensive',
        'externality within',
        'intensive',
        'exists in itself',
        'negative',
        'as against other',
        'amount',
        'quantitative moment',
        'pertains to',
        'unit',
        'simple direct ratio',
        'dividend',
        'divisor',
        'specifying ratio',
        'power',
        'becoming-other',
        'root',
        'count',
        'reflect on external quantum',
        'totally accidental determinateness',
        'empirical',
        'alteration',
        'advancing',
        'external arithmetical progression',
        'falls on',
        'unit',
        'intensive quality',
        'external extensive side',
        'represented as altering',
        'specified series',
        'direct ratio',
        'velocity',
        'st',
        'formal determination',
        'no concrete existence',
        'abstraction of reflection',
        'ratio of root and square',
        's = at^2',
        'empirical quantum',
        'varying in arithmetical progression',
        'other side',
        'specified',
        'higher realization',
        'qualification of quantitative moment',
        'more in keeping with concept',
        'both sides',
        'higher determinations of powers',
        's^3 = at^2',
      ],
      { section: 'Specifying Measure', order: 8 }
    ),
  ],
  {
    sectionDescription: 'Specifying Measure - Three moments: rule, specific quantity, relation as qualities. The rule (unit determinate in itself, external comparison). Specifying measure (determining external magnitude, intensive measure, ratio and exponent). Intensive/extensive vs specifying (quantum alteration difference). Exponent as qualitative moment (power determination, numerically incommensurable ratio). Relation of two sides as qualities (indivisible unity, double determination). Variable magnitude (ratio of powers, realized measure). Genuine alteration (power determination, extensive vs intensive, higher powers).',
  }
);

