import type { DialecticIR, DialecticState } from '@schema/dialectic';

// Generated by src/tools/generate-real-measure-ir.ts
const stateRealMeasure3: DialecticState = {
  "id": "real-measure-3",
  "title": "Measureless progression and substantive persistence",
  "concept": "MeasurelessProgression",
  "phase": "quantity",
  "moments": [
    {
      "name": "measurelessDrive",
      "definition": "Measure is driven into a progression that exceeds any fixed finite measure-state",
      "type": "process"
    },
    {
      "name": "substantialMatter",
      "definition": "Beneath changing measures persists a substantial self-sameness",
      "type": "determination",
      "relation": "contains",
      "relatedTo": "measurelessDrive"
    },
    {
      "name": "indifferenceThreshold",
      "definition": "Progressive determination culminates in indifference as threshold to essence",
      "type": "mediation"
    }
  ],
  "invariants": [
    {
      "id": "real-measure-3-inv-1",
      "constraint": "measureless progression remains determinate",
      "predicate": "determinateProgression(measureless)"
    },
    {
      "id": "real-measure-3-inv-2",
      "constraint": "substance persists through quantitative difference",
      "predicate": "persistence(substance)"
    }
  ],
  "forces": [
    {
      "id": "real-measure-3-force-1",
      "description": "Measureless culmination passes over into becoming essence",
      "type": "passover",
      "trigger": "indifferenceThreshold.reached = true",
      "effect": "becomingEssence.initiated = true",
      "targetState": "becoming-essence-1"
    }
  ],
  "transitions": [
    {
      "id": "real-measure-3-trans-1",
      "from": "real-measure-3",
      "to": "becoming-essence-1",
      "mechanism": "passover",
      "description": "From measureless progression to becoming essence"
    }
  ],
  "nextStates": [
    "becoming-essence-1"
  ],
  "previousStates": [
    "real-measure-2-leap"
  ],
  "provenance": {
    "topicMapId": "rm-c-8-progressive-determination-summary",
    "lineRange": {
      "start": 132,
      "end": 174
    },
    "section": "The Measureless",
    "order": 8
  },
  "description": "Progressive determination: Measure = immediate unity of quality and quantity (common quantum, specific). Measure = ratio (determinateness referring to itself). Holds moments as sublated/unseparated. Difference real, yields multitude of measure-relations (formal totalities, self-subsistent). Series = constant ordering. Ordering = immanently specifying unity, but principle = substrate/matter. Differences have only external quantitative determination (qualitative differentiation). In self-unity: measure determination = sublated, quality = external state determined by quantum. Course = progressive determination of measure + demotion to moment.",
  "keyPoints": [
    "reviewing",
    "progressive determination",
    "measure",
    "gone through",
    "moments",
    "progression",
    "summed up",
    "measure",
    "first",
    "itself",
    "immediate unity",
    "quality",
    "quantity",
    "form",
    "common quantum",
    "specific",
    "determinateness",
    "quantity",
    "refers",
    "other",
    "refers to itself",
    "measure",
    "essentially",
    "ratio",
    "consequently",
    "holds",
    "moments",
    "sublated",
    "unseparated",
    "itself",
    "always",
    "case",
    "concept",
    "difference",
    "ratio",
    "each",
    "moments",
    "itself",
    "unity",
    "qualitative",
    "quantitative moment",
    "difference",
    "real",
    "yields",
    "multitude",
    "measure-relations",
    "formal totalities",
    "each",
    "self-subsistent",
    "themselves",
    "series",
    "form",
    "two sides",
    "ratios",
    "each single member",
    "same constant ordering",
    "member",
    "belonging",
    "one side",
    "relates itself",
    "whole series",
    "standing opposite",
    "ordering",
    "mere order",
    "still wholly external unity",
    "demonstrates itself",
    "immanently specifying unity",
    "measure",
    "determinate being-for-itself",
    "distinguished",
    "specifications",
    "specifying principle",
    "not yet",
    "free concept",
    "alone",
    "gives",
    "differences",
    "immanent determination",
    "principle",
    "first",
    "substrate",
    "matter",
    "differences",
    "order",
    "totalities",
    "should have",
    "themselves",
    "nature",
    "stable",
    "self-equal substrate",
    "available",
    "external quantitative determination",
    "shows itself",
    "same time",
    "qualitative differentiation",
    "self-unity",
    "substrate",
    "determination",
    "measure",
    "sublated determination",
    "quality",
    "external state",
    "determined",
    "quantum",
    "course",
    "equally",
    "progressive determination",
    "measure",
    "demotion",
    "moment"
  ]
};

export const measurelessIR: DialecticIR = {
  id: "measureless-ir",
  title: "Measureless IR: Progressive Determination",
  section: "BEING - MEASURE - B. Real Measure - The Measureless",
  states: [
    stateRealMeasure3,
  ],
  metadata: {
  "sourceFile": "measureless.txt",
  "totalStates": 1,
  "cpuGpuMapping": {
    "real-measure-3": "quantity"
  }
},
};

export const measurelessStates = {
  "real-measure-3": stateRealMeasure3,
};
