import type { TopicMapEntry } from '@schema/topic';

/**
 * TopicMap for one-many.txt - B. THE ONE AND THE MANY
 *
 * This TopicMap follows B. THE ONE AND THE MANY in the source text.
 *
 * Structure:
 * - B. THE ONE AND THE MANY (simple reference and determining)
 * - a. The one within (unalterable and void)
 * - b. The one and the void (existence and externalization)
 * - c. Many ones / Repulsion (repulsion and plurality)
 */
export const oneManyTopicMap: TopicMapEntry[] = [
  {
    id: 'one-many-b',
    title: 'B. THE ONE AND THE MANY — simple reference and determining',
    lineRange: { start: 2, end: 41 },
    description:
      "The one is the simple reference of being-for-itself to itself in which its moments have fallen together; in which, therefore, being-for-itself has the form of immediacy and its moments, therefore, are now there as existents. As the self-reference of the negative, the one is a determining; and, as self-reference, it is infinite self-determining. However, because of the present immediacy, these distinctions are no longer only moments of one and the same self-determination but are at the same time posited as existents. The ideality of the being-for-itself as a totality thus turns at first into reality; a reality, moreover, of the most fixed and abstract kind, as a one. In the one, the being-for-itself is the posited unity of being and existence, as the absolute union of the reference to another and the reference to itself; but also the determinateness of being then enters into opposition to the determination of the infinite negation, to self-determination, so that what the one is in itself, it is that now only in it, and the negative consequently is an other distinct from it. What shows itself to be present as distinct from the one is the one's own self-determining; its unity with itself, as thus distinct from itself, is demoted to reference, and, as negative unity, it is negation of itself as other, the excluding of the one as an other from itself, from the one.",
    keyPoints: [
      'One is simple reference of being-for-itself to itself',
      'Moments have fallen together',
      'Being-for-itself has form of immediacy, moments are existents',
      'As self-reference of negative, one is determining',
      'As self-reference, infinite self-determining',
      'Because of immediacy, distinctions are moments and existents',
      'Ideality of being-for-itself turns into reality',
      'Reality of most fixed and abstract kind, as a one',
      'One is posited unity of being and existence',
      'Absolute union of reference to another and reference to itself',
      'Determinateness of being enters into opposition to infinite negation',
      'Negative is other distinct from it',
      "One's own self-determining shows itself as distinct",
      'Unity demoted to reference, as negative unity',
      'Negation of itself as other, excluding of one as other from itself',
    ],
    status: 'pending',
    section: 'B. THE ONE AND THE MANY',
    order: 1,
    relatedChunks: ['one-many-a'],
  },
  {
    id: 'one-many-a',
    title: 'a. The one within — unalterable and void',
    lineRange: { start: 43, end: 82 },
    description:
      'Within it, the one just is; this, its being, is not an existence, not a determination as reference to an other, not a constitution; it is rather its having negated this circle of categories. The one is not capable, therefore, of becoming any other; it is unalterable. It is indeterminate, yet no longer like being; its indeterminateness is the determinateness of self-reference, absolutely determined being; posited in-itselfness. As negation which, in accordance with its concept, is self-referring, it has distinction in it: it directs away from itself towards another, but this direction is immediately reversed, because, according to this moment of self-determining, there is no other to which it would be addressed, and the directing reverts back to itself. In this simple immediacy, even the mediation of existence and ideality, and with it all diversity and manifoldness, have vanished. In the one there is nothing; this nothing, the abstraction of self-reference, is here distinguished from the in-itselfness of the one; it is a posited nothing, for this in-itselfness no longer has the simplicity of the something, but, as mediation, has rather the determination of being concrete; taken in abstraction, it is indeed identical with the one, but different from its determination. So this nothing, posited as in the one, is the nothing as the void. The void is thus the quality of the one in its immediacy.',
    keyPoints: [
      'Within it, one just is',
      'Its being is not existence, not determination as reference to other, not constitution',
      'Has negated this circle of categories',
      'One is not capable of becoming any other, unalterable',
      'Indeterminate, yet no longer like being',
      'Indeterminateness is determinateness of self-reference',
      'Absolutely determined being, posited in-itselfness',
      'As negation self-referring, has distinction in it',
      'Directs away from itself towards another, immediately reversed',
      'No other to which it would be addressed, directing reverts back',
      'In simple immediacy, mediation of existence and ideality vanished',
      'All diversity and manifoldness have vanished',
      'In the one there is nothing',
      'Nothing, abstraction of self-reference, distinguished from in-itselfness',
      'Posited nothing, in-itselfness has determination of being concrete',
      'Nothing posited as in one is nothing as void',
      'Void is quality of one in its immediacy',
    ],
    status: 'pending',
    section: 'a. The one within',
    order: 1,
    relatedChunks: ['one-many-b', 'one-many-b-1'],
  },
  {
    id: 'one-many-b-1',
    title: 'b. The one and the void — existence and externalization',
    lineRange: { start: 84, end: 109 },
    description:
      'The one is the void as the abstract self-reference of negation. But the void, as nothing, is absolutely diverse from the simple immediacy of the one, from the being of the latter which is also affirmative, and because the two stand in one single reference, namely to the one, their diversity is posited; however, as distinct from the affirmative being, the nothing stands as void outside the one as existent. Being-for-itself, determined in this way as the one and the void, has again acquired an existence. The one and the void have their negative self-reference as their common and simple terrain. The moments of being-for-itself come out of this unity, become external to themselves; for through the simple unity of the moments the determination of being comes into play, and the unity itself thus withdraws to one side, is therefore lowered to existence, and there it is confronted by its other determination standing over against it, negation as such and likewise as the existence of the nothing, as the void.',
    keyPoints: [
      'One is void as abstract self-reference of negation',
      'Void as nothing is absolutely diverse from simple immediacy of one',
      'From being of latter which is also affirmative',
      'Two stand in one single reference, namely to one, diversity posited',
      'As distinct from affirmative being, nothing stands as void outside one as existent',
      'Being-for-itself determined as one and void has again acquired existence',
      'One and void have negative self-reference as common and simple terrain',
      'Moments of being-for-itself come out of unity, become external to themselves',
      'Through simple unity of moments, determination of being comes into play',
      'Unity withdraws to one side, lowered to existence',
      'Confronted by other determination standing over against it',
      'Negation as such and likewise as existence of nothing, as void',
    ],
    status: 'pending',
    section: 'b. The one and the void',
    order: 2,
    relatedChunks: ['one-many-a', 'one-many-c'],
  },
  {
    id: 'one-many-c',
    title: 'c. Many ones — repulsion and plurality',
    lineRange: { start: 111, end: 248 },
    description:
      "The one and the void constitute the first existence of being-for-itself. Each of these moments has negation for its determination, and is posited at the same time as an existence. The one and the void are each the reference of negation to negation as of an other to its other: the one is negation in the determination of being; the void, negation in the determination of non-being. Essentially, however, the one is only self-reference as referring negation, that is, it is itself the same as the void outside it is supposed to be. The one is consequently a becoming of many ones. Strictly speaking, however, this is not just a becoming; for becoming is a transition of being into nothing; the one, by contrast, becomes only a one. The one's own immanent reference is present; and, since this reference is negative and the one is at the same time an existent, the one repels itself from itself. This negative reference of the one to itself is repulsion. Repulsion is the positing of many ones through the one itself, the one's own coming-forth-from-itself, but to such outside it as are themselves only ones. The ones are presupposed with respect to each other through the repulsion of the one from itself; presupposed, posited as non-posited; their being-posited is sublated, they are existents referring only to themselves. Plurality appears not as otherness, but as a determination completely external to the one. The void is their limit, an external limit in which they are not supposed to be for one another. The void is determined as pure non-being, and this alone constitutes the limit of the ones. Repulsion is the making explicit of what the one is implicitly in itself; but, thus laid out as one-outside-the-other, infinity is here an infinity that has externalized itself. Plurality of the ones is infinity as a contradiction that unconstrainedly produces itself.",
    keyPoints: [
      'One and void constitute first existence of being-for-itself',
      'Each moment has negation for determination, posited as existence',
      'One and void are reference of negation to negation as other to other',
      'One is negation in determination of being; void, negation in determination of non-being',
      'Essentially, one is only self-reference as referring negation',
      'Same as void outside it is supposed to be',
      'One is consequently becoming of many ones',
      'Not just becoming (transition of being into nothing)',
      'One becomes only a one',
      "One's own immanent reference is present",
      'Reference is negative and one is existent, one repels itself from itself',
      'Negative reference of one to itself is repulsion',
      'Repulsion is positing of many ones through one itself',
      "One's own coming-forth-from-itself, to outside as ones",
      'Repulsion according to concept, as exists implicitly',
      'Second repulsion distinguished: mutual holding off of ones presupposed',
      'Many ones have determinations as such',
      'Becoming of many immediately vanishes as product of positing',
      'Produced are ones, infinitely referring to themselves',
      'One repels only itself from itself, already is',
      'Repelled is equally one, existent',
      'Repelling and being repelled applies to both',
      'Ones presupposed with respect to each other through repulsion',
      'Presupposed, posited as non-posited',
      'Being-posited is sublated, existents referring only to themselves',
      'Plurality appears not as otherness, but as determination external to one',
      'One in repelling remains reference to itself',
      'Ones are other to one another, brought together in determinateness of plurality',
      'Does not concern the one',
      'If plurality were reference of ones to one another, ones would limit each other',
      'Connecting reference determined as none, previously posited void',
      'Void is their limit, external limit in which not supposed to be for one another',
      'Void determined as pure non-being, constitutes limit of ones',
      'Repulsion is making explicit of what one is implicitly',
      'Laid out as one-outside-the-other, infinity externalized itself',
      'Through immediacy of infinite, of one',
      'Infinity is simple reference of one to one',
      "One's absolute lack of reference",
      'According to simple affirmative reference of one to itself',
      'According to same reference as negative',
      "Plurality of ones is one's own positing of one",
      'One is nothing but negative reference of one to itself',
      'Reference is plural one',
      'Plurality is utterly external to one',
      'One is precisely sublating of otherness',
      'Repulsion is self-reference and simple equality with itself',
      'Plurality of ones is infinity as contradiction that unconstrainedly produces itself',
    ],
    status: 'pending',
    section: 'c. Many ones / Repulsion',
    order: 3,
    relatedChunks: ['one-many-b-1'],
  },
];
