/**
 * REPULSION AND ATTRACTION: The Final Dialectical Unity
 * ====================================================
 *
 * The culmination of Being-for-Self showing the complete dialectical
 * interplay between repulsion and attraction as the final resolution
 * of the One-Many problem and transition to Quantity.
 *
 * Based on Hegel's Logic, showing how:
 * - Repulsion generates the Many but requires Attraction
 * - Attraction posits the One but presupposes Repulsion
 * - Each is the self-mediation of itself through the other
 * - Their unity provides the transition to Quantity
 *
 * "Each is in itself only a moment, this is the transition of each
 *  from itself into the other, the negation of itself in the other
 *  and the positing of itself as the other of itself."
 */

/**
 * Base interface for repulsion-attraction dialectic
 */
interface RepulsionAttractionMoment {
  dialecticalMovement(): string;
  getSelfPresupposing(): string;
  getOtherPresupposing(): string;
  getSelfMediation(): string;
}

/**
 * EXCLUSION OF THE ONE
 * ====================
 *
 * How repulsion becomes relative and mutual exclusion
 */
class ExclusionOfTheOne implements RepulsionAttractionMoment {
  private mutualRepulsion: string;
  private beingForOther: string;
  private selfDissolution: string;

  constructor() {
    this.mutualRepulsion = "mutual repulsion as common connecting reference";
    this.beingForOther = "being-for-one becomes being-for-other";
    this.selfDissolution = "self-preservation becomes dissolution";
  }

  dialecticalMovement(): string {
    return `EXCLUSION OF THE ONE - From Absolute to Relative Repulsion:

    The Demonstrated Contradiction:
    - Many ones are each a being
    - Their existence/reference to one another is non-reference: abstract void
    - But they themselves are now this negative reference to existent others
    - The demonstrated contradiction: infinity posited in immediacy of being

    Relative Repulsion:
    - Repulsion now finds immediately before it what is repelled by it
    - In this determination, it is an EXCLUDING
    - One repels from itself only many not generated by it
    - Ones not posited by it - this repelling is mutual, from all sides
    - Limited by being of the ones - RELATIVE repulsion

    The Connecting Reference:
    - Plurality not at first posited otherness
    - Limit only the void - only that in which ones are not
    - But in the limit they also ARE - they are in the void
    - Their repulsion IS their common connecting reference
    - Mutual repulsion = posited existence of many ones`;
  }

  getSelfPresupposing(): string {
    return `The Contradiction of Being-for-Other:
    - Not their being-for-itself (would distinguish them only in a third)
    - But their own distinguishing which preserves them
    - They mutually negate themselves, posit one another as being only for-one
    - But simultaneously negate this being only for-one
    - They repel the ideality that they have and are

    The Moment Split:
    - In ideality, moments absolutely united - but now come apart
    - In being-for-itself: one is also for-one, but this one is itself
    - Distinguishing from itself immediately sublated
    - But in plurality: distinguished one has a being
    - Being-for-one determined in exclusion = BEING-FOR-OTHER`;
  }

  getOtherPresupposing(): string {
    return `Each Repelled by Another:
    - Each comes to be repelled by an other
    - Sublated and made into one not for itself but for-one
    - And an OTHER one at that
    - Being-for-itself of many ones shows itself as self-preservation
    - Through mediation of mutual repulsion
    - In which they sublate themselves reciprocally
    - Posit others as mere being-for-another`;
  }

  getSelfMediation(): string {
    return `The Dissolution Through Self-Preservation:
    - Self-preservation consists in repelling ideality
    - Positing ones as not being for-an-other
    - But this self-preservation through negative reference
    - Is rather their DISSOLUTION

    The Identity in Difference:
    - Ones maintain themselves through reciprocal exclusion
    - In their being-in-itself: should have firm support for diversity
    - But they all ARE this - in being-in-itself, all the same
    - Their positing themselves as one = reciprocal negating
    - This likewise one and same determination of all
    - They posit themselves as IDENTICAL
    - According to being and positing: only one affirmative unity

    RESULT: The negative relating of ones to one another
    is consequently only a coming-together-with-oneself
    - This identity sublates their diversity and externality
    - This self-positing-in-a-one of many ones IS ATTRACTION`;
  }
}

/**
 * THE ONE ONE OF ATTRACTION
 * =========================
 *
 * How attraction realizes ideality and mediates through repulsion
 */
class OneOneOfAttraction implements RepulsionAttractionMoment {
  private realizedIdeality: string;
  private mediatedOne: string;
  private unityOfBoth: string;

  constructor() {
    this.realizedIdeality = "ideality realized, posited in the one";
    this.mediatedOne = "the one posited as one through mediation";
    this.unityOfBoth = "unity of repulsion and attraction in general";
  }

  dialecticalMovement(): string {
    return `THE ONE ONE OF ATTRACTION - Realized Ideality:

    Transition of Repulsion to Attraction:
    - Repulsion = fragmentation of one into many
    - First into many of which it is negative relating
    - Since they presuppose each other as existent
    - Only the ought of ideality - but realized in attraction
    - REPULSION PASSES OVER INTO ATTRACTION
    - Many ones into one one

    Distinguished Yet Inseparable:
    - Both at first distinguished from each other
    - Repulsion as reality of ones, attraction as posited ideality
    - Attraction refers to repulsion by having it for presupposition
    - Repulsion delivers the material for attraction
    - If no ones, nothing to attract - attraction presupposes repulsion`;
  }

  getSelfPresupposing(): string {
    return `The Presupposition Structure:
    - If attraction accomplished (many brought to point of one one)
    - Result would be inert one, no longer any attraction
    - Ideality in attraction has determination of negation of itself
    - The many ones to which it refers
    - ATTRACTION IS INSEPARABLE FROM REPULSION

    No Immediate Precedence:
    - To attract pertains equally to each many ones as immediately present
    - None has advantage over another
    - Would result in equilibrium in attraction and repulsion
    - Inert state of rest without ideality present
    - No question of immediately present one taking precedence
    - This would presuppose determinate distinction between them`;
  }

  getOtherPresupposing(): string {
    return `Attraction as Positing of Distinction:
    - Attraction is positing of given lack of distinction among ones
    - Attraction itself posits a one distinct from other ones
    - These are only immediate ones preserving themselves through repulsion
    - Through their posited negation: proceeds the ONE OF ATTRACTION
    - Therefore determined as the MEDIATED ONE
    - The one posited as one

    Immediate vs Mediated:
    - First ones as immediate do not return into themselves in ideality
    - Have this ideality each in another
    - The one one = ideality that has been realized, posited in the one`;
  }

  getSelfMediation(): string {
    return `The One One's Self-Mediation:
    - It attracts through mediation of repulsion
    - Contains in itself this mediation as its determination
    - Does not swallow attracted ones into one point
    - Does not sublate them abstractly
    - Since contains repulsion in determination
    - Latter equally preserves ones as many within it

    The Area or Filling:
    - By its attracting, it musters something before it
    - Gains an area or a filling
    - Thus there is in it the UNITY OF REPULSION AND ATTRACTION IN GENERAL
    - This unity is the key to the entire dialectic`;
  }
}

/**
 * CONNECTION OF REPULSION AND ATTRACTION
 * =====================================
 *
 * The complete dialectical unity and self-mediation of each through other
 */
class ConnectionRepulsionAttraction implements RepulsionAttractionMoment {
  private mutualReference: string;
  private selfPresupposing: string;
  private selfMediation: string;

  constructor() {
    this.mutualReference = "essentially joined together in mutual reference";
    this.selfPresupposing = "each presupposes itself, refers only to itself";
    this.selfMediation = "each is its own self-mediation through the other";
  }

  dialecticalMovement(): string {
    return `CONNECTION OF REPULSION AND ATTRACTION - Complete Unity:

    The Fundamental Structure:
    - Difference of one and many determined as difference of mutual reference
    - Connecting them which breaks down into two: repulsion and attraction
    - Each stands at first outside other on its own
    - In such way that two are essentially joined together nevertheless
    - Their still indeterminate unity must be brought out in detail

    The Apparent Independence:
    - As fundamental determination of one, repulsion appears first
    - Appears as immediate, like its ones generated by it
    - Yet at same time posited as immediate
    - Therefore indifferent to attraction added externally
    - But attraction is NOT presupposed by repulsion`;
  }

  getSelfPresupposing(): string {
    return `Each Presupposes Only Itself:

    Repulsion's Self-Presupposition:
    - Not supposed to have any part in positing/being of attraction
    - As if repulsion were not already in it negation of itself
    - Or ones were not already negated in it
    - Taking mere repulsion for itself: dispersion of many ones in indeterminacy
    - Outside sphere of repulsion itself
    - But repulsion is not just void - ones do not repel their determination
    - Although negative, repulsion nonetheless essentially CONNECTION
    - Mutual repulsion and flight not liberation from what is repelled
    - What is excluded still stands in connection with what excludes it

    Attraction's Self-Presupposition:
    - Attraction is positing of one as such, of real one
    - With respect to which existence of many determined as vanishing idealization
    - Attraction thus directly presupposes itself
    - In determination of many ones to be an idealization
    - Same ones otherwise supposed to have existence for themselves
    - Ideality is presupposed: ideality of ones as existent in itself
    - Inasmuch as they as ones are not distinguished from one another
    - But are ONE AND THE SAME`;
  }

  getOtherPresupposing(): string {
    return `Mutual Presupposition Structure:
    - It is not just repulsion presupposed by attraction
    - But equally present also reverse connection of repulsion to attraction
    - Repulsion no less has attraction for its presupposition
    - As thus determined, they are INSEPARABLE
    - At same time each determined as ought and limitation with respect to other

    Their Ought and Mediation:
    - Their ought = their abstract determinateness as each existent in itself
    - Determinateness directed beyond itself and refers to other
    - Through mediation of other, each is as other
    - Self-subsistence consists in being mutually posited in this mediation
    - As an other determining`;
  }

  getSelfMediation(): string {
    return `The Final Self-Mediation:

    Repulsion and Attraction as Self-Mediation:
    - Repulsion = positing of many; attraction = positing of one
    - Latter equally negation of many; former negation of ideality of many in one
    - Attraction is attraction only through mediation of repulsion
    - Just as repulsion is repulsion through mediation of attraction
    - But mediation of each with itself through other is negated
    - EACH OF THE TWO DETERMINATIONS IS ITS OWN SELF-MEDIATION

    The Coming-Out and Falling-Back:
    - Self-presupposing = positing of oneself in one as negative of oneself (repulsion)
    - What is presupposed in this positing = same as that which presupposes (attraction)
    - Each is in itself only a moment
    - This is transition of each from itself into other
    - Negation of itself in other and positing of itself as other of itself

    THE FINAL UNITY:
    - One as such = coming-out-of-itself
    - Itself only positing of itself as its other, as the many
    - Many for its part = only falling back upon itself
    - Positing of itself as its other, as a one
    - In this equally only connecting of itself to itself
    - Each continuing itself in its other
    - Coming-out-of-itself (repulsion) and self-positing-as-one (attraction)
    - ALREADY INHERENTLY PRESENT AS UNDIVIDED

    The Completed Dialectic:
    - In relative repulsion and attraction (presupposing immediate ones)
    - Posited that two are each, within it, this negation of itself
    - Consequently also continuity of itself in its other
    - Repulsion of existent ones = self-preservation of one
    - Through mutual holding off of others
    - Attraction of existent ones = their ideality and positing of one
    - As both negating and producing of one, attraction sublates itself
    - As positing within it of one, is negative of itself: IS REPULSION

    FINAL RESULT: Complete interpenetration and transition to Quantity`;
  }

  /**
   * The transition to Quantity
   */
  getTransitionToQuantity(): string {
    return `Transition to Quantity:

    The Completed Being-for-Self:
    - Repulsion and attraction are the complete development of being-for-self
    - They are the realized dialectic of the one and many
    - Each is its own self-mediation through the other
    - Their unity is no longer the abstract unity of being-for-self
    - But the concrete unity that has passed through all determinations

    Preparation for Quantity:
    - The equilibrium of repulsion and attraction
    - Points beyond quality to quantity
    - Where the one-many relationship becomes extensive magnitude
    - The void becomes space, the ones become units
    - Repulsion becomes discreteness, attraction becomes continuity
    - Quality passes over into Quantity through this completed dialectic

    This completes the entire development of Quality!
    From Pure Being through Existence to Being-for-Self
    The foundation is now laid for the Logic of Essence`;
  }
}

/**
 * REPULSION AND ATTRACTION SYSTEM
 * ===============================
 *
 * Complete dialectical system showing final unity of Being-for-Self
 */
class RepulsionAttractionSystem {
  private exclusion: ExclusionOfTheOne;
  private oneOne: OneOneOfAttraction;
  private connection: ConnectionRepulsionAttraction;

  constructor() {
    this.exclusion = new ExclusionOfTheOne();
    this.oneOne = new OneOneOfAttraction();
    this.connection = new ConnectionRepulsionAttraction();
  }

  /**
   * Complete dialectical development
   */
  getCompleteRepulsionAttractionDevelopment(): string {
    return `REPULSION AND ATTRACTION - Final Unity of Being-for-Self:

    a. EXCLUSION OF THE ONE:
    ${this.exclusion.dialecticalMovement()}

    Self-Mediation through Other: ${this.exclusion.getSelfMediation()}

    b. THE ONE ONE OF ATTRACTION:
    ${this.oneOne.dialecticalMovement()}

    Unity of Both: ${this.oneOne.getSelfMediation()}

    c. CONNECTION OF REPULSION AND ATTRACTION:
    ${this.connection.dialecticalMovement()}

    Complete Self-Mediation: ${this.connection.getSelfMediation()}

    ${this.connection.getTransitionToQuantity()}`;
  }

  /**
   * The philosophical significance
   */
  getPhilosophicalSignificance(): string {
    return `THE PHILOSOPHICAL SIGNIFICANCE OF REPULSION AND ATTRACTION:

    COMPLETION OF QUALITY:
    - This completes the entire development from Pure Being to Being-for-Self
    - Shows how the One-Many problem resolves into dynamic equilibrium
    - Provides the foundation for all subsequent logical development

    THE DIALECTICAL METHOD REVEALED:
    - Each determination is its own self-mediation through its other
    - What appears as external relation is internal self-development
    - The "other" is always the self in its otherness
    - Opposition is the motor of all logical development

    METAPHYSICAL IMPLICATIONS:
    - Solves the ancient problem of the One and Many
    - Shows unity and multiplicity as moments of single process
    - Demonstrates that reality is essentially self-determining
    - Establishes the logical foundation for physics and philosophy of nature

    TRANSITION TO QUANTITY:
    - Quality has completed its development through all its moments
    - The equilibrium of repulsion and attraction points beyond itself
    - To the realm of Quantity where extensive magnitude emerges
    - The foundation is laid for the entire system of Logic`;
  }

  /**
   * Access to individual moments
   */
  getExclusion(): ExclusionOfTheOne {
    return this.exclusion;
  }

  getOneOne(): OneOneOfAttraction {
    return this.oneOne;
  }

  getConnection(): ConnectionRepulsionAttraction {
    return this.connection;
  }
}

// Export the main classes
export {
  RepulsionAttractionSystem as default,
  ExclusionOfTheOne,
  OneOneOfAttraction,
  ConnectionRepulsionAttraction,
  RepulsionAttractionMoment
};
