import type { DialecticIR, DialecticState } from '@schema/dialectic';

// Generated by src/tools/generate-actuality-actuality-ir.ts
const stateActC1: DialecticState = {
  "id": "act-c-1",
  "title": "Determinate necessity contains contingency",
  "concept": "DeterminateNecessity",
  "phase": "appearance",
  "moments": [
    {
      "name": "determinateNecessity",
      "definition": "Real necessity has content and determinateness",
      "type": "determination"
    },
    {
      "name": "innerContingency",
      "definition": "Negation is internal to necessity as its own moment",
      "type": "negation",
      "relation": "contains",
      "relatedTo": "determinateNecessity"
    }
  ],
  "invariants": [
    {
      "id": "act-c-1-inv-1",
      "constraint": "necessity includes contingency as determinateness",
      "predicate": "contains(necessity, contingency)"
    },
    {
      "id": "act-c-1-inv-2",
      "constraint": "actuality cannot be otherwise",
      "predicate": "not(canBeOtherwise(actuality))"
    }
  ],
  "forces": [
    {
      "id": "act-c-1-force-1",
      "description": "Necessity resolves distinctions into absolute truth of being and essence",
      "type": "sublation",
      "trigger": "difference(content, form) = transparent",
      "effect": "absoluteNecessity.truth = explicit",
      "targetState": "act-c-6"
    }
  ],
  "transitions": [
    {
      "id": "act-c-1-trans-1",
      "from": "act-c-1",
      "to": "act-c-6",
      "mechanism": "sublation",
      "description": "From determinate necessity to absolute necessity as truth"
    }
  ],
  "nextStates": [
    "act-c-6"
  ],
  "previousStates": [
    "act-a-9"
  ],
  "provenance": {
    "topicMapId": "act-c-1-determinate-necessity",
    "lineRange": {
      "start": 3,
      "end": 16
    },
    "section": "Absolute Necessity",
    "order": 1
  },
  "description": "Real necessity = determinate necessity (formal necessity has no content/determinateness). Determinateness = having negation (contingency) within. In first simplicity: determinateness = actuality, determinate necessity = immediate actual necessity. Actuality necessary, contains necessity as in-itself = absolute actuality (cannot be otherwise, in-itself = necessity itself).",
  "keyPoints": [
    "real necessity",
    "determinate necessity",
    "formal necessity",
    "no content",
    "no determinateness",
    "determinateness",
    "having negation",
    "contingency",
    "first simplicity",
    "actuality",
    "immediate actual necessity",
    "necessary",
    "contains necessity as in-itself",
    "absolute actuality",
    "cannot be otherwise",
    "necessity itself"
  ]
};
const stateActC6: DialecticState = {
  "id": "act-c-6",
  "title": "Absolute necessity as truth of being and essence",
  "concept": "AbsoluteNecessityTruth",
  "phase": "appearance",
  "moments": [
    {
      "name": "beingEssenceIdentity",
      "definition": "Pure being and pure essence are one and the same",
      "type": "reflection"
    },
    {
      "name": "selfGrounding",
      "definition": "Absolute necessity has condition and ground only in itself",
      "type": "immanence",
      "relation": "unified",
      "relatedTo": "beingEssenceIdentity"
    }
  ],
  "invariants": [
    {
      "id": "act-c-6-inv-1",
      "constraint": "absolutely necessary is because it is",
      "predicate": "becauseItIs(absolutelyNecessary)"
    },
    {
      "id": "act-c-6-inv-2",
      "constraint": "possibility and actuality coincide in self-reference",
      "predicate": "equals(possibility, actuality)"
    }
  ],
  "forces": [
    {
      "id": "act-c-6-force-1",
      "description": "Absolute necessity externalizes as the transition to substance",
      "type": "reflection",
      "trigger": "absoluteNecessity.negativityBreaksForth = true",
      "effect": "substance.transitionPrepared = true",
      "targetState": "act-c-11"
    }
  ],
  "transitions": [
    {
      "id": "act-c-6-trans-1",
      "from": "act-c-6",
      "to": "act-c-11",
      "mechanism": "reflection",
      "description": "From absolute necessity truth to substance transition"
    }
  ],
  "nextStates": [
    "act-c-11"
  ],
  "previousStates": [
    "act-c-1"
  ],
  "provenance": {
    "topicMapId": "act-c-6-absolute-necessity-truth",
    "lineRange": {
      "start": 105,
      "end": 127
    },
    "section": "Absolute Necessity",
    "order": 6
  },
  "description": "Absolute necessity = truth (actuality/possibility, formal/real necessity return). Being in negation/essence refers itself to itself = being. Equally simple immediacy/pure being and simple immanent reflection/pure essence; two are one and same. Absolutely necessary only is because it is (no condition/ground). Equally pure essence (being = simple immanent reflection). As reflection: has ground/condition = itself. In-itself = immediacy, possibility = actuality. Because it is; rejoining of being with itself = essence; immediate simplicity = being.",
  "keyPoints": [
    "absolute necessity",
    "truth",
    "actuality",
    "possibility",
    "formal necessity",
    "real necessity",
    "return",
    "being in negation",
    "being in essence",
    "refers itself to itself",
    "being",
    "simple immediacy",
    "pure being",
    "simple immanent reflection",
    "pure essence",
    "two are one and same",
    "absolutely necessary",
    "only is because it is",
    "no condition",
    "no ground",
    "pure essence",
    "simple immanent reflection",
    "as reflection",
    "has ground",
    "has condition",
    "itself",
    "in-itself",
    "immediacy",
    "possibility",
    "actuality",
    "rejoining of being with itself",
    "essence",
    "immediate simplicity"
  ]
};
const stateActC11: DialecticState = {
  "id": "act-c-11",
  "title": "Substance as identity of being in negation",
  "concept": "TransitionToSubstance",
  "phase": "appearance",
  "moments": [
    {
      "name": "substanceIdentity",
      "definition": "Identity of being with itself in negation is substance",
      "type": "determination"
    },
    {
      "name": "selfExternalizingMovement",
      "definition": "Necessity reveals itself through its own externalization",
      "type": "process",
      "relation": "transitions",
      "relatedTo": "substanceIdentity"
    }
  ],
  "invariants": [
    {
      "id": "act-c-11-inv-1",
      "constraint": "unity in contingency refers to itself as substance",
      "predicate": "equals(unity(negation, contingency), substance)"
    },
    {
      "id": "act-c-11-inv-2",
      "constraint": "transition is the absolute own exposition",
      "predicate": "equals(transition, absoluteOwnExposition)"
    }
  ],
  "forces": [
    {
      "id": "act-c-11-force-1",
      "description": "Transition culminates in substantial relation",
      "type": "passover",
      "trigger": "substanceIdentity.established = true",
      "effect": "relationOfSubstantiality.emerges = true",
      "targetState": "sub-a-1"
    }
  ],
  "transitions": [
    {
      "id": "act-c-11-trans-1",
      "from": "act-c-11",
      "to": "sub-a-1",
      "mechanism": "passover",
      "description": "From absolute necessity to relation of substantiality"
    }
  ],
  "nextStates": [
    "sub-a-1"
  ],
  "previousStates": [
    "act-c-6"
  ],
  "provenance": {
    "topicMapId": "act-c-11-substance",
    "lineRange": {
      "start": 223,
      "end": 231
    },
    "section": "Absolute Necessity",
    "order": 11
  },
  "description": "Identity of being with itself in negation = substance. Unity in negation/contingency, relation to itself = substance. Blind transition of necessity = absolute's own exposition, movement in itself, in externalization reveals itself.",
  "keyPoints": [
    "identity of being with itself",
    "in negation",
    "substance",
    "unity in negation",
    "unity in contingency",
    "relation to itself",
    "blind transition of necessity",
    "absolute's own exposition",
    "movement in itself",
    "externalization",
    "reveals itself"
  ]
};

export const absoluteNecessityIR: DialecticIR = {
  id: "absolute-necessity-ir",
  title: "Absolute Necessity IR: Determinate Necessity, Truth, Substance Transition",
  section: "ESSENCE - C. ACTUALITY - C. Absolute Necessity",
  states: [
    stateActC1,
    stateActC6,
    stateActC11,
  ],
  metadata: {
  "sourceFile": "absolute-necessity.txt",
  "totalStates": 3,
  "cpuGpuMapping": {
    "act-c-1": "appearance",
    "act-c-6": "appearance",
    "act-c-11": "appearance"
  }
},
};

export const absoluteNecessityStates = {
  "act-c-1": stateActC1,
  "act-c-6": stateActC6,
  "act-c-11": stateActC11,
};
