import type { DialecticIR, DialecticState } from '@schema/dialectic';

// Generated by src/tools/generate-actuality-actuality-ir.ts
const stateActA1: DialecticState = {
  id: 'act-a-1',
  title: 'Formal actuality immediately contains possibility',
  concept: 'FormalActuality',
  phase: 'appearance',
  moments: [
    {
      name: 'formalActuality',
      definition:
        'Immediate actuality not yet total form but carrying possibility within',
      type: 'determination',
    },
    {
      name: 'innerOuterUnity',
      definition: 'In-itselfness and externality remain immediately topicmap',
      type: 'mediation',
      relation: 'contains',
      relatedTo: 'formalActuality',
    },
  ],
  invariants: [
    {
      id: 'act-a-1-inv-1',
      constraint: 'what is actual is possible',
      predicate: 'implies(actual(x), possible(x))',
    },
    {
      id: 'act-a-1-inv-2',
      constraint: 'actuality remains immediate and unreflected',
      predicate: 'and(equals(actuality, immediate), not(reflected(actuality)))',
    },
  ],
  forces: [
    {
      id: 'act-a-1-force-1',
      description: 'Immediate unity destabilizes into contingent duality',
      type: 'reflection',
      trigger: 'possibility.distinguishedFromActuality = true',
      effect: 'contingency.twoSidedness = explicit',
      targetState: 'act-a-8',
    },
  ],
  transitions: [
    {
      id: 'act-a-1-trans-1',
      from: 'act-a-1',
      to: 'act-a-8',
      mechanism: 'reflection',
      description: 'From formal actuality into contingency structure',
    },
  ],
  nextStates: ['act-a-8'],
  previousStates: ['act-b-9', 'mod-9'],
  provenance: {
    topicMapId: 'act-a-1-formal-actuality',
    lineRange: {
      start: 3,
      end: 13,
    },
    section: 'Contingency or Formal Actuality, Possibility, and Necessity',
    order: 1,
  },
  description:
    'Formal actuality = first actuality, immediate, unreflected, only form determination, not totality of form = being/concrete existence. But by essence = form-unity of in-itselfness/inwardness and externality, immediately contains possibility. What is actual is possible.',
  keyPoints: [
    'formal actuality',
    'first actuality',
    'immediate',
    'unreflected',
    'form determination',
    'totality of form',
    'being',
    'concrete existence',
    'form-unity',
    'in-itselfness',
    'inwardness',
    'externality',
    'possibility',
    'what is actual is possible',
  ],
};
const stateActA8: DialecticState = {
  id: 'act-a-8',
  title: 'Contingency as grounded and groundless unity',
  concept: 'Contingency',
  phase: 'appearance',
  moments: [
    {
      name: 'groundlessImmediacy',
      definition:
        'Contingent actuality appears as immediate without sufficient ground',
      type: 'externality',
    },
    {
      name: 'groundedPositedness',
      definition:
        'The same contingent is reflected into an other as its ground',
      type: 'reflection',
      relation: 'opposite',
      relatedTo: 'groundlessImmediacy',
    },
  ],
  invariants: [
    {
      id: 'act-a-8-inv-1',
      constraint: 'contingent has no ground because contingent',
      predicate: 'implies(contingent(x), noGround(x))',
    },
    {
      id: 'act-a-8-inv-2',
      constraint: 'contingent has ground because contingent',
      predicate: 'implies(contingent(x), hasGround(x))',
    },
  ],
  forces: [
    {
      id: 'act-a-8-force-1',
      description: 'Absolute restlessness turns contingency into necessity',
      type: 'contradiction',
      trigger: 'eachDetermination.turnsIntoOpposite = true',
      effect: 'identityInOther.emerges = necessity',
      targetState: 'act-a-9',
    },
  ],
  transitions: [
    {
      id: 'act-a-8-trans-1',
      from: 'act-a-8',
      to: 'act-a-9',
      mechanism: 'contradiction',
      description: 'From contingency duality to necessity through conversion',
    },
  ],
  nextStates: ['act-a-9'],
  previousStates: ['act-a-1'],
  provenance: {
    topicMapId: 'act-a-8-contingency-two-sides',
    lineRange: {
      start: 151,
      end: 226,
    },
    section: 'Contingency or Formal Actuality, Possibility, and Necessity',
    order: 8,
  },
  description:
    'Unity of possibility and actuality = contingency. Contingent = actual determined as only possible, actual whose opposite equally is = mere being/concrete existence, posited as positedness/possibility. Possibility = immanent reflection, in-itself as positedness, possible = actual with value of contingent actuality = contingent. Two sides: (1) possibility immediately in it/sublated = immediate actuality, no ground, groundless. (2) Actual as only possible/positedness, possible as positedness, not in and for themselves, have immanent reflection in other = have ground. Contingent has no ground because contingent; has ground because contingent.',
  keyPoints: [
    'unity of possibility and actuality',
    'contingency',
    'contingent',
    'actual determined as only possible',
    'opposite equally is',
    'mere being',
    'concrete existence',
    'positedness',
    'possibility',
    'immanent reflection',
    'in-itself as positedness',
    'contingent actuality',
    'two sides',
    'possibility immediately in it',
    'sublated',
    'immediate actuality',
    'no ground',
    'groundless',
    'only possible',
    'not in and for themselves',
    'immanent reflection in other',
    'have ground',
    'has no ground because contingent',
    'has ground because contingent',
  ],
};
const stateActA9: DialecticState = {
  id: 'act-a-9',
  title: 'Absolute restlessness yields necessity',
  concept: 'NecessityFromContingency',
  phase: 'appearance',
  moments: [
    {
      name: 'absoluteRestlessness',
      definition: 'Immediate conversion of inner and outer in becoming',
      type: 'process',
    },
    {
      name: 'identityOfOpposites',
      definition:
        'Each determination rejoins itself in its opposite as necessity',
      type: 'sublation',
      relation: 'mediates',
      relatedTo: 'absoluteRestlessness',
    },
  ],
  invariants: [
    {
      id: 'act-a-9-inv-1',
      constraint: 'becoming is contingency',
      predicate: 'equals(becoming, contingency)',
    },
    {
      id: 'act-a-9-inv-2',
      constraint: 'identity in opposition is necessity',
      predicate: 'equals(identity(opposites), necessity)',
    },
  ],
  forces: [
    {
      id: 'act-a-9-force-1',
      description: 'Necessity moves to determinate necessity',
      type: 'passover',
      trigger: 'necessity.identityEstablished = true',
      effect: 'determinateNecessity.emerges = true',
      targetState: 'act-c-1',
    },
  ],
  transitions: [
    {
      id: 'act-a-9-trans-1',
      from: 'act-a-9',
      to: 'act-c-1',
      mechanism: 'passover',
      description: 'From contingency necessity to absolute necessity',
    },
  ],
  nextStates: ['act-c-1'],
  previousStates: ['act-a-8'],
  provenance: {
    topicMapId: 'act-a-9-absolute-restlessness-necessity',
    lineRange: {
      start: 184,
      end: 216,
    },
    section: 'Contingency or Formal Actuality, Possibility, and Necessity',
    order: 9,
  },
  description:
    'Posited immediate conversion of inner/outer, immanently-reflected-being/being, each into other (moments of absolute form). Actuality in unity = concrete existence, groundless, only posited/possible; or reflected/separated = only possible. Possibility as in-itself = immediate, existent; or opposed = in-itself without actuality, only possible = concrete existence. Absolute restlessness of becoming = contingency. Each determination immediately turns into opposite, in opposite rejoins itself, identity of two (each in other) = necessity.',
  keyPoints: [
    'posited immediate conversion',
    'inner',
    'outer',
    'immanently-reflected-being',
    'being',
    'each into other',
    'moments of absolute form',
    'actuality in unity',
    'concrete existence',
    'groundless',
    'only posited',
    'only possible',
    'reflected',
    'separated',
    'possibility as in-itself',
    'immediate',
    'existent',
    'opposed',
    'in-itself without actuality',
    'absolute restlessness',
    'becoming',
    'contingency',
    'each determination turns into opposite',
    'rejoins itself',
    'identity of two',
    'each in other',
    'necessity',
  ],
};

export const contingencyIR: DialecticIR = {
  id: 'contingency-ir',
  title:
    'Contingency IR: Formal Actuality, Groundless/Grounded Unity, Necessity',
  section: 'ESSENCE - C. ACTUALITY - A. Contingency',
  states: [stateActA1, stateActA8, stateActA9],
  metadata: {
    sourceFile: 'contingency.txt',
    totalStates: 3,
    cpuGpuMapping: {
      'act-a-1': 'appearance',
      'act-a-8': 'appearance',
      'act-a-9': 'appearance',
    },
  },
};

export const contingencyStates = {
  'act-a-1': stateActA1,
  'act-a-8': stateActA8,
  'act-a-9': stateActA9,
};
