//! Skolemization + CNF conversion.
//!
//! Port of `nltk/sem/skolemize.py`. Removes existentials by replacing
//! their bound variables with Skolem functions of the enclosing
//! universal scope (or with Skolem constants when no universals are in
//! scope), and converts the result to **conjunctive normal form** by
//! pushing disjunction under conjunction.
//!
//! ## Algorithm
//!
//! Standard Skolemization:
//!
//! - `∀x. φ` → recurse with `x` added to the universal scope, then
//!   rename `x` to a fresh variable to keep variables apart.
//! - `∃x. φ` → recurse, then replace `x` with `F(u1,…,uk)` (the
//!   universal scope) or with a fresh Skolem constant if the scope is
//!   empty.
//! - `¬∀x. φ` ≡ `∃x. ¬φ` (and dually).
//! - Disjunction is pushed through conjunction by [`to_cnf`].
//! - Implication and biconditional are decomposed via the standard
//!   equivalences (`A → B ≡ ¬A ∨ B`; `A ↔ B ≡ (¬A ∨ B) ∧ (¬B ∨ A)`).
//!
//! Equality and atomic application expressions are left untouched.
//!
//! ## Skolem naming
//!
//! Skolem functions are named `F2`, `F3`, … — uppercase so they are
//! classified as **function variables** by NLTK convention
//! ([`Variable::is_function_name`]). Skolem constants (no universal
//! scope) are fresh **individual variables** generated by
//! [`unique_variable`], so they are still substitutable for equality
//! rewriting downstream (matching the choice already made in the
//! tableau prover).

use std::collections::BTreeSet;
use std::sync::atomic::{AtomicU64, Ordering};

use crate::ml::nlp::sem::logic::{unique_variable, Expression, Variable};

static SKOLEM_FN_COUNTER: AtomicU64 = AtomicU64::new(2);

/// Reset the skolem-function counter. Intended for deterministic tests.
pub fn reset_skolem_counter() {
    SKOLEM_FN_COUNTER.store(2, Ordering::SeqCst);
}

fn fresh_skolem_function(univ_scope: &BTreeSet<Variable>) -> Expression {
    let n = SKOLEM_FN_COUNTER.fetch_add(1, Ordering::SeqCst);
    let head = Expression::Variable(Variable::new(format!("F{}", n)));
    univ_scope.iter().fold(head, |acc, v| {
        Expression::app(acc, Expression::Variable(v.clone()))
    })
}

/// Skolemize `expression` and return its CNF form. Mirrors NLTK
/// `skolemize`.
pub fn skolemize(expression: &Expression) -> Expression {
    skolemize_inner(expression, &BTreeSet::new(), &BTreeSet::new())
}

fn skolemize_inner(
    expr: &Expression,
    univ_scope: &BTreeSet<Variable>,
    used_variables: &BTreeSet<Variable>,
) -> Expression {
    match expr {
        Expression::All(v, body) => {
            let mut next_scope = univ_scope.clone();
            next_scope.insert(v.clone());
            let mut next_used = used_variables.clone();
            next_used.insert(v.clone());
            let term = skolemize_inner(body, &next_scope, &next_used);
            let fresh = unique_variable(None, &next_used);
            term.replace(v, &Expression::Variable(fresh))
        }
        Expression::And(a, b) => Expression::and(
            skolemize_inner(a, univ_scope, used_variables),
            skolemize_inner(b, univ_scope, used_variables),
        ),
        Expression::Or(a, b) => to_cnf(
            &skolemize_inner(a, univ_scope, used_variables),
            &skolemize_inner(b, univ_scope, used_variables),
        ),
        Expression::Imp(a, b) => to_cnf(
            &skolemize_inner(&Expression::not((**a).clone()), univ_scope, used_variables),
            &skolemize_inner(b, univ_scope, used_variables),
        ),
        Expression::Iff(a, b) => Expression::and(
            to_cnf(
                &skolemize_inner(&Expression::not((**a).clone()), univ_scope, used_variables),
                &skolemize_inner(b, univ_scope, used_variables),
            ),
            to_cnf(
                &skolemize_inner(a, univ_scope, used_variables),
                &skolemize_inner(&Expression::not((**b).clone()), univ_scope, used_variables),
            ),
        ),
        Expression::Equality(_, _) => expr.clone(),
        Expression::Negated(inner) => skolemize_negated(inner, univ_scope, used_variables, expr),
        Expression::Exists(v, body) | Expression::Iota(v, body) => {
            let mut next_used = used_variables.clone();
            next_used.insert(v.clone());
            let term = skolemize_inner(body, univ_scope, &next_used);
            if !univ_scope.is_empty() {
                term.replace(v, &fresh_skolem_function(univ_scope))
            } else {
                let fresh = unique_variable(None, &next_used);
                term.replace(v, &Expression::Variable(fresh))
            }
        }
        Expression::Application(_, _)
        | Expression::Variable(_)
        | Expression::Constant(_)
        | Expression::Lambda(_, _) => expr.clone(),
    }
}

fn skolemize_negated(
    negated: &Expression,
    univ_scope: &BTreeSet<Variable>,
    used_variables: &BTreeSet<Variable>,
    original: &Expression,
) -> Expression {
    match negated {
        Expression::All(v, body) => {
            let mut next_used = used_variables.clone();
            next_used.insert(v.clone());
            let term = skolemize_inner(&Expression::not((**body).clone()), univ_scope, &next_used);
            if !univ_scope.is_empty() {
                term.replace(v, &fresh_skolem_function(univ_scope))
            } else {
                let fresh = unique_variable(None, &next_used);
                term.replace(v, &Expression::Variable(fresh))
            }
        }
        Expression::And(a, b) => to_cnf(
            &skolemize_inner(&Expression::not((**a).clone()), univ_scope, used_variables),
            &skolemize_inner(&Expression::not((**b).clone()), univ_scope, used_variables),
        ),
        Expression::Or(a, b) => Expression::and(
            skolemize_inner(&Expression::not((**a).clone()), univ_scope, used_variables),
            skolemize_inner(&Expression::not((**b).clone()), univ_scope, used_variables),
        ),
        Expression::Imp(a, b) => Expression::and(
            skolemize_inner(a, univ_scope, used_variables),
            skolemize_inner(&Expression::not((**b).clone()), univ_scope, used_variables),
        ),
        Expression::Iff(a, b) => Expression::and(
            to_cnf(
                &skolemize_inner(&Expression::not((**a).clone()), univ_scope, used_variables),
                &skolemize_inner(&Expression::not((**b).clone()), univ_scope, used_variables),
            ),
            to_cnf(
                &skolemize_inner(a, univ_scope, used_variables),
                &skolemize_inner(b, univ_scope, used_variables),
            ),
        ),
        Expression::Equality(_, _) => original.clone(),
        Expression::Negated(inner) => skolemize_inner(inner, univ_scope, used_variables),
        Expression::Exists(v, body) => {
            let mut next_scope = univ_scope.clone();
            next_scope.insert(v.clone());
            let mut next_used = used_variables.clone();
            next_used.insert(v.clone());
            let term = skolemize_inner(&Expression::not((**body).clone()), &next_scope, &next_used);
            let fresh = unique_variable(None, &next_used);
            term.replace(v, &Expression::Variable(fresh))
        }
        Expression::Application(_, _) | Expression::Variable(_) | Expression::Constant(_) => {
            original.clone()
        }
        // Iota / Lambda / nested negations not normally produced by
        // FOL surface; fall through to identity.
        _ => original.clone(),
    }
}

/// Distribute disjunction over conjunction. Mirrors NLTK
/// `to_cnf(first, second)`.
pub fn to_cnf(first: &Expression, second: &Expression) -> Expression {
    if let Expression::And(a, b) = first {
        Expression::and(to_cnf(a, second), to_cnf(b, second))
    } else if let Expression::And(a, b) = second {
        Expression::and(to_cnf(first, a), to_cnf(first, b))
    } else {
        Expression::or(first.clone(), second.clone())
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ml::nlp::sem::logic::parse;

    /// Count the number of literals in a CNF tree (helpful for shape
    /// assertions).
    fn count_clauses(e: &Expression) -> usize {
        match e {
            Expression::And(a, b) => count_clauses(a) + count_clauses(b),
            _ => 1,
        }
    }

    #[test]
    fn atom_is_unchanged() {
        let e = parse("man(adam)").unwrap();
        assert_eq!(skolemize(&e), e);
    }

    #[test]
    fn negated_atom_is_unchanged() {
        let e = parse("-man(adam)").unwrap();
        assert_eq!(skolemize(&e), e);
    }

    #[test]
    fn double_negation_collapses() {
        let e = parse("--man(adam)").unwrap();
        assert_eq!(skolemize(&e), parse("man(adam)").unwrap());
    }

    #[test]
    fn implication_becomes_disjunction() {
        // (man(adam) -> mortal(adam)) ⟹ (-man(adam) | mortal(adam))
        let e = parse("(man(adam) -> mortal(adam))").unwrap();
        let s = skolemize(&e);
        assert_eq!(s, parse("(-man(adam) | mortal(adam))").unwrap());
    }

    #[test]
    fn or_distributes_over_and() {
        // ((P & Q) | R) ⟹ ((P | R) & (Q | R))
        let e = parse("((man(a) & boy(a)) | dog(a))").unwrap();
        let s = skolemize(&e);
        assert_eq!(count_clauses(&s), 2);
    }

    #[test]
    fn existential_no_universal_uses_fresh_constant() {
        // some x. man(x)  ⟹  man(z2) (or some fresh z-var)
        let e = parse("some x. man(x)").unwrap();
        let s = skolemize(&e);
        // After skolemization the bound `x` is replaced; the result is
        // still an Application headed by `man`.
        match s {
            Expression::Application(f, arg) => {
                assert_eq!(*f, parse("man").unwrap());
                assert!(matches!(*arg, Expression::Variable(_)));
            }
            other => panic!("expected man(<sk>), got {:?}", other),
        }
    }

    #[test]
    fn existential_under_universal_uses_skolem_function() {
        reset_skolem_counter();
        // all x. some y. love(x, y)  ⟹  all x. love(x, F(x))
        // After universal removal: love(<fresh>, F(<fresh>))
        let e = parse("all x. some y. love(x, y)").unwrap();
        let s = skolemize(&e);
        // The result should be an application of love to two terms,
        // the second of which is itself an application (the skolem
        // function applied to the universal variable).
        match s {
            Expression::Application(love_x, sk_y) => match (*love_x, *sk_y) {
                (Expression::Application(_, _), Expression::Application(_, _)) => {}
                other => panic!("expected love(x, F(x)) shape, got {:?}", other),
            },
            other => panic!("expected love(...) application, got {:?}", other),
        }
    }

    #[test]
    fn negated_universal_becomes_existential() {
        // -all x. man(x)  ⟹  -man(<sk>)
        let e = parse("-all x. man(x)").unwrap();
        let s = skolemize(&e);
        match s {
            Expression::Negated(inner) => match *inner {
                Expression::Application(f, _) => {
                    assert_eq!(*f, parse("man").unwrap());
                }
                other => panic!("expected -man(<sk>), got {:?}", other),
            },
            other => panic!("expected negation, got {:?}", other),
        }
    }

    #[test]
    fn equality_is_unchanged() {
        let e = parse("(adam = adam)").unwrap();
        assert_eq!(skolemize(&e), e);
    }

    #[test]
    fn negated_equality_is_unchanged() {
        let e = parse("-(adam = betty)").unwrap();
        assert_eq!(skolemize(&e), e);
    }

    #[test]
    fn conjunction_recurses() {
        // (man(a) & some x. dog(x))  ⟹  (man(a) & dog(<sk>))
        let e = parse("(man(a) & some x. dog(x))").unwrap();
        let s = skolemize(&e);
        match s {
            Expression::And(a, b) => {
                assert_eq!(*a, parse("man(a)").unwrap());
                assert!(matches!(*b, Expression::Application(_, _)));
            }
            other => panic!("expected conjunction, got {:?}", other),
        }
    }
}
