/**
 * TopicMap for number.txt - Number
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - number-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const NUMBER_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/quantity/quantum/sources/number.txt',
  'Hegel\'s Science of Logic - Quantum',
  'Number',
  [
    createTopicMapEntry(
      'number-quantum-as-number',
      'Quantum as number: complete positedness',
      [4, 52],
      'Quantum as number: Complete positedness with limit as plurality distinguished from unity. Number is discrete magnitude with continuity in unity. The one is principle: (a) self-referring, (b) enclosing, (c) other-excluding limit.',
      [
        'quantity',
        'quantum',
        'limit',
        'continuous',
        'discrete',
        'magnitude',
        'distinction',
        'species',
        'significance',
        'sublated',
        'being-for-itself',
        'quantity',
        'indifferent',
        'limit',
        'limit',
        'quantum',
        'indifferent',
        'quantity',
        'quantity',
        'contains',
        'absolute determinateness',
        'one',
        'moment',
        'posited',
        'continuity',
        'unity',
        'quantity',
        'limit',
        'limit',
        'remains',
        'one',
        'quantity',
        'become',
        'one',
        'therefore',
        'principle',
        'quantum',
        'one',
        'quantity',
        'reason',
        'first',
        'continuous',
        'unity',
        'second',
        'discrete',
        'plurality',
        'implicit',
        'continuous magnitude',
        'posited',
        'discrete magnitude',
        'ones',
        'equality',
        'continuity',
        'unity',
        'third',
        'one',
        'negation',
        'many ones',
        'simple limit',
        'excluding',
        'otherness',
        'determination',
        'opposition',
        'quanta',
        'one',
        'self-referring',
        'enclosing',
        'other-excluding',
        'limit',
        'completely',
        'posited',
        'determinations',
        'quantum',
        'number',
        'complete',
        'positedness',
        'existence',
        'limit',
        'plurality',
        'distinguished',
        'unity',
        'number',
        'appears',
        'discrete magnitude',
        'unity',
        'continuity',
        'quantum',
        'complete determinateness',
        'limit',
        'determinate plurality',
        'one',
        'absolutely determined',
        'principle',
        'continuity',
        'one',
        'implicitly',
        'present',
        'sublated moment',
        'posited',
        'unity',
        'form',
        'indeterminateness',
      ],
      { section: 'A. NUMBER', order: 1 }
    ),

    createTopicMapEntry(
      'number-amount-and-unit',
      'Amount and unit: the two moments of number',
      [53, 65],
      'Amount and unit: Number\'s limit is manifold, containing many ones as determinate aggregate. Amount is the how many times; unit is the continuity of the amount. These are the two moments of number.',
      [
        'quantum',
        'limited',
        'general',
        'limit',
        'abstract',
        'simple',
        'determinateness',
        'number',
        'limit',
        'posited',
        'manifold',
        'contains',
        'many ones',
        'existence',
        'contains',
        'indeterminate',
        'manner',
        'determinateness',
        'limit',
        'falls',
        'limit',
        'excludes',
        'existence',
        'ones',
        'pluralities',
        'encloses',
        'determinate aggregate',
        'amount',
        'how many times',
        'discreteness',
        'number',
        'other',
        'unit',
        'continuity',
        'amount',
        'amount',
        'unit',
        'constitute',
        'moments',
        'number',
      ],
      { section: 'A. NUMBER', order: 2 }
    ),

    createTopicMapEntry(
      'number-amount-in-limit',
      'Amount in the limit: many ones present',
      [67, 109],
      'Amount in limit: Many ones are present (not sublated), posited with excluding limit. All ones are equal; each is the hundredth. The many constitute the delimitation itself - the number is not plurality over against limiting one, but is the delimitation.',
      [
        'amount',
        'examine',
        'closely',
        'many ones',
        'consists',
        'limit',
        'rightly',
        'amount',
        'consists',
        'many',
        'ones',
        'sublated',
        'present',
        'posited',
        'excluding',
        'limit',
        'indifferent',
        'limit',
        'indifferent',
        'sphere',
        'existence',
        'limit',
        'placed',
        'relation',
        'existence',
        'left',
        'side',
        'limit',
        'standing',
        'affirmative',
        'limit',
        'negation',
        'outside',
        'border',
        'existence',
        'similarly',
        'many ones',
        'truncated',
        'exclusion',
        'remaining',
        'appears',
        'determination',
        'falls',
        'outside',
        'enclosed',
        'found',
        'sphere',
        'existence',
        'limit',
        'pervades',
        'existence',
        'extends',
        'existence',
        'something',
        'limited',
        'determination',
        'finite',
        'quantitative sphere',
        'number',
        'hundred',
        'represented',
        'hundredth',
        'unit',
        'brings',
        'many',
        'limit',
        'hundred',
        'respect',
        'correct',
        'respect',
        'ones',
        'hundred',
        'precedence',
        'equal',
        'hundredth',
        'belong',
        'limit',
        'number',
        'hundred',
        'number',
        'dispense',
        'determinateness',
        'hundredth',
        'rest',
        'constitute',
        'determinate existence',
        'different',
        'inside',
        'outside',
        'limit',
        'consequently',
        'number',
        'plurality',
        'limiting',
        'one',
        'encloses',
        'constitutes',
        'delimitation',
        'determinate quantum',
        'many',
        'constitute',
        'number',
        'one',
        'two',
        'ten',
        'hundred',
      ],
      { section: 'A. NUMBER', order: 3 }
    ),

    createTopicMapEntry(
      'number-indifference-and-exteriority',
      'Number\'s indifference and exteriority',
      [111, 136],
      'Number\'s indifference/exteriority: Distinguishing remains quantitative (external reflection). Number is absolutely determined but has simple immediacy; reference to other is external. Yet amount is plurality of ones - absolute exteriority is in the one itself. This intrinsic contradiction is the quality of quantum.',
      [
        'limiting',
        'one',
        'discriminating',
        'determinateness',
        'distinguishing',
        'number',
        'numbers',
        'distinguishing',
        'qualitative',
        'determinateness',
        'remains',
        'quantitative',
        'falling',
        'compass',
        'comparing',
        'external reflection',
        'one',
        'number',
        'remains',
        'turned back',
        'itself',
        'indifferent',
        'others',
        'indifference',
        'number',
        'others',
        'essential',
        'determination',
        'constitutes',
        'being-determined-in-itself',
        'time',
        'exteriority',
        'number',
        'numerical',
        'one',
        'absolutely determined',
        'time',
        'form',
        'simple',
        'immediacy',
        'connecting',
        'reference',
        'other',
        'remains',
        'completely',
        'external',
        'further',
        'numerical',
        'one',
        'possesses',
        'determinateness',
        'consists',
        'reference',
        'other',
        'moment',
        'distinction',
        'unit',
        'amount',
        'amount',
        'plurality',
        'ones',
        'absolute',
        'exteriority',
        'one',
        'itself',
        'intrinsic',
        'contradiction',
        'number',
        'quantum',
        'general',
        'quality',
        'quantum',
        'contradiction',
        'develop',
        'determinations',
        'quality',
      ],
      { section: 'A. NUMBER', order: 4 }
    ),
  ],
  {
    sectionDescription: 'Number - Quantum as number (complete positedness, one as principle: self-referring, enclosing, other-excluding). Amount and unit (two moments of number). Amount in limit (many ones present, all equal, constitute delimitation). Number\'s indifference/exteriority (intrinsic contradiction, quality of quantum).',
  }
);

