/**
 * TopicMap for quantum.txt - Extensive and Intensive Quantum
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - quantum-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const QUANTUM_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/quantity/quantum/sources/quantum.txt',
  'Hegel\'s Science of Logic - Quantum',
  'Extensive and Intensive Quantum',
  [
    createTopicMapEntry(
      'quantum-extensive-magnitude',
      'Extensive magnitude: limit as plurality',
      [6, 54],
      'Extensive magnitude: Quantum has determinateness as limit in amount (plurality). Extensive/intensive are determinacies of quantitative limit itself. Extensive quantum is amount essentially (amount of one unit), distinguished from number only by explicit plurality.',
      [
        'quantum',
        'determinateness',
        'limit',
        'amount',
        'discrete',
        'plurality',
        'being',
        'different',
        'limit',
        'outside',
        'quantum',
        'limit',
        'plurality',
        'extensive magnitude',
        'extensive magnitude',
        'distinguished',
        'continuous magnitude',
        'direct opposite',
        'discrete',
        'intensive magnitude',
        'extensive',
        'intensive',
        'magnitudes',
        'determinacies',
        'quantitative limit',
        'quantum',
        'identical',
        'limit',
        'continuous',
        'discrete',
        'magnitudes',
        'determinations',
        'magnitude',
        'quantity',
        'quantum',
        'abstraction',
        'limit',
        'extensive magnitude',
        'moment',
        'continuity',
        'limit',
        'many',
        'continuous',
        'limit',
        'negation',
        'appears',
        'equality',
        'many',
        'limiting',
        'unity',
        'continuous magnitude',
        'quantity',
        'continues',
        'regard',
        'limit',
        'represented',
        'limit',
        'limitation',
        'general',
        'discreteness',
        'posited',
        'determined',
        'continuous magnitude',
        'quantum',
        'determined',
        'magnitude',
        'lacks',
        'one',
        'determinateness-for-itself',
        'number',
        'discrete magnitude',
        'immediately',
        'differentiated',
        'many',
        'limit',
        'many',
        'aggregate',
        'indeterminately',
        'limited',
        'quantum',
        'determinate',
        'many',
        'concentrated',
        'one',
        'posited',
        'identical',
        'limit',
        'continuous',
        'discrete',
        'magnitude',
        'quantum',
        'general',
        'posited',
        'sides',
        'quantum',
        'determined',
        'number',
        'extensive quantum',
        'simple',
        'determinateness',
        'amount',
        'essentially',
        'amount',
        'one',
        'same',
        'unit',
        'extensive quantum',
        'distinguished',
        'number',
        'determinateness',
        'explicitly',
        'posited',
        'plurality',
      ],
      { section: 'a. Their difference', order: 1 }
    ),

    createTopicMapEntry(
      'quantum-number-determinateness',
      'Number\'s determinateness: self-referring limit',
      [56, 86],
      'Number\'s determinateness: Limit is determined for itself, indifferent and self-referring. In number, limit is enclosed within one - externality/reference to other is inside it. Many collapses into continuity, becomes simple unity. Amount is moment; ones are sublated in number\'s self-reference.',
      [
        'determinateness',
        'number',
        'how much',
        'something',
        'require',
        'distinguished',
        'how much',
        'something else',
        'determinateness',
        'thing',
        'belonged',
        'how much',
        'other',
        'determinateness',
        'magnitude',
        'limit',
        'determined',
        'itself',
        'indifferent',
        'self-referring',
        'number',
        'limit',
        'posited',
        'enclosed',
        'one',
        'existing',
        'itself',
        'externality',
        'reference',
        'other',
        'inside',
        'many',
        'general',
        'many',
        'limit',
        'internally',
        'unequal',
        'continuous',
        'many',
        'many',
        'many',
        'existents',
        'outside',
        'discrete',
        'constitute',
        'determinateness',
        'many',
        'collapses',
        'continuity',
        'simple',
        'unity',
        'amount',
        'moment',
        'number',
        'aggregate',
        'numerical',
        'ones',
        'constitute',
        'determinateness',
        'number',
        'contrary',
        'ones',
        'indifferent',
        'self-external',
        'sublated',
        'number',
        'being',
        'turned back',
        'itself',
        'externality',
        'constituted',
        'ones',
        'plurality',
        'vanishes',
        'one',
        'self-reference',
        'number',
      ],
      { section: 'a. Their difference', order: 2 }
    ),

    createTopicMapEntry(
      'quantum-intensive-magnitude-degree',
      'Intensive magnitude: degree as simple determinateness',
      [88, 117],
      'Intensive magnitude (degree): Limit passes over into simple determinateness. Degree is quantum but not aggregate - plurality gathered into simple determination, existence returned into being-for-itself. Number expresses determinateness but as sublated amount, simple determinateness (onefold degree).',
      [
        'limit',
        'quantum',
        'extensive',
        'existent',
        'determinateness',
        'self-external',
        'number',
        'passes over',
        'simple',
        'determinateness',
        'simple',
        'determination',
        'limit',
        'quantum',
        'intensive magnitude',
        'limit',
        'determinateness',
        'identical',
        'quantum',
        'posited',
        'simple',
        'degree',
        'degree',
        'determinate',
        'magnitude',
        'quantum',
        'aggregate',
        'several',
        'within',
        'plurality',
        'plurality',
        'severality',
        'gathered',
        'together',
        'simple',
        'determination',
        'existence',
        'returned',
        'being-for-itself',
        'determinateness',
        'expressed',
        'number',
        'being',
        'quantum',
        'completely',
        'determined',
        'number',
        'amount',
        'how many times',
        'onefold',
        'degree',
        'speak',
        'degrees',
        'quantum',
        'degrees',
        'tenth',
        'twentieth',
        'degree',
        'amount',
        'sum',
        'degrees',
        'extensive quantum',
        'degree',
        'tenth',
        'twentieth',
        'contains',
        'determinateness',
        'number',
        'several',
        'ones',
        'number',
        'sublated',
        'amount',
        'simple',
        'determinateness',
      ],
      { section: 'a. Their difference', order: 3 }
    ),

    createTopicMapEntry(
      'quantum-degree-externality-quality',
      'Degree\'s externality and quality',
      [119, 170],
      'Degree\'s externality/quality: Self-reference is externality to itself. Degree has determinateness outside it (plurality external). Amount sublated in extensive is posited outside intensive. Degree is unitary determinateness among plurality of intensities, each in essential connection - scale is continuous progress. In externality it possesses its quality.',
      [
        'number',
        'quantum',
        'posited',
        'complete',
        'determinateness',
        'intensive quantum',
        'being-for-itself',
        'number',
        'posited',
        'concept',
        'implicitly',
        'itself',
        'form',
        'self-reference',
        'degree',
        'time',
        'externality',
        'degree',
        'itself',
        'extensive quantum',
        'number',
        'numerical',
        'plurality',
        'externality',
        'inside',
        'externality',
        'plurality',
        'general',
        'collapses',
        'state',
        'undifferentiatedness',
        'sublated',
        'numerical',
        'one',
        'self-reference',
        'number',
        'quantum',
        'determinateness',
        'number',
        'contains',
        'determinateness',
        'posited',
        'degree',
        'internally',
        'simple',
        'external',
        'otherness',
        'outside',
        'refers',
        'determinateness',
        'plurality',
        'external',
        'constitutes',
        'determinateness',
        'simple',
        'limit',
        'degree',
        'extensive quantum',
        'amount',
        'supposed',
        'found',
        'within',
        'number',
        'sublated',
        'sublated',
        'amount',
        'posited',
        'outside',
        'number',
        'posited',
        'one',
        'self-reference',
        'reflected',
        'itself',
        'excludes',
        'indifference',
        'externality',
        'amount',
        'self-reference',
        'reference',
        'external',
        'quantum',
        'reality',
        'adequate',
        'concept',
        'indifference',
        'determinateness',
        'constitutes',
        'quality',
        'determinateness',
        'determinateness',
        'external',
        'degree',
        'unitary',
        'quantitative',
        'determinateness',
        'plurality',
        'intensities',
        'diverse',
        'simple',
        'reference',
        'itself',
        'time',
        'essential',
        'connection',
        'determinateness',
        'continuity',
        'reference',
        'connecting',
        'degree',
        'other',
        'ascent',
        'descent',
        'scale',
        'degrees',
        'continuous',
        'progress',
        'flow',
        'uninterrupted',
        'indivisible',
        'alteration',
        'more or less',
        'differentiated',
        'separate',
        'determinateness',
        'self-referring',
        'quantitative',
        'determination',
        'degree',
        'indifferent',
        'refers',
        'externality',
        'intermediary',
        'externality',
        'reference',
        'itself',
        'indifferent',
        'reference',
        'externality',
        'externality',
        'possesses',
        'quality',
      ],
      { section: 'a. Their difference', order: 4 }
    ),

    createTopicMapEntry(
      'quantum-degree-contains-amount',
      'Degree contains amount: identity of extensive and intensive',
      [174, 197],
      'Degree contains amount: Degree is not indeterminate one. Several degrees refer to each other as outside each other. Determinateness lies in connection with them - degree contains amount. Twentieth degree contains twenty as continuity (determinate plurality) through intermediate of amount.',
      [
        'degree',
        'inherently',
        'external',
        'itself',
        'indeterminate',
        'one',
        'principle',
        'number',
        'amount',
        'negatively',
        'sense',
        'amount',
        'intensive magnitude',
        'simple',
        'one',
        'more or less',
        'degrees',
        'determined',
        'unitary',
        'one',
        'more or less',
        'referring',
        'outside',
        'identity',
        'one',
        'more or less',
        'several',
        'more or less',
        'outside',
        'unitary',
        'degree',
        'determinateness',
        'latter',
        'connection',
        'degree',
        'contains',
        'amount',
        'twenty',
        'contains',
        'extensive magnitude',
        'twenty',
        'ones',
        'discrete',
        'specific',
        'degree',
        'contains',
        'continuity',
        'continuity',
        'determinate',
        'plurality',
        'twentieth',
        'degree',
        'twentieth',
        'degree',
        'intermediate',
        'amount',
        'outside',
      ],
      { section: 'b. Identity of extensive and intensive magnitude', order: 5 }
    ),

    createTopicMapEntry(
      'quantum-identity-two-sides',
      'Identity: extensive and intensive are same determinateness',
      [199, 254],
      'Identity: Extensive/intensive are same determinateness. Distinguished only by amount within vs without. Extensive passes into intensive (many collapses into oneness). But intensive has determinateness in amount - essentially extensive. With this identity, qualitative something appears - unity through negation of distinct terms.',
      [
        'determinateness',
        'intensive magnitude',
        'considered',
        'sides',
        'determined',
        'intensive quanta',
        'continuous',
        'otherness',
        'determinateness',
        'consists',
        'connection',
        'determinateness',
        'simple',
        'determinateness',
        'determined',
        'degrees',
        'excludes',
        'determinateness',
        'exclusion',
        'determined',
        'within',
        'amount',
        'amount',
        'excluded',
        'amount',
        'degrees',
        'twentieth',
        'degree',
        'contains',
        'twenty',
        'within',
        'determined',
        'distinguished',
        'nineteenth',
        'twenty-first',
        'determinateness',
        'amount',
        'amount',
        'determinateness',
        'time',
        'essentially',
        'amount',
        'degree',
        'extensive quantum',
        'extensive',
        'intensive',
        'magnitude',
        'determinateness',
        'quantum',
        'distinguished',
        'amount',
        'within',
        'same',
        'without',
        'extensive magnitude',
        'passes over',
        'intensive magnitude',
        'many',
        'collapses',
        'oneness',
        'steps',
        'outside',
        'simple',
        'one',
        'determinateness',
        'amount',
        'amount',
        'indifferent',
        'determined',
        'intensities',
        'externality',
        'amount',
        'intensive magnitude',
        'essentially',
        'extensive magnitude',
        'identity',
        'qualitative',
        'something',
        'scene',
        'identity',
        'unity',
        'refers',
        'negation',
        'distinct',
        'terms',
        'make up',
        'determinateness',
        'existent',
        'magnitude',
        'something',
        'quantum',
        'qualitative',
        'existence',
        'posited',
        'indifferent',
        'speak',
        'quantum',
        'number',
        'mention',
        'something',
        'substrate',
        'something',
        'self-mediated',
        'virtue',
        'negation',
        'determinations',
        'confronts',
        'existing',
        'quantum',
        'confronts',
        'extensive',
        'intensive',
        'quantum',
        'determinateness',
        'quantum',
        'posited',
        'distinct',
        'moments',
        'unity',
        'amount',
        'itself',
        'determinateness',
        'positing',
        'differences',
        'extensive',
        'intensive',
        'quantum',
        'return',
        'unity',
        'negative',
        'something',
        'posited',
        'indifferent',
      ],
      { section: 'b. Identity of extensive and intensive magnitude', order: 6 }
    ),

    createTopicMapEntry(
      'quantum-alteration-necessity',
      'Alteration of quantum: quantum must alter',
      [256, 281],
      'Alteration: Difference extensive/intensive is indifferent to quantum as quantum. Quantum is determinateness posited as sublated - indifferent limit that is negation of itself. Quantum is in absolute continuity with externality/otherness. It must alter - has being only in continuity with other. Limit becomes, not just exists.',
      [
        'alteration',
        'quantum',
        'difference',
        'extensive',
        'intensive',
        'quantum',
        'indifferent',
        'determinateness',
        'quantum',
        'quantum',
        'general',
        'determinateness',
        'posited',
        'sublated',
        'indifferent',
        'limit',
        'determinateness',
        'negation',
        'itself',
        'extensive quantum',
        'difference',
        'developed',
        'intensive magnitude',
        'existence',
        'externality',
        'quantum',
        'difference',
        'posited',
        'contradiction',
        'simple',
        'self-referring',
        'determinateness',
        'negation',
        'determinateness',
        'quantum',
        'quantum',
        'quality',
        'absolute',
        'continuity',
        'externality',
        'otherness',
        'consequently',
        'determinateness',
        'magnitude',
        'transcended',
        'altered',
        'alter',
        'posited',
        'determination',
        'magnitude',
        'continues',
        'otherness',
        'being',
        'continuity',
        'other',
        'limit',
        'exists',
        'becomes',
      ],
      { section: 'c. Alteration of quantum', order: 7 }
    ),

    createTopicMapEntry(
      'quantum-sends-beyond-infinity',
      'Quantum sends itself beyond itself: to infinity',
      [283, 304],
      'Quantum sends beyond: Quantum is infinite (self-referring negation), repels itself from itself. Repulsion of determinateness from itself (not like itself but otherness). Quantum sends itself beyond itself (increases/decreases). Other it becomes is quantum impelling itself beyond - limit sublates and sends to further limit, to infinity.',
      [
        'one',
        'infinite',
        'self-referring',
        'negation',
        'repulsion',
        'itself',
        'quantum',
        'equally',
        'infinite',
        'posited',
        'self-referring',
        'negation',
        'repels',
        'determinate',
        'one',
        'passed over',
        'existence',
        'limit',
        'repulsion',
        'determinateness',
        'generation',
        'like',
        'repulsion',
        'one',
        'otherness',
        'quantum',
        'posited',
        'sending',
        'beyond',
        'consists',
        'increases',
        'decreases',
        'within',
        'externality',
        'determinateness',
        'quantum',
        'sends',
        'beyond',
        'other',
        'becomes',
        'quantum',
        'static',
        'limit',
        'impels',
        'beyond',
        'limit',
        'arises',
        'beyond',
        'sublates',
        'sends',
        'further',
        'limit',
        'infinity',
      ],
      { section: 'c. Alteration of quantum', order: 8 }
    ),
  ],
  {
    sectionDescription: 'Extensive and Intensive Quantum - a. Their difference: Extensive magnitude (limit as plurality), Number\'s determinateness (self-referring limit), Intensive magnitude (degree as simple determinateness), Degree\'s externality and quality. b. Identity: Degree contains amount, Extensive and intensive are same determinateness. c. Alteration: Quantum must alter, Quantum sends itself beyond itself to infinity.',
  }
);

