/**
 * TopicMap for measures.txt - The Relation of Independent Measures
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - measures-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const MEASURES_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/measure/real-measure/sources/measures.txt',
  'Hegel\'s Science of Logic - Measure',
  'The Relation of Independent Measures',
  [
    createTopicMapEntry(
      'rm-a-intro-self-subsistent-measures',
      'Introduction — self-subsistent measures',
      [3, 11],
      'Measures no longer immediate but self-subsistent, becoming specified relations within themselves, being-for-itself, something physical and material.',
      [
        'measures',
        'no longer mean',
        'merely immediate measures',
        'self-subsistent',
        'become within themselves',
        'relations',
        'specified',
        'being-for-itself',
        'something',
        'things',
        'physical',
        'at first material',
      ],
      { section: 'The Relation of Independent Measures', order: 1 }
    ),

    createTopicMapEntry(
      'rm-a-a-whole-immediate',
      '(a) Whole immediate — external combination',
      [13, 20],
      'Whole as relation of measures at first immediate, two sides as independent measures having subsistence in things external to each other, posited in combination externally.',
      [
        'whole',
        'relation of such measures',
        'at first itself immediate',
        'two sides',
        'independent measures',
        'subsistence',
        'things external to each other',
        'posited in combination externally',
      ],
      { section: 'The Relation of Independent Measures', order: 2 }
    ),

    createTopicMapEntry(
      'rm-a-b-self-subsistent-materialities',
      '(b) Self-subsistent materialities — affinity',
      [22, 27],
      'Self-subsistent materialities are what they qualitatively are only in virtue of quantitative determination as measures, posited as non-indifferent (affinity), members of series of quantitative relations.',
      [
        'self-subsistent materialities',
        'qualitatively',
        'quantitative determination',
        'measures',
        'quantitative connection',
        'non-indifferent',
        'affinity',
        'members',
        'series',
        'quantitative relations',
      ],
      { section: 'The Relation of Independent Measures', order: 3 }
    ),

    createTopicMapEntry(
      'rm-a-c-elective-affinity-intro',
      '(c) Elective affinity — exclusive being-for-itself',
      [29, 32],
      'Indifferent multifarious relating concludes by cutting itself off as exclusive being-for-itself: elective affinity.',
      [
        'indifferent multifarious relating',
        'concludes',
        'cutting itself off',
        'exclusive being-for-itself',
        'elective affinity',
      ],
      { section: 'The Relation of Independent Measures', order: 4 }
    ),

    createTopicMapEntry(
      'rm-a-a-1-measure-relation-direct-ratio',
      'Measure relation — weight to volume, direct ratio',
      [36, 61],
      'Measure relation: something determined by quanta with qualities (in-itselfness/material vs externality/space), quantitatively determined, ratio of weight to volume (specifically determined gravity). Volume = unit, intensive aspect = amount. Ratio of powers disappeared, immediacy returned, determinateness = quantum in ordinary exponent of direct ratio.',
      [
        'measure relation',
        'something',
        'determined by quanta',
        'qualities accrue',
        'connection of such qualities',
        'in-itselfness',
        'exists for itself',
        'something material',
        'weight',
        'intensively',
        'extensively',
        'aggregate of parts',
        'externality',
        'abstract and idealized',
        'space',
        'quantitatively determined',
        'mutual relation',
        'qualitative nature',
        'material something',
        'ratio of weight to volume',
        'specifically determined gravity',
        'volume',
        'idealized element',
        'unit',
        'intensive aspect',
        'extensive magnitude',
        'aggregate of ones',
        'amount',
        'purely qualitative relating',
        'determinacies of magnitude',
        'ratio of powers',
        'disappeared',
        'self-subsistence',
        'being-for-itself',
        'material being',
        'immediacy',
        'come back',
        'determinateness of magnitude',
        'quantum',
        'relation to other side',
        'ordinary exponent',
        'direct ratio',
      ],
      { section: 'The Relation of Independent Measures', order: 5 }
    ),

    createTopicMapEntry(
      'rm-a-a-2-exponent-inner-measure',
      'Exponent — inner measure, subject to alteration',
      [63, 95],
      'Exponent = specific quantum (immediate, determined by comparison with other exponents). Exponent = inner measure characteristic, but rests on quantum = external and indifferent determinateness, subject to alteration. Other = quantum which is also exponent of specific ratio. Two things of different inner measure: each preserves itself, but self-preservation = negative relating, specification, alteration of measure itself = reciprocal specification.',
      [
        'exponent',
        'specific quantum',
        'something',
        'immediate quantum',
        'determined',
        'compared with other exponents',
        'like ratios',
        'constitutes',
        'specific way',
        'determined in itself',
        'inner measure characteristic',
        'something\'s measure',
        'rests on quantum',
        'external',
        'indifferent determinateness',
        'subject to alteration',
        'other',
        'relate as alterable',
        'aggregate of matters',
        'quantum in general',
        'holds out',
        'specific intrinsic determination',
        'quantum',
        'exponent of such specific ratio',
        'two things',
        'different inner measure',
        'stand connected',
        'enter into composition',
        'two metals',
        'different specific gravity',
        'homogeneous',
        'nature',
        'composition',
        'metal combining with water',
        'each of two measures',
        'preserves itself',
        'alteration',
        'externality of quantum',
        'measure',
        'self-preservation',
        'negative relating',
        'quantum',
        'specification',
        'exponent of ratio of measure',
        'alteration of measure itself',
        'reciprocal specification',
      ],
      { section: 'The Relation of Independent Measures', order: 6 }
    ),

    createTopicMapEntry(
      'rm-a-a-3-compound-volume-alteration',
      'Compound — weight sum, volume alteration, space idealization',
      [97, 137],
      'Compound: quantitatively would be sum of magnitudes, but only weight = sum (side capable of addition, stability, permanent immediate quantum). Alteration falls in exponents (qualitative side, being-for-itself). Immanent determining appears in other quality (idealized side). Mixing diverse materials: alteration of total volume (diminution). Space = stability but in face of negativity = alterable, idealization.',
      [
        'merely quantitative determination',
        'compound',
        'mere sum',
        'two magnitudes',
        'one quality',
        'other quality',
        'sum of two weights',
        'two volumes',
        'compound of two matters',
        'different specific weights',
        'weight of mixture',
        'remain equal',
        'said sum',
        'space',
        'mixture occupies',
        'sum of two spaces',
        'weight of mixture',
        'sum of weights',
        'present prior to combination',
        'side capable of addition',
        'one existing for itself',
        'attained stability of being',
        'permanent immediate quantum',
        'weight of matter',
        'aggregate of material parts',
        'alteration falls',
        'exponents',
        'expression',
        'qualitative side',
        'compound',
        'being-for-itself',
        'relations of measure',
        'quantum as such',
        'subject',
        'accidental alteration',
        'increase',
        'summed',
        'being-for-itself',
        'negating factor',
        'externality',
        'immanent determining',
        'quantitative element',
        'weight',
        'turns up',
        'other quality',
        'idealized side',
        'relation',
        'surprising',
        'sense-perception',
        'mixing',
        'specifically diverse materials',
        'results',
        'alteration of total volume',
        'diminution',
        'space',
        'gives stability',
        'matters',
        'existing outside one another',
        'stability',
        'face of negativity',
        'being-for-itself',
        'no existence in itself',
        'alterable',
        'space',
        'posited',
        'truth',
        'idealization',
      ],
      { section: 'The Relation of Independent Measures', order: 7 }
    ),

    createTopicMapEntry(
      'rm-a-a-4-measure-not-stable',
      'Measure not stable — determinateness in other measure-relations',
      [139, 145],
      'Measure itself posited as alterable, qualitative determinateness not stable within but has determinateness in other measure-relations.',
      [
        'not only',
        'qualitative sides',
        'posited as alterable',
        'measure itself',
        'qualitative determinateness',
        'something',
        'based on it',
        'shown itself',
        'not something stable within',
        'quantum in general',
        'determinateness',
        'other measure-relations',
      ],
      { section: 'The Relation of Independent Measures', order: 8 }
    ),

    createTopicMapEntry(
      'rm-a-b-1-independence-union',
      'Independence and union — preserving through quantitative indifference',
      [149, 171],
      'Something as measure-relation: independent yet capable of union with another measure-relation. In union, each preserves itself through permanence of quantitative indifference, behaves as specifying moment of new measure-relation. Quality enveloped in quantitative element, indifferent towards exponent (external determinateness). Specific property not expressed in one measure-relation alone.',
      [
        'something united with other',
        'simple qualitative determination',
        'sublate themselves',
        'being compounded',
        'something',
        'in itself measure-relation',
        'independent',
        'capable of union',
        'another',
        'also in itself measure-relation',
        'sublated in union',
        'each preserves itself',
        'permanence',
        'quantitative indifference',
        'behaves',
        'specifying moment',
        'new measure-relation',
        'quality',
        'enveloped',
        'quantitative element',
        'indifferent towards',
        'exponent',
        'new measure',
        'some quantum or other',
        'external determinateness',
        'indifference',
        'displayed',
        'specifically determined something',
        'runs',
        'other such measures',
        'same kind',
        'neutralizations',
        'reciprocal measure-relations',
        'specific property',
        'something',
        'not expressed',
        'one measure-relation alone',
        'formed',
        'another something',
      ],
      { section: 'The Relation of Independent Measures', order: 9 }
    ),

    createTopicMapEntry(
      'rm-a-b-2-series-exponents',
      'Series of exponents — comparative numbers, unit and amounts',
      [173, 270],
      'Combination with plurality yields different ratios with different exponents. Independent measure has exponent only in comparison with other measures; neutrality = real comparison. Independent measure displays qualitative exponent as series of different amounts (unit). Truly differentiates in characteristic series of exponents. Comparison requires unit common to both (ratio of exponents of series). Both sides are series: each number = unit with respect to opposite series, exponent for each member, comparative number for rest of its series.',
      [
        'combination',
        'plurality of others',
        'in themselves likewise measures',
        'yields different ratios',
        'different exponents',
        'measure which is independent',
        'exponent',
        'being-determined-in-itself',
        'comparison with other measures',
        'neutrality',
        'others',
        'real comparison',
        'comparison with them through itself',
        'exponents of these ratios',
        'diverse',
        'independent measure',
        'consequently displays',
        'qualitative exponent',
        'series',
        'different amounts',
        'unit',
        'series of specific ways',
        'relating to others',
        'one immediate quantum',
        'qualitative exponent',
        'expresses',
        'one single relation',
        'independent measure',
        'truly differentiates itself',
        'characteristic series of exponents',
        'taken as unit',
        'forms',
        'other equally independent measures',
        'each of these measures',
        'brought in connection',
        'any other',
        'taken as unit',
        'forms another series',
        'relation of such series',
        'among themselves',
        'constitutes',
        'qualitative aspect',
        'independent measure',
        'independent measure produces',
        'series of exponents',
        'series of such independent measures',
        'compared with another',
        'independent measure',
        'outside this series itself',
        'differentiated',
        'other independent measure produces',
        'another series of exponents',
        'same measures',
        'opposite to it',
        'two independent measures',
        'not be comparable',
        'regarded as unit',
        'respect to exponents',
        'two series',
        'resulting',
        'basis',
        'connection of unit and exponents',
        'do not differ',
        'determinate way',
        'two measures',
        'independent',
        'supposed to be compared',
        'differentiated from each other',
        'only as quanta',
        'ratio be determined',
        'ratio requires',
        'unit',
        'exists for itself',
        'common to both',
        'determinate unit',
        'sought',
        'specific existence',
        'two independent measures',
        'compared',
        'found',
        'ratio',
        'exponents of ratio',
        'series',
        'have to each other',
        'ratio of exponents',
        'unit existing for itself',
        'determinate',
        'members of series',
        'constant ratio',
        'between them',
        'common unit',
        'possibility of comparing',
        'two independent measures',
        'assumed',
        'not neutralize each other',
        'reciprocally indifferent',
        'taken by itself',
        'outside comparison',
        'unit of ratios',
        'establishes',
        'opposite members',
        'amounts',
        'relative to this unit',
        'represent',
        'series of exponents',
        'conversely',
        'series',
        'unit',
        'two independent measures',
        'compared with each other',
        'quanta to each other',
        'different amounts',
        'just indicated unit',
        'measures',
        'together with two',
        'indefinitely many',
        'reciprocally opposing',
        'contrasting measures',
        'yield',
        'series of exponents',
        'ratio of these same measures',
        'equally independent',
        'in themselves',
        'specific something',
        'own relevant measure-relation',
        'to this extent',
        'similarly to be taken',
        'each as unit',
        'series of exponents',
        'two',
        'indeterminate plurality of measures',
        'first named',
        'compared only among themselves',
        'exponents',
        'comparative numbers',
        'precisely these named measures',
        'conversely',
        'comparative numbers',
        'independent measures',
        'taken singly',
        'similarly',
        'series of exponents',
        'members of first series',
        'both sides',
        'series',
        'each number',
        'simply unit',
        'respect to opposite series',
        'specifically determined being',
        'series of exponents',
        'each number',
        'exponent',
        'each member',
        'opposite series',
        'comparative number',
        'rest of numbers',
        'its series',
        'amount',
        'belongs',
        'also as exponent',
        'unit',
        'determined for itself',
        'opposite series',
      ],
      { section: 'The Relation of Independent Measures', order: 10 }
    ),

    createTopicMapEntry(
      'rm-a-b-3-return-degree-exclusive',
      'Return to degree — exclusive unit, elective affinity',
      [271, 323],
      'Return to quantum as degree (magnitude in quantum outside it, circle of quanta). In measure: externality = series of numerical ratios. Independent measure = self-externality. Self-reference = immediate relation, indifference only in quantum. Qualitative side falls in externality, relating to other = specific determination. Two measures specify themselves in third (exponent): each negatively posited, preserves itself, negation negated = qualitative unity = exclusive unit existing for itself. Exponents gain determinateness specifying reciprocally, difference = qualitative nature (but quantitative basis). Affinity = elective affinity.',
      [
        'relation',
        'return to mode',
        'quantum',
        'posited as existing for itself',
        'degree',
        'being simple',
        'magnitude of determinateness',
        'quantum that exists outside it',
        'circle of quanta',
        'measure',
        'externality',
        'merely quantum',
        'circle of quanta',
        'series of numerical ratios',
        'entirety of these',
        'being-determined-for-itself',
        'measure',
        'being-for-itself',
        'quantum as degree',
        'nature of independent measure',
        'turned into',
        'self-externality',
        'self-reference',
        'at first',
        'immediate relation',
        'indifference to other',
        'lies only in quantum',
        'qualitative side',
        'falls in externality',
        'relating to other',
        'constitutes',
        'specific determination',
        'independent measure',
        'determination',
        'consists solely',
        'quantitative mode',
        'relating',
        'determined',
        'other',
        'measure itself',
        'other',
        'series of quanta',
        'measure',
        'one such quantum',
        'connection',
        'two specific measures',
        'specify themselves',
        'third thing',
        'exponent',
        'entails',
        'exponent',
        'one measure',
        'not gone over into other',
        'not only one negation',
        'connection',
        'two measures',
        'each negatively posited',
        'each preserves itself',
        'indifferently',
        'negation',
        'also negated',
        'qualitative unity',
        'exclusive unit',
        'existing for itself',
        'moment of exclusion',
        'exponents',
        'at first comparative numbers',
        'gain',
        'determinateness',
        'truly specifying',
        'reciprocally',
        'difference',
        'qualitative nature',
        'difference',
        'quantitative basis',
        'independent measure',
        'relates',
        'plurality',
        'qualitatively other side',
        'relating',
        'at same time indifferent',
        'neutral connection',
        'virtue',
        'quantitative basis',
        'not only alteration',
        'posited',
        'negation of negation',
        'exclusive unit',
        'consequently',
        'affinity',
        'independent measure',
        'plurality of measures',
        'other side',
        'no longer',
        'indifferent connection',
        'elective affinity',
      ],
      { section: 'The Relation of Independent Measures', order: 11 }
    ),

    createTopicMapEntry(
      'rm-a-c-1-chemical-musical-examples',
      'Chemical and musical examples — exclusive affinities',
      [327, 368],
      'Elective affinity = chemical relation. Matter receives specific determinateness in connection with other, exists only as non-indifference. Connection bound up with quantity, with series of non-indifferent matters. Affinity with every member, each excludes every other. Not just chemical: single note depends on relation to other notes, harmony/disharmony = qualitative nature based on quantitative ratios forming series of exponents. Single note = keynote of system, also member in system of every other note. Harmonies = exclusive elective affinities, quality dissolves in quantitative progression. Principle of measure for affinities = question of higher order.',
      [
        'expression',
        'elective affinity',
        'used here',
        'refers',
        'chemical relation',
        'preceding neutrality',
        'affinity',
        'chemical sphere',
        'matter',
        'receives',
        'specific determinateness',
        'essentially',
        'connection with other',
        'exists concretely',
        'non-indifference',
        'specific connection',
        'bound up with quantity',
        'connection with single other',
        'series',
        'non-indifferent matters',
        'standing over and against it',
        'combinations',
        'series',
        'rest on',
        'affinity',
        'every member of series',
        'indifference',
        'each member excludes',
        'every other',
        'connection of opposite determinations',
        'not just chemical sphere',
        'specificity',
        'exhibited',
        'circle of combinations',
        'meaning',
        'single note',
        'depends',
        'relation',
        'combination',
        'another note',
        'series of other notes',
        'harmony',
        'disharmony',
        'circle of combinations',
        'constitutes',
        'qualitative nature',
        'based on',
        'quantitative ratios',
        'form',
        'series of exponents',
        'ratios of two specific ratios',
        'each of combined notes',
        'within it',
        'single note',
        'keynote',
        'system',
        'member',
        'system of every other note',
        'harmonies',
        'exclusive elective affinities',
        'characteristic quality',
        'dissolves',
        'externality',
        'mere quantitative progression',
        'principle of measure',
        'affinities',
        'among others',
        'against others',
        'chemical',
        'musical',
        'whatever',
        'elective affinities',
        'following Remark',
        'connection',
        'chemical affinity',
        'question',
        'higher order',
        'closely bound up',
        'specific nature',
        'strictly qualitative',
        'belongs',
        'particular parts',
        'concrete science of nature',
      ],
      { section: 'The Relation of Independent Measures', order: 12 }
    ),

    createTopicMapEntry(
      'rm-a-c-2-quantitative-qualitative-conversion',
      'Quantitative vs qualitative — sudden conversion',
      [370, 430],
      'Member of series: qualitative unity in relating to whole of opposite series. More specific determinateness = quantitative. Elective affinity = exclusive qualitative connection, escapes quantitative difference. Exclusion based on extensive magnitudes (intensity) = no exclusiveness posited, combination of any number possible. But combination = neutralization, exponent = determination of measure, exclusive. Numbers lose continuity, relating = more or less (negative character). Advantage of one exponent over another not confined to magnitude. Other side: matter of indifference whether receives neutralizing quantum from several opposite moments. Exclusive relating vulnerable to incursion of quantitative side. Sudden conversion: indifferent quantitative → qualitative, specifically determinate being → external relation, series of relations (quantitative and specific).',
      [
        'member of series',
        'qualitative unity',
        'way',
        'relates',
        'whole',
        'opposite series',
        'members',
        'differ from each other',
        'quantum required',
        'neutralized',
        'member',
        'more specific determinateness',
        'manifold affinity',
        'likewise',
        'quantitative',
        'elective affinity',
        'exclusive',
        'qualitative connection',
        'relating',
        'escapes',
        'quantitative difference',
        'next determination',
        'offers itself',
        'accordance',
        'difference',
        'number',
        'extensive magnitudes',
        'members of one side',
        'required',
        'neutralization',
        'member',
        'another side',
        'elective affinity',
        'member',
        'directed',
        'members of first series',
        'affinity',
        'transformed',
        'exclusion',
        'established',
        'form',
        'firmer bonding',
        'against',
        'other possibilities',
        'combination',
        'appear',
        'proportionally greater intensity',
        'keeping',
        'previously demonstrated identity',
        'forms',
        'extensive',
        'intensive magnitude',
        'determinateness of magnitude',
        'both one and same',
        'sudden conversion',
        'one-sided form',
        'extensive magnitude',
        'also into its other',
        'intensive form',
        'changes nothing',
        'nature',
        'fundamental determination',
        'one and same quantum',
        'fact',
        'no exclusiveness',
        'posited',
        'instead',
        'one single bonding',
        'combination',
        'any number of members',
        'take place',
        'provided',
        'portions',
        'members',
        'entering into combination',
        'corresponded',
        'required quantum',
        'proportionately',
        'ratios',
        'between them',
        'combination',
        'also called neutralization',
        'not only',
        'form of intensity',
        'exponent',
        'essentially',
        'determination of measure',
        'exclusive',
        'side of exclusive relating',
        'numbers',
        'lost',
        'continuity',
        'tendency to combine',
        'relating',
        'more or less',
        'acquires',
        'negative character',
        'advantage',
        'one exponent',
        'over another',
        'not remain confined',
        'determinateness of magnitude',
        'also equally present',
        'other side',
        'makes',
        'matter of indifference',
        'moment of measure',
        'receives',
        'neutralizing quantum',
        'several opposite moments',
        'each',
        'accordance',
        'determinateness',
        'specifies',
        'against other',
        'exclusive',
        'negative relating',
        'same time',
        'vulnerable',
        'incursion',
        'quantitative side',
        'posited',
        'sudden conversion',
        'indifferent',
        'merely quantitative relating',
        'qualitative one',
        'conversely',
        'transition',
        'specifically determinate being',
        'merely external relation',
        'series of relations',
        'sometimes',
        'merely quantitative nature',
        'sometimes',
        'specific relations',
        'measures',
      ],
      { section: 'The Relation of Independent Measures', order: 13 }
    ),
  ],
  {
    sectionDescription: 'The Relation of Independent Measures - Introduction (self-subsistent measures). (a) Whole immediate (external combination). (b) Self-subsistent materialities (affinity). (c) Elective affinity (exclusive being-for-itself). a. Combination of two measures (measure relation, exponent, compound, measure not stable). b. Measure as a series of measure-relations (independence and union, series of exponents, return to degree). c. Elective affinity (chemical and musical examples, quantitative vs qualitative conversion).',
  }
);

