/**
 * TopicMap for measureless.txt - The Measureless
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - measureless-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const MEASURELESS_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/measure/real-measure/sources/measureless.txt',
  'Hegel\'s Science of Logic - Measure',
  'The Measureless',
  [
    createTopicMapEntry(
      'rm-c-1-driven-into-measureless',
      'Driven into measureless — magnitude as entanglement',
      [3, 13],
      'Exclusive measure affected by quantitative existence, susceptible to movement on quantum scale. Something/quality based on ratio driven into measureless, collapsing under mutation of magnitude. Magnitude = constitutional aspect where existence caught in entanglement and destroyed.',
      [
        'exclusive measure',
        'realized being-for-itself',
        'remains affected',
        'moment',
        'quantitative existence',
        'susceptible',
        'movement',
        'up and down',
        'quantum scale',
        'varying ratios',
        'something',
        'quality',
        'based on',
        'ratio',
        'driven beyond itself',
        'measureless',
        'collapsing',
        'mere mutation',
        'magnitude',
        'constitutional aspect',
        'existence',
        'caught up',
        'apparently harmless entanglement',
        'destroyed',
      ],
      { section: 'The Measureless', order: 1 }
    ),

    createTopicMapEntry(
      'rm-c-2-abstract-measureless',
      'Abstract measureless — alternation ad infinitum',
      [15, 34],
      'Abstract measureless = quantum lacking internal order, indifferent determinateness not altering measure. In nodal lines: determinateness posited as specifying. Abstract measureless sublates into qualitative determinateness. New measure-relation measureless with respect to original but quality existing for itself. Alternation of specific existences with quantitative relations ad infinitum. Transition = negation of specific relations + negation of quantitative progression = infinite existing for itself.',
      [
        'abstract measureless',
        'quantum in general',
        'lacks internal order',
        'indifferent determinateness',
        'does not alter measure',
        'nodal lines',
        'measures',
        'determinateness',
        'posited',
        'specifying',
        'abstract measureless',
        'sublates itself',
        'qualitative determinateness',
        'new measure-relation',
        'original',
        'passes over',
        'measureless',
        'respect',
        'latter',
        'quality',
        'exists for itself',
        'posited',
        'alternation',
        'specific existences',
        'one another',
        'relations',
        'remain',
        'merely quantitative',
        'alternation ad infinitum',
        'present',
        'transition',
        'negation',
        'specific relations',
        'negation',
        'quantitative progression',
        'infinite existing for itself',
      ],
      { section: 'The Measureless', order: 2 }
    ),

    createTopicMapEntry(
      'rm-c-3-qualitative-vs-quantitative-infinite',
      'Qualitative vs quantitative infinite — reciprocal transition',
      [35, 65],
      'Qualitative infinite = irruption into finite, immediate transition/vanishing. Quantitative infinite = continuity of quantum, continuing beyond itself. Qualitatively finite becomes infinite; quantitatively finite points beyond itself. Infinite of specification posits qualitative and quantitative each sublating into other, posits first immediate unity (measure) as returned into itself. Transition of qualitative = alteration of magnitude determinateness. Qualitative→qualitative = external/indifferent alteration, coming together with itself. Quantitative sublates by turning into qualitative (determined in-and-for-itself). Unity continuing in alternating measures = self-subsistent matter persisting, the fact.',
      [
        'sphere of existence',
        'qualitative infinite',
        'irruption',
        'infinite',
        'finite',
        'immediate transition',
        'vanishing',
        'this here',
        'beyond there',
        'contrast',
        'quantitative infinite',
        'determinateness',
        'continuity',
        'quantum',
        'continuing beyond itself',
        'qualitatively finite',
        'becomes infinite',
        'quantitatively finite',
        'beyond',
        'points beyond itself',
        'infinite',
        'specification',
        'measure',
        'posits',
        'qualitative',
        'quantitative',
        'each',
        'sublating itself',
        'other',
        'thereby',
        'first immediate unity',
        'measure in general',
        'returned into itself',
        'consequently',
        'itself posited',
        'transition',
        'qualitative',
        'specific concrete existence',
        'another',
        'happens',
        'alteration',
        'magnitude determinateness',
        'alteration',
        'qualitative',
        'as such',
        'qualitative',
        'posited',
        'external',
        'indifferent alteration',
        'coming together',
        'itself',
        'quantitative',
        'sublates itself',
        'suddenly turning',
        'qualitative',
        'being',
        'determined',
        'in-and-for-itself',
        'unity',
        'continues',
        'alternating measures',
        'self-subsistent matter',
        'truly persists',
        'fact',
      ],
      { section: 'The Measureless', order: 3 }
    ),

    createTopicMapEntry(
      'rm-c-4-substantial-matter',
      'Substantial matter — perennial substrate',
      [69, 84],
      '(a) One and same substantial matter = perennial substrate of differentiations. Detaching of being from determinateness begins in quantum. In measure: persisting matter = unity of qualitative and quantitative (each beyond of other). Perennial substrate = existent infinity.',
      [
        'one and same',
        'substantial matter',
        'posited',
        'perennial substrate',
        'differentiations',
        'detaching',
        'being',
        'determinateness',
        'already begins',
        'quantum in general',
        'something',
        'great',
        'indifferently',
        'against',
        'determinateness',
        'has',
        'measure',
        'persisting matter',
        'itself',
        'already',
        'unity',
        'qualitative',
        'quantitative',
        'two moments',
        'general',
        'sphere of being',
        'distinguished',
        'each',
        'beyond',
        'other',
        'way',
        'perennial substrate',
        'begins to possess',
        'determination',
        'existent infinity',
      ],
      { section: 'The Measureless', order: 4 }
    ),

    createTopicMapEntry(
      'rm-c-5-self-sameness-quantitative-differences',
      'Self-sameness — quantitative differences',
      [86, 91],
      '(b) Self-sameness posited: qualitative independent measures (determining unit dispersed) consist of only quantitative differences. Substrate persists while internally distinguished.',
      [
        'self-sameness',
        'substrate',
        'posited',
        'qualitative independent measures',
        'determining unit',
        'dispersed',
        'consist',
        'only quantitative differences',
        'substrate',
        'persists',
        'while',
        'internally distinguished',
      ],
      { section: 'The Measureless', order: 5 }
    ),

    createTopicMapEntry(
      'rm-c-6-infinite-progression',
      'Infinite progression — reciprocal transition',
      [93, 111],
      '(c) Infinite progression: continuation of qualitative into quantitative (indifferent alteration), negation of qualitative and quantitative externality. Quantitative pointing beyond perishes with emergence of measure-relation/quality. Qualitative transition sublated (new quality = quantitative relation). Reciprocal transition on basis of unity. Meaning = demonstration that substrate underlies process, is unity of moments.',
      [
        'infinite progression',
        'nodal series',
        'posited',
        'continuation',
        'qualitative',
        'quantitative advance',
        'indifferent alteration',
        'equally',
        'negation',
        'qualitative',
        'contained',
        'progression',
        'consequently',
        'same time',
        'merely quantitative externality',
        'quantitative',
        'pointing beyond itself',
        'other',
        'itself quantitative',
        'perishes',
        'emergence',
        'measure-relation',
        'quality',
        'qualitative transition',
        'sublated',
        'very fact',
        'new quality',
        'itself only',
        'quantitative relation',
        'reciprocal transition',
        'other',
        'qualitative',
        'quantitative moments',
        'occurs',
        'basis',
        'unity',
        'meaning',
        'process',
        'existence',
        'demonstration',
        'positing',
        'substrate',
        'underlies',
        'process',
        'unity',
        'moments',
      ],
      { section: 'The Measureless', order: 6 }
    ),

    createTopicMapEntry(
      'rm-c-7-measures-as-states',
      'Measures as states — substrate persists',
      [113, 130],
      'Series of independent measure-relations: one-sided members = immediate qualitative somethings (specific gravities, chemical materials). Neutralizations = self-subsistent, exclusive measure-relations, mutually indifferent totalities. Relations determined as nodes of same substrate. Measures and forms demoted to states. Alteration = mutation of state. That which passes over = remaining same in mutation.',
      [
        'series',
        'independent measure relations',
        'one-sided members',
        'immediate qualitative somethings',
        'specific gravities',
        'chemical materials',
        'bases',
        'alkalis',
        'acids',
        'neutralizations',
        'understand',
        'combinations',
        'materials',
        'different specific gravities',
        'turn',
        'self-subsistent',
        'exclusive measure-relations',
        'mutually indifferent totalities',
        'existing for themselves',
        'relations',
        'determined',
        'nodes',
        'one and same substrate',
        'measures',
        'self-subsistent forms',
        'posited',
        'consequently',
        'demoted',
        'states',
        'alteration',
        'mutation',
        'state',
        'passes over',
        'posited',
        'remaining',
        'same',
        'mutation',
      ],
      { section: 'The Measureless', order: 7 }
    ),

    createTopicMapEntry(
      'rm-c-8-progressive-determination-summary',
      'Progressive determination summary — measure demoted to moment',
      [132, 174],
      'Progressive determination: Measure = immediate unity of quality and quantity (common quantum, specific). Measure = ratio (determinateness referring to itself). Holds moments as sublated/unseparated. Difference real, yields multitude of measure-relations (formal totalities, self-subsistent). Series = constant ordering. Ordering = immanently specifying unity, but principle = substrate/matter. Differences have only external quantitative determination (qualitative differentiation). In self-unity: measure determination = sublated, quality = external state determined by quantum. Course = progressive determination of measure + demotion to moment.',
      [
        'reviewing',
        'progressive determination',
        'measure',
        'gone through',
        'moments',
        'progression',
        'summed up',
        'measure',
        'first',
        'itself',
        'immediate unity',
        'quality',
        'quantity',
        'form',
        'common quantum',
        'specific',
        'determinateness',
        'quantity',
        'refers',
        'other',
        'refers to itself',
        'measure',
        'essentially',
        'ratio',
        'consequently',
        'holds',
        'moments',
        'sublated',
        'unseparated',
        'itself',
        'always',
        'case',
        'concept',
        'difference',
        'ratio',
        'each',
        'moments',
        'itself',
        'unity',
        'qualitative',
        'quantitative moment',
        'difference',
        'real',
        'yields',
        'multitude',
        'measure-relations',
        'formal totalities',
        'each',
        'self-subsistent',
        'themselves',
        'series',
        'form',
        'two sides',
        'ratios',
        'each single member',
        'same constant ordering',
        'member',
        'belonging',
        'one side',
        'relates itself',
        'whole series',
        'standing opposite',
        'ordering',
        'mere order',
        'still wholly external unity',
        'demonstrates itself',
        'immanently specifying unity',
        'measure',
        'determinate being-for-itself',
        'distinguished',
        'specifications',
        'specifying principle',
        'not yet',
        'free concept',
        'alone',
        'gives',
        'differences',
        'immanent determination',
        'principle',
        'first',
        'substrate',
        'matter',
        'differences',
        'order',
        'totalities',
        'should have',
        'themselves',
        'nature',
        'stable',
        'self-equal substrate',
        'available',
        'external quantitative determination',
        'shows itself',
        'same time',
        'qualitative differentiation',
        'self-unity',
        'substrate',
        'determination',
        'measure',
        'sublated determination',
        'quality',
        'external state',
        'determined',
        'quantum',
        'course',
        'equally',
        'progressive determination',
        'measure',
        'demotion',
        'moment',
      ],
      { section: 'The Measureless', order: 8 }
    ),
  ],
  {
    sectionDescription: 'The Measureless - Driven into measureless (magnitude as entanglement). Abstract measureless (alternation ad infinitum). Qualitative vs quantitative infinite (reciprocal transition). Substantial matter (perennial substrate). Self-sameness (quantitative differences). Infinite progression (reciprocal transition). Measures as states (substrate persists). Progressive determination summary (measure demoted to moment).',
  }
);

