/**
 * TopicMap for nodal-lines.txt - Nodal Lines of Measure-Relations
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - nodal-lines-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const NODAL_LINES_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/measure/real-measure/sources/nodal-lines.txt',
  'Hegel\'s Science of Logic - Measure',
  'Nodal Lines of Measure-Relations',
  [
    createTopicMapEntry(
      'rm-b-1-exclusive-measure-continuity',
      'Exclusive measure continuity — separability, indifference',
      [3, 33],
      'Measure-relation as specific = exclusive. Exclusiveness = negative unity of distinct moments. No further principle for connection with other neutralities; specification = quantitative determination. Exclusive elective affinity continues into opposite neutralities. Continuity not just external comparison; neutrality has separability. Moments as self-subsisting enter connection indifferently. Measure affected by indifference, external within, alterable in reference to itself.',
      [
        'last determination',
        'measure-relation',
        'specific',
        'exclusive',
        'exclusiveness',
        'accrues',
        'neutrality',
        'negative unity',
        'distinct moments',
        'unity existing for itself',
        'elective affinity',
        'no further principle',
        'available',
        'specifying',
        'connection',
        'other neutralities',
        'specification',
        'resides',
        'quantitative determination',
        'affinity in general',
        'specific amounts',
        'neutralize themselves',
        'consequently',
        'stand opposed',
        'other relative elective affinities',
        'moments',
        'basic determination',
        'quantitative',
        'exclusive elective affinity',
        'continues',
        'opposite neutralities',
        'continuity',
        'not just',
        'external comparative connection',
        'different ratios',
        'neutralities',
        'neutrality',
        'element of separability',
        'self-subsisting somethings',
        'moments',
        'union',
        'come to be',
        'enter into connection',
        'one or other',
        'opposite series',
        'enter into connection',
        'indifferently',
        'combine',
        'different specific determinate amounts',
        'measure',
        'internally based',
        'such relation',
        'reason',
        'affected',
        'indifference',
        'own',
        'something',
        'external within',
        'alterable',
        'reference to itself',
      ],
      { section: 'Nodal Lines of Measure-Relations', order: 1 }
    ),

    createTopicMapEntry(
      'rm-b-2-self-reference-qualitative-foundation',
      'Self-reference as qualitative foundation — substrate',
      [35, 44],
      'Self-reference differs from externality/alterability (quantitative side). Self-reference = existent qualitative foundation, permanent material substrate. Substrate = continuity of measure with itself in externality, contains principle of specification of externality.',
      [
        'self-reference',
        'measure-relation',
        'differs',
        'externality',
        'alterability',
        'belong',
        'quantitative side',
        'contrast',
        'self-reference',
        'existent qualitative foundation',
        'permanent',
        'material substrate',
        'continuity',
        'measure',
        'itself',
        'externality',
        'contain',
        'quality',
        'principle of specification',
        'externality',
      ],
      { section: 'Nodal Lines of Measure-Relations', order: 2 }
    ),

    createTopicMapEntry(
      'rm-b-3-self-repelling-measure',
      'Self-repelling measure — nodal line',
      [46, 66],
      'Exclusive measure external to itself repels itself, posits as another quantitative relation and another measure. Determined as specifying unity producing measure-relations within itself. Relations occur in same substrate, same moments. Self-repelling measure = other qualitatively diverse relations, form affinities and measures, alternating with quantitative diversities. Forms nodal line of measures on scale of more and less.',
      [
        'more developed form',
        'external',
        'itself',
        'being-for-itself',
        'exclusive measure',
        'repels itself',
        'from itself',
        'posits itself',
        'another',
        'merely quantitative relation',
        'another relation',
        'as such',
        'same time',
        'another measure',
        'determined',
        'in itself',
        'specifying unity',
        'produces',
        'measure-relations',
        'within itself',
        'relations',
        'differ',
        'affinities',
        'kind mentioned above',
        'independent measure',
        'relates itself',
        'independent measures',
        'another quality',
        'series',
        'occur',
        'one and same substrate',
        'within',
        'same moments',
        'neutrality',
        'self-repelling measure',
        'takes on',
        'determination',
        'other',
        'only qualitatively diverse relations',
        'relations',
        'likewise form',
        'affinities',
        'measures',
        'alternating',
        'remain',
        'only quantitative diversities',
        'form',
        'nodal line',
        'measures',
        'scale',
        'more and less',
      ],
      { section: 'Nodal Lines of Measure-Relations', order: 3 }
    ),

    createTopicMapEntry(
      'rm-b-4-qualitative-leap',
      'Qualitative leap — new quality, new something',
      [68, 100],
      'Measure-relation = self-subsistent reality qualitatively distinguished. Being-for-itself = relation of quanta, open to externality/quantitative alteration, has margin of indifference. At point: quality alters, quantum specifying, quantitative relation suddenly = measure = new quality = new something. New relation determined by first (qualitative sameness, quantitative continuity). But distinction = quantitative, new something indifferent to preceding, difference = external quantum. New something emerged from itself (internal specifying unity), not from preceding. New quality subjected to same progression, into infinity.',
      [
        'measure-relation',
        'self-subsistent reality',
        'qualitatively distinguished',
        'others',
        'being-for-itself',
        'essentially',
        'same time',
        'relation of quanta',
        'open',
        'externality',
        'quantitative alteration',
        'margin',
        'remains indifferent',
        'alteration',
        'does not alter',
        'quality',
        'point',
        'quantitative alteration',
        'quality alters',
        'quantum',
        'shows',
        'specifying',
        'altered quantitative relation',
        'suddenly',
        'turned into',
        'measure',
        'thereby',
        'new quality',
        'new something',
        'relation',
        'replaced',
        'first',
        'determined',
        'latter',
        'qualitative sameness',
        'moments',
        'affinity',
        'quantitative continuity',
        'distinction',
        'falls',
        'side',
        'quantitative moment',
        'new something',
        'stands',
        'indifferently',
        'related',
        'preceding',
        'difference',
        'two',
        'external',
        'quantum',
        'new something',
        'emerged',
        'preceding',
        'emerged',
        'immediately',
        'itself',
        'internal specifying unity',
        'not yet entered',
        'existence',
        'new quality',
        'new something',
        'subjected',
        'same progression',
        'alteration',
        'infinity',
      ],
      { section: 'Nodal Lines of Measure-Relations', order: 4 }
    ),

    createTopicMapEntry(
      'rm-b-5-gradualness-vs-leap',
      'Gradualness vs leap — absolute interruption',
      [102, 134],
      'Advance proceeds in steady continuity of quantity, ratios distinguished by more or less. Alteration = gradual. But gradualness = externality only, not qualitative moment. Preceding relation infinitely near succeeding = still another qualitative existence. From qualitative side: gradual progression absolutely interrupted. New quality = indeterminate other, indifferent, transition = leap, wholly external. Gradualness = alteration as merely indifferent, opposite of qualitative alteration. In gradualness: connecting link sublated, neither reality limit of other, absolutely external. Point for conceptual comprehension missed.',
      [
        'advance',
        'quality',
        'proceeds',
        'steady continuity',
        'quantity',
        'ratios',
        'approaching',
        'qualifying point',
        'distinguished',
        'quantitatively considered',
        'more or less',
        'respect',
        'alteration',
        'gradual',
        'gradualness',
        'concerns',
        'merely',
        'externality',
        'alteration',
        'qualitative moment',
        'preceding quantitative relation',
        'infinitely near',
        'succeeding',
        'still',
        'another qualitative existence',
        'qualitative side',
        'gradual',
        'merely quantitative progression',
        'no limits',
        'itself',
        'absolutely interrupted',
        'merely quantitative connection',
        'newly emerging quality',
        'respect',
        'vanishing',
        'indeterminate other',
        'indifferent',
        'transition',
        'leap',
        'two',
        'posited',
        'wholly external',
        'favorite practice',
        'try',
        'make',
        'alteration',
        'conceptually comprehensible',
        'gradualness',
        'transition',
        'leading up',
        'gradualness',
        'alteration',
        'precisely',
        'merely indifferent',
        'opposite',
        'qualitative alteration',
        'gradualness',
        'connecting link',
        'two realities',
        'states',
        'self-subsistent things',
        'sublated',
        'posited',
        'neither reality',
        'limit',
        'other',
        'each',
        'absolutely external',
        'very point',
        'necessary',
        'conceptual comprehension',
        'alteration',
        'missed',
        'little enough',
        'required',
        'purpose',
      ],
      { section: 'Nodal Lines of Measure-Relations', order: 5 }
    ),
  ],
  {
    sectionDescription: 'Nodal Lines of Measure-Relations - Exclusive measure continuity (separability, indifference). Self-reference as qualitative foundation (substrate). Self-repelling measure (nodal line). Qualitative leap (new quality, new something). Gradualness vs leap (absolute interruption).',
  }
);

