npx tsx examples/src/gds/gds-astar-stream.ts
npx tsx examples/src/gds/gds-bellman-ford-estimate.ts
npx tsx examples/src/gds/gds-bellman-ford-stats.ts
npx tsx examples/src/gds/gds-bellman-ford-stream.ts
npx tsx examples/src/gds/gds-betweenness-centrality-estimate.ts
npx tsx examples/src/gds/gds-betweenness-centrality-stats.ts
npx tsx examples/src/gds/gds-bfs-estimate.ts
npx tsx examples/src/gds/gds-bfs-stats.ts
npx tsx examples/src/gds/gds-bfs-stream.ts
npx tsx examples/src/gds/gds-closeness-centrality-estimate.ts
npx tsx examples/src/gds/gds-closeness-centrality-stats.ts
npx tsx examples/src/gds/gds-degree-centrality-estimate.ts
npx tsx examples/src/gds/gds-degree-centrality-mutate.ts
npx tsx examples/src/gds/gds-degree-centrality-stats.ts
npx tsx examples/src/gds/gds-dfs-stream.ts
npx tsx examples/src/gds/gds-dijkstra-estimate.ts
npx tsx examples/src/gds/gds-dijkstra-stats.ts
npx tsx examples/src/gds/gds-dijkstra-stream.ts
npx tsx examples/src/gds/gds-graph-exists.ts
npx tsx examples/src/gds/gds-list-graphs-admin-scope.ts
npx tsx examples/src/gds/gds-list-graphs.ts
npx tsx examples/src/gds/gds-pagerank-estimate.ts
npx tsx examples/src/gds/gds-pagerank-stats.ts
npx tsx examples/src/gds/gds-pagerank-stream.ts
npx tsx examples/src/gds/gds-ping.ts
npx tsx examples/src/gds/gds-project-native-prune-properties.ts
npx tsx examples/src/gds/gds-project-native.ts
npx tsx examples/src/gds/gds-stream-node-properties.ts
npx tsx examples/src/gds/gds-stream-relationship-properties.ts
npx tsx examples/src/gds/gds-stream-relationships.ts
npx tsx examples/src/gds/gds-version.ts
