import type { DialecticIR, DialecticState } from '@schema/dialectic';

// Generated by src/relative/core/compiler/generate-being-for-self-ir.ts
const stateBeingForSelfA: DialecticState = {
  "id": "being-for-self-a",
  "title": "Being-for-itself as sublated otherness",
  "concept": "GeneralBeingForSelf",
  "phase": "quality",
  "moments": [
    {
      "name": "infiniteTurningBack",
      "definition": "Being-for-itself is the infinite turning back into itself by sublating otherness",
      "type": "sublation"
    },
    {
      "name": "idealityInConsciousness",
      "definition": "The other persists only as moment, giving the form of ideality",
      "type": "reflection",
      "relation": "contains",
      "relatedTo": "infiniteTurningBack"
    }
  ],
  "invariants": [
    {
      "id": "being-for-self-a-inv-1",
      "constraint": "otherness is retained only as sublated moment",
      "predicate": "retainedAsSublated(otherness)"
    },
    {
      "id": "being-for-self-a-inv-2",
      "constraint": "self-reference is constituted through negation of limit",
      "predicate": "selfReferenceThroughNegation(limit)"
    }
  ],
  "forces": [
    {
      "id": "being-for-self-a-force-1",
      "description": "Infinite self-reference must be articulated as existence bent back into being-for-one",
      "type": "mediation",
      "trigger": "selfReference.requiresExistentialMoment = true",
      "effect": "beingForOne.explicit = true",
      "targetState": "being-for-self-b"
    }
  ],
  "transitions": [
    {
      "id": "being-for-self-a-trans-1",
      "from": "being-for-self-a",
      "to": "being-for-self-b",
      "mechanism": "mediation",
      "description": "From general being-for-itself to being-for-one"
    }
  ],
  "nextStates": [
    "being-for-self-b"
  ],
  "previousStates": [
    "affirmative-infinity-16"
  ],
  "provenance": {
    "topicMapId": "being-for-self-a",
    "lineRange": {
      "start": 49,
      "end": 103
    },
    "section": "A. BEING-FOR-ITSELF AS SUCH",
    "order": 1
  },
  "description": "The general concept of being-for-itself has come to light. The justification for using the expression 'being-for-itself' for that concept would depend on showing that the representation associated with the expression corresponds to the concept. Something is for itself inasmuch as it sublates otherness, sublates its connection and community with other, has rejected them by abstracting from them. The other is in it only as something sublated, as its moment; being-for-itself consists in having thus transcended limitation, its otherness; it consists in being, as this negation, the infinite turning back into itself. Consciousness contains determination of being-for-itself; content of object is idealization. Being-for-itself is polemical, negative relating to limiting other. Self-consciousness is being-for-itself brought to completion and posited; it is the nearest example of the presence of infinity.",
  "keyPoints": [
    "General concept of being-for-itself has come to light",
    "Expression 'being-for-itself' corresponds to concept",
    "Something is for itself inasmuch as it sublates otherness",
    "Sublates connection and community with other, has rejected them by abstracting",
    "Other is in it only as something sublated, as its moment",
    "Being-for-itself consists in having transcended limitation, its otherness",
    "Being as this negation, the infinite turning back into itself",
    "Consciousness contains determination of being-for-itself",
    "Content of object is idealization",
    "Consciousness abides with itself even in negative/other",
    "Being-for-itself is polemical, negative relating to limiting other",
    "Through negation of other, is being-reflected-within-itself",
    "Consciousness is phenomenal, dualism: external object and idealized object",
    "Self-consciousness is being-for-itself brought to completion and posited",
    "Self-consciousness is nearest example of presence of infinity"
  ]
};
const stateBeingForSelfB: DialecticState = {
  "id": "being-for-self-b",
  "title": "Being-for-one as inseparable moment of ideality",
  "concept": "BeingForOne",
  "phase": "quality",
  "moments": [
    {
      "name": "forOneNotForAnother",
      "definition": "Ideality is for-one, yet this one is only the selfsame being-for-itself",
      "type": "determination"
    },
    {
      "name": "inseparableUnity",
      "definition": "Being-for-itself and being-for-one are not two separate determinacies",
      "type": "mediation",
      "relation": "contains",
      "relatedTo": "forOneNotForAnother"
    }
  ],
  "invariants": [
    {
      "id": "being-for-self-b-inv-1",
      "constraint": "being-for-one and being-for-itself are internally unified",
      "predicate": "internalUnity(beingForOne, beingForItself)"
    },
    {
      "id": "being-for-self-b-inv-2",
      "constraint": "the one-for-which is not an external other",
      "predicate": "notExternalOther(oneForWhich)"
    }
  ],
  "forces": [
    {
      "id": "being-for-self-b-force-1",
      "description": "Inseparable ideality collapses into immediate abstract unity as the one",
      "type": "sublation",
      "trigger": "moments.sunkIntoImmediacy = true",
      "effect": "one.emerges = true",
      "targetState": "being-for-self-c"
    }
  ],
  "transitions": [
    {
      "id": "being-for-self-b-trans-1",
      "from": "being-for-self-b",
      "to": "being-for-self-c",
      "mechanism": "sublation",
      "description": "From being-for-one to the one"
    }
  ],
  "nextStates": [
    "being-for-self-c"
  ],
  "previousStates": [
    "being-for-self-a"
  ],
  "provenance": {
    "topicMapId": "being-for-self-b",
    "lineRange": {
      "start": 129,
      "end": 192
    },
    "section": "b. Being-for-one",
    "order": 2
  },
  "description": "This moment gives expression to how the finite is in its unity with the infinite or as an idealization. Being-for-itself does not have negation in it as a determinateness or limit, and consequently also not as reference to an existence other than it. Although this moment is now being designated as being-for-one, there is yet nothing at hand for which it would be; there is not the one of which it would be the moment. There is only one being-for-another, and since this is only one being-for-another, it is also only being-for-one; there is only the one ideality. Being-for-one and being-for-itself do not therefore constitute two genuine determinacies. Being-for-itself refers itself to itself as sublated other, is for-one; in its other it refers itself only to itself. An idealization is necessarily for-one, but it is not for an other; the one, for which it is, is only itself. The 'I,' therefore, spirit in general, or God, are idealizations, because they are infinite; as existents which are for-themselves, however, they are not ideationally different from that which is for-one. God is therefore for himself, in so far he is himself that which is for him. Being-for-itself and being-for-one are not, therefore, diverse significations of ideality but essential, inseparable, moments of it.",
  "keyPoints": [
    "Moment expresses how finite is in unity with infinite or as idealization",
    "Being-for-itself does not have negation as determinateness or limit",
    "Not as reference to existence other than it",
    "Being-for-one: nothing at hand for which it would be",
    "Not the one of which it would be the moment",
    "Undistinguishedness of two sides in being-for-one",
    "Only one being-for-another, also only being-for-one",
    "Only one ideality",
    "Being-for-one and being-for-itself do not constitute two genuine determinacies",
    "Being-for-itself refers itself to itself as sublated other, is for-one",
    "In its other it refers itself only to itself",
    "Idealization is necessarily for-one, but not for an other",
    "The one for which it is, is only itself",
    "'I,' spirit, God are idealizations because infinite",
    "As existents for-themselves, not ideationally different from that which is for-one",
    "God is for himself, in so far he is himself that which is for him",
    "Being-for-itself and being-for-one are essential, inseparable moments of ideality"
  ]
};
const stateBeingForSelfC: DialecticState = {
  "id": "being-for-self-c",
  "title": "The one as abstract limit of being-for-itself",
  "concept": "TheOne",
  "phase": "quality",
  "moments": [
    {
      "name": "immediateUnity",
      "definition": "Moments collapse into simple immediacy, yielding the one as existent-for-itself",
      "type": "determination"
    },
    {
      "name": "selfReferentialContradiction",
      "definition": "The one contains moments that are both identical and opposed",
      "type": "contradiction",
      "relation": "transitions",
      "relatedTo": "immediateUnity"
    }
  ],
  "invariants": [
    {
      "id": "being-for-self-c-inv-1",
      "constraint": "the one is simple self-reference of sublating negation",
      "predicate": "simpleSelfReference(theOne)"
    }
  ],
  "forces": [
    {
      "id": "being-for-self-c-force-1",
      "description": "The one must externalize its contradiction into the many and their relation",
      "type": "passover",
      "trigger": "one.requiresExternalization = true",
      "effect": "oneManyDialectic.initiated = true",
      "targetState": "one-many-a"
    }
  ],
  "transitions": [
    {
      "id": "being-for-self-c-trans-1",
      "from": "being-for-self-c",
      "to": "one-many-a",
      "mechanism": "passover",
      "description": "From the one to one-and-many"
    }
  ],
  "nextStates": [
    "one-many-a"
  ],
  "previousStates": [
    "being-for-self-b"
  ],
  "provenance": {
    "topicMapId": "being-for-self-c",
    "lineRange": {
      "start": 194,
      "end": 231
    },
    "section": "c. The one",
    "order": 3
  },
  "description": "Being-for-itself is the simple unity of itself and its moments, of the being-for-one. There is only one determination present, the self-reference itself of the sublating. The moments of being-for-itself have sunk into an indifferentiation which is immediacy or being, but an immediacy that is based on the negating posited as its determination. Being-for-itself is thus an existent-for-itself, and, since in this immediacy its inner meaning vanishes, it is the totally abstract limit of itself: the one. Attention may be drawn in advance to the difficulties that lie ahead in the exposition of the development of the one, and to the source of these difficulties. The moments that constitute the concept of the one as being-for-itself occur in it one outside the other: (1) negation in general; (2) two negations that are, therefore, (3) the same, (4) absolutely opposed; (5) self-reference, identity as such; (6) negative reference which is nonetheless self-reference. These moments occur here apart because the form of immediacy, of being, enters into the being-for-itself as existent-for-itself; because of this immediacy, each moment is posited as a determination existent on its own, and yet they are just as inseparable. Hence, of each determination the opposite must equally be said; it is this contradiction that causes the difficulty that goes with the abstract nature of the moments.",
  "keyPoints": [
    "Being-for-itself is simple unity of itself and its moments, of being-for-one",
    "Only one determination present: self-reference itself of sublating",
    "Moments of being-for-itself have sunk into indifferentiation",
    "Indifferentiation is immediacy or being, but immediacy based on negating posited",
    "Being-for-itself is existent-for-itself",
    "In this immediacy inner meaning vanishes",
    "Totally abstract limit of itself: the one",
    "Difficulties in exposition of development of one",
    "Moments occur one outside the other:",
    "(1) negation in general",
    "(2) two negations",
    "(3) the same",
    "(4) absolutely opposed",
    "(5) self-reference, identity as such",
    "(6) negative reference which is nonetheless self-reference",
    "Moments occur apart because form of immediacy enters into being-for-itself",
    "Each moment posited as determination existent on its own, yet inseparable",
    "Of each determination the opposite must equally be said",
    "Contradiction causes difficulty with abstract nature of moments"
  ]
};

export const beingForSelfIR: DialecticIR = {
  id: "being-for-self-ir",
  title: "Being-for-Self IR: Self-Reference, Being-for-One, The One",
  section: "BEING - QUALITY - C. Being-for-Self",
  states: [
    stateBeingForSelfA,
    stateBeingForSelfB,
    stateBeingForSelfC,
  ],
  metadata: {
  "sourceFile": "being-for-self.txt",
  "totalStates": 3,
  "cpuGpuMapping": {
    "being-for-self-a": "quality",
    "being-for-self-b": "quality",
    "being-for-self-c": "quality"
  }
},
};

export const beingForSelfStates = {
  "being-for-self-a": stateBeingForSelfA,
  "being-for-self-b": stateBeingForSelfB,
  "being-for-self-c": stateBeingForSelfC,
};
