/**
 * TopicMap for relation-causality.txt - The Relation of Causality
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - relation-causality-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 *
 * NOTE: There is a gap at lines 514-563 (section "3. We now have to see what has resulted...")
 * that is not currently chunked. This should be addressed in future upgrades.
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const RELATION_CAUSALITY_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/essence/actuality/substance/sources/relation-causality.txt',
  'Hegel\'s Science of Logic - The Absolute Relation',
  'The Relation of Causality',
  [
    createTopicMapEntry(
      'sub-b-1-substance-power-cause',
      'Substance as power — cause and effect',
      [3, 15],
      'Substance = power reflected into itself (not transitive, posits determinations, distinguishes from itself). Self-referring in determining = itself posited as negative/positedness. Positedness = sublated substantiality, merely posited = effect. Substance existing for itself = cause. Relation of causality = relation of cause and effect = formal relation of causality.',
      [
        'substance',
        'power',
        'reflected into itself',
        'not transitive',
        'posits determinations',
        'distinguishes from itself',
        'self-referring',
        'determining',
        'negative',
        'positedness',
        'sublated substantiality',
        'merely posited',
        'effect',
        'substance existing for itself',
        'cause',
        'relation of causality',
        'cause and effect',
        'formal relation of causality',
      ],
      { section: 'The Relation of Causality', order: 1 }
    ),

    createTopicMapEntry(
      'sub-b-2-formal-cause-originative',
      'Formal causality — cause is originative',
      [19, 67],
      'Cause = originative against effect. Substance as power = reflective shining/accidentality, immanent reflection, expounds transition, reflective shine determined, accident posited. Determining: substance does not proceed from accidentality, two are one actuosity. Substance determines itself, determining = sublation/turning back. Substance = immediate/already determined, posits already determined as determined, sublates positedness, returns into itself. Turning back = negative reference, determining/repelling from itself, determinate comes to be. Absolute actuosity = cause (power of substance, manifestation, accident/positedness expounded, posited as effect). Effect = substance as positedness; accident transient, effect self-identical; cause manifested as whole substance reflected into itself.',
      [
        'cause',
        'originative',
        'effect',
        'substance as power',
        'reflective shining',
        'accidentality',
        'immanent reflection',
        'expounds transition',
        'reflective shine determined',
        'accident posited',
        'determining',
        'does not proceed from accidentality',
        'one actuosity',
        'substance determines itself',
        'sublation',
        'turning back',
        'immediate',
        'already determined',
        'posits already determined',
        'sublates positedness',
        'returns into itself',
        'negative reference',
        'repelling from itself',
        'determinate comes to be',
        'absolute actuosity',
        'power of substance',
        'manifestation',
        'posited as effect',
        'substance as positedness',
        'accident transient',
        'effect self-identical',
        'cause manifested',
        'whole substance',
        'reflected into itself',
      ],
      { section: 'The Relation of Causality', order: 2 }
    ),

    createTopicMapEntry(
      'sub-b-3-cause-actuality-effect',
      'Cause has actuality only in effect — necessity',
      [69, 113],
      'Against positedness reflected = substance as non-posited original. Substance as absolute power = turning back into itself (determining), no longer mere in-itself but posited. Substance has actuality only as cause. Actuality (in-itself/determinateness posited) = effect. Substance has actuality as cause only in effect = necessity = cause. Actual substance (power determines itself) = cause (expounds determinateness, posits as positedness/effect). Other of cause = positedness against original, mediated. Cause as necessity sublates mediating, determines as originally self-referring, turns back to itself. Positedness = self-identical, cause actual/self-identical only in effect. Effect = necessary (manifestation of cause, necessity). Cause = self-moving, self-initiating, self-subsisting, must effect. Originariness: immanent reflection = positing that determines, two = one unity.',
      [
        'positedness reflected',
        'substance',
        'non-posited original',
        'absolute power',
        'turning back into itself',
        'determining',
        'no longer mere in-itself',
        'posited',
        'substance has actuality only as cause',
        'actuality',
        'in-itself',
        'determinateness posited',
        'effect',
        'substance has actuality as cause only in effect',
        'necessity',
        'cause',
        'actual substance',
        'power determines itself',
        'expounds determinateness',
        'posits as positedness',
        'other of cause',
        'positedness against original',
        'mediated',
        'cause as necessity',
        'sublates mediating',
        'originally self-referring',
        'turns back to itself',
        'positedness self-identical',
        'cause actual only in effect',
        'effect necessary',
        'manifestation of cause',
        'cause self-moving',
        'self-initiating',
        'self-subsisting',
        'must effect',
        'originariness',
        'immanent reflection',
        'positing that determines',
        'two one unity',
      ],
      { section: 'The Relation of Causality', order: 3 }
    ),

    createTopicMapEntry(
      'sub-b-4-effect-contains-cause',
      'Effect contains nothing cause does not — identity',
      [115, 133],
      'Effect contains nothing cause does not contain. Cause contains nothing not in effect. Cause = cause only to extent produces effect; to be cause = determination of having effect; to be effect = determination of having cause. Cause entails effect, effect entails cause. Cause not acted/ceased acting = not cause. Effect without cause = no longer effect = indifferent actuality.',
      [
        'effect contains nothing cause does not',
        'cause contains nothing not in effect',
        'cause only to extent produces effect',
        'to be cause',
        'determination of having effect',
        'to be effect',
        'determination of having cause',
        'cause entails effect',
        'effect entails cause',
        'cause not acted',
        'ceased acting',
        'not cause',
        'effect without cause',
        'no longer effect',
        'indifferent actuality',
      ],
      { section: 'The Relation of Causality', order: 4 }
    ),

    createTopicMapEntry(
      'sub-b-5-identity-extinguished',
      'Identity extinguished — immediacy',
      [135, 146],
      'In identity of cause/effect: form distinguishing (exists in itself/posited) = sublated. Cause extinguished in effect, effect extinguished (only determinateness of cause). Causality extinguished = immediacy (indifferent to relation, comes externally).',
      [
        'identity of cause and effect',
        'form distinguishing',
        'exists in itself',
        'posited',
        'sublated',
        'cause extinguished in effect',
        'effect extinguished',
        'determinateness of cause',
        'causality extinguished',
        'immediacy',
        'indifferent to relation',
        'comes externally',
      ],
      { section: 'The Relation of Causality', order: 5 }
    ),

    createTopicMapEntry(
      'sub-b-6-determinate-causality-content',
      'Determinate causality — content and form',
      [150, 180],
      'Self-identity of cause in effect = sublation of power/negativity = unity indifferent to form differences = content. Content refers to form (causality) only implicitly. Two posited as diverse, form = immediately efficient causality = contingent. Content = internally diversified, cause/effect determined according to content. Content (reflectedness = immediate actuality) = actual but finite substance. Relation of causality = reality and finitude. Formal = infinite relation of absolute power (content = pure manifestation/necessity). Finite = given content, external difference, runs course over identical content (one same substance).',
      [
        'self-identity of cause in effect',
        'sublation of power',
        'negativity',
        'unity indifferent to form differences',
        'content',
        'content refers to form',
        'causality',
        'only implicitly',
        'two posited as diverse',
        'form',
        'immediately efficient causality',
        'contingent',
        'content internally diversified',
        'cause effect determined according to content',
        'reflectedness',
        'immediate actuality',
        'actual but finite substance',
        'relation of causality',
        'reality',
        'finitude',
        'formal',
        'infinite relation of absolute power',
        'pure manifestation',
        'necessity',
        'finite causality',
        'given content',
        'external difference',
        'runs course',
        'identical content',
        'one same substance',
      ],
      { section: 'The Relation of Causality', order: 6 }
    ),

    createTopicMapEntry(
      'sub-b-7-analytic-proposition',
      'Analytic proposition — same content',
      [182, 197],
      'Identity of content = analytic proposition. Same fact as cause (subsisting on own) and as effect (positedness/determination). Form determinations = external reflection, tautological consideration determines appearance as effect, rises to cause. Same content repeated, nothing in cause not in effect.',
      [
        'identity of content',
        'analytic proposition',
        'same fact',
        'cause',
        'subsisting on own',
        'effect',
        'positedness',
        'determination',
        'form determinations',
        'external reflection',
        'tautological consideration',
        'determines appearance as effect',
        'rises to cause',
        'same content repeated',
        'nothing in cause not in effect',
      ],
      { section: 'The Relation of Causality', order: 7 }
    ),

    createTopicMapEntry(
      'sub-b-8-examples-analytic',
      'Examples — rain, color, act, movement',
      [198, 225],
      'Examples: Rain = cause of wetness (effect), analytical proposition, same water, different forms. Color: coloring agent = same actuality, different forms. Act: intention = same content/value as existence through action. Movement: propulsive force = same quantum before/after, same concrete existence communicated/lost.',
      [
        'rain',
        'cause of wetness',
        'effect',
        'analytical proposition',
        'same water',
        'different forms',
        'color',
        'coloring agent',
        'same actuality',
        'act',
        'intention',
        'same content value',
        'existence through action',
        'movement',
        'propulsive force',
        'same quantum',
        'before and after',
        'same concrete existence',
        'communicated',
        'lost',
      ],
      { section: 'The Relation of Causality', order: 8 }
    ),

    createTopicMapEntry(
      'sub-b-9-contingent-side-being',
      'Contingent side-being — inadmissible applications',
      [227, 340],
      'Cause has further content (contingent side-being) not entering into cause. Remote cause: alteration of form hides identity, several causes together contain complete effect. Shot not cause by itself, only moment of possibility. Inadmissible: causality to physico-organic/spiritual life. Living thing determines/alters/transmutes, sublates cause. Spirit does not admit originative principle, interrupts/transmutes. Effect cannot be greater than cause. Small causes/great effects = occasion/stimulus, spirit determines occasion. Conversion sublates causality.',
      [
        'cause',
        'further content',
        'contingent side-being',
        'not entering into cause',
        'remote cause',
        'alteration of form',
        'hides identity',
        'several causes together',
        'contain complete effect',
        'shot',
        'not cause by itself',
        'moment of possibility',
        'inadmissible',
        'causality',
        'physico-organic',
        'spiritual life',
        'living thing',
        'determines',
        'alters',
        'transmutes',
        'sublates cause',
        'spirit',
        'does not admit originative principle',
        'interrupts',
        'transmutes',
        'effect cannot be greater than cause',
        'small causes',
        'great effects',
        'occasion',
        'stimulus',
        'spirit determines occasion',
        'conversion',
        'sublates causality',
      ],
      { section: 'The Relation of Causality', order: 9 }
    ),

    createTopicMapEntry(
      'sub-b-10-substrate-substance',
      'Substrate and substance — finite causality',
      [342, 399],
      'Content/form different/indifferent. Form determination = content determination, cause/effect = another content. Content has form difference within, essentially different. Form of content = causality (identical in cause/effect), different content externally connected. External content = relationless, immediate concrete existence, implicit identity. Content = anything with manifold determinations (cause/effect). Form determinations have substrate (essential subsistence, particular subsistence, immediate, not unity of form/relation). Thing = substrate and substance (identical subsistence as subsistence of relation). Substance = finite (immediate over against causality, has causality, identity). Substrate as cause = negative reference to itself. "Itself" = positedness (immediately actual, any determination). Causality external = positedness. Causal substance: causality = negative self-reference (to positedness/external causality). Effective action: begins external, frees from external determination, turning back = preservation of immediate concrete existence, sublation of posited/causality.',
      [
        'content form different',
        'indifferent',
        'form determination',
        'content determination',
        'cause effect',
        'another content',
        'content has form difference within',
        'essentially different',
        'form of content',
        'causality',
        'identical in cause effect',
        'different content externally connected',
        'external content',
        'relationless',
        'immediate concrete existence',
        'implicit identity',
        'content',
        'manifold determinations',
        'form determinations',
        'substrate',
        'essential subsistence',
        'particular subsistence',
        'immediate',
        'not unity of form relation',
        'thing',
        'substrate',
        'substance',
        'identical subsistence',
        'subsistence of relation',
        'substance finite',
        'immediate over against causality',
        'has causality',
        'identity',
        'substrate as cause',
        'negative reference to itself',
        'positedness',
        'immediately actual',
        'any determination',
        'causality external',
        'causal substance',
        'negative self-reference',
        'effective action',
        'begins external',
        'frees from external determination',
        'turning back',
        'preservation of immediate concrete existence',
        'sublation of posited',
        'sublation of causality',
      ],
      { section: 'The Relation of Causality', order: 10 }
    ),

    createTopicMapEntry(
      'sub-b-11-infinite-regress',
      'Infinite regress — finite causality',
      [436, 512],
      'Second determinateness: causality external to itself (originariness = positedness/effect). Union of opposite determination = infinite regress. Cause finite (determinate, one moment, determinateness/negation outside, finite within, positedness/effect). Identity as positedness = third term (immediate substrate), causality external (originariness = immediacy). Form difference = first determinateness (existent otherness). Finite reflection: stops at immediate (cause/effect in different respects), transfers unity into infinite (endless progression, impotence). Same for effect: endless progression = regression. Cause begins external, returns but loses causality. Effect arrives at substance (original self-referring), positedness becomes positedness, substance behaves as cause. First effect external, second immanent reflection. Causality external fails to return, becomes external, bad infinity.',
      [
        'second determinateness',
        'causality external to itself',
        'originariness',
        'positedness',
        'effect',
        'union of opposite determination',
        'infinite regress',
        'cause finite',
        'determinate',
        'one moment',
        'determinateness negation outside',
        'finite within',
        'positedness effect',
        'identity as positedness',
        'third term',
        'immediate substrate',
        'causality external',
        'originariness immediacy',
        'form difference',
        'first determinateness',
        'existent otherness',
        'finite reflection',
        'stops at immediate',
        'cause effect in different respects',
        'transfers unity into infinite',
        'endless progression',
        'impotence',
        'effect',
        'endless progression',
        'regression',
        'cause begins external',
        'returns',
        'loses causality',
        'effect arrives at substance',
        'original self-referring',
        'positedness becomes positedness',
        'substance behaves as cause',
        'first effect external',
        'second immanent reflection',
        'causality external fails to return',
        'becomes external',
        'bad infinity',
      ],
      { section: 'The Relation of Causality', order: 11 }
    ),

    createTopicMapEntry(
      'sub-b-12-action-reaction',
      'Action and reaction — passive and efficient substance',
      [567, 606],
      'Causality = presupposing activity. Cause = conditioned, negative reference to itself as presupposed/external other (in itself = causality). Other = substantial identity (formal causality passes over, determined as negative). Substance confronted by power of accidentality = passive substance. Passive = immediate, exists-in-itself, not for itself, abstract self-identity. Efficient substance = negatively self-referring, cause (restored from effect through negation), reflected being, positing activity, mediates through negation. Causality = substance itself (no substrate, not form determination, at origin). Substrate = passive substance (presupposed).',
      [
        'causality',
        'presupposing activity',
        'cause',
        'conditioned',
        'negative reference to itself',
        'presupposed',
        'external other',
        'in itself causality',
        'other',
        'substantial identity',
        'formal causality passes over',
        'determined as negative',
        'substance',
        'confronted by power of accidentality',
        'passive substance',
        'passive',
        'immediate',
        'exists-in-itself',
        'not for itself',
        'abstract self-identity',
        'efficient substance',
        'negatively self-referring',
        'cause',
        'restored from effect',
        'through negation',
        'reflected being',
        'positing activity',
        'mediates through negation',
        'causality substance itself',
        'no substrate',
        'not form determination',
        'at origin',
        'substrate',
        'passive substance',
        'presupposed',
      ],
      { section: 'The Relation of Causality', order: 12 }
    ),

    createTopicMapEntry(
      'sub-b-13-violence-power',
      'Violence and power — reaction',
      [608, 778],
      'Cause acts (negative power over itself, own presupposition) on passive substance: sublates otherness, returns to itself; determines substance, posits sublation/turning back as determinateness. Positedness = effect. Presupposing: posits effect in other. Passive substance = double (self-subsistent other, presupposed, implicitly identical). Action double: sublation of determinateness/condition/self-subsistence; pre-supposing of itself (positing as other). Passive preserved, some determinations sublated, identity externally. Suffers violence. Violence = appearance of power (external). Power external: causal substance presupposing, posits itself as sublated. Violence = act of power. Passive = self-subsistent posited, internally fractured, condition (actuality = possible, in-itself = determinateness, only passive). Violence must be done; dominion = power of other, manifests both. Violence posits passive as posited (simple positive/immediate = posited, "pre-" = reflective shine stripped). Passive given due by action. Loses immediacy/substantiality. Determined as positedness = own determination. Determined = not sublated, rejoins itself, originariness. Preserved by active (active sublates itself); passive rejoins itself, makes itself cause. Posited by other = own becoming. Passive converted to cause: effect sublated = reaction. Passive = in itself as positedness, positedness posited by other. Reaction twofold: in itself posited; as posited displays as in-itself (positedness in itself, own in-itself, own effect, displays as cause). Reaction directed at first cause. Effect sublated = causal substantiality sublated. Cause makes itself effect (becomes passive); reacting substance sublates effect. Determinate causality: substance acted upon becomes cause (acts against positing effect). Did not react, posited effect in another = infinite progression. Cause implicitly identical, expires/revives. Conditioned causality: cause refers back to itself (effect = condition/presupposition/other, becoming = positing/sublating). Causality as passive becomes causal. First cause receives reaction, comes up again, activity bent around = action returning to itself = infinite reciprocal action.',
      [
        'cause acts',
        'negative power over itself',
        'own presupposition',
        'passive substance',
        'sublates otherness',
        'returns to itself',
        'determines substance',
        'posits sublation',
        'turning back',
        'determinateness',
        'positedness',
        'effect',
        'presupposing',
        'posits effect in other',
        'passive substance double',
        'self-subsistent other',
        'presupposed',
        'implicitly identical',
        'action double',
        'sublation of determinateness',
        'condition',
        'self-subsistence',
        'pre-supposing of itself',
        'positing as other',
        'passive preserved',
        'some determinations sublated',
        'identity externally',
        'suffers violence',
        'violence',
        'appearance of power',
        'power external',
        'causal substance presupposing',
        'posits itself as sublated',
        'violence act of power',
        'passive',
        'self-subsistent posited',
        'internally fractured',
        'condition',
        'actuality possible',
        'in-itself determinateness',
        'only passive',
        'violence must be done',
        'dominion',
        'power of other',
        'manifests both',
        'violence posits passive as posited',
        'simple positive',
        'immediate posited',
        'pre-',
        'reflective shine stripped',
        'passive given due by action',
        'loses immediacy',
        'substantiality',
        'determined as positedness',
        'own determination',
        'determined not sublated',
        'rejoins itself',
        'originariness',
        'preserved by active',
        'active sublates itself',
        'passive rejoins itself',
        'makes itself cause',
        'posited by other',
        'own becoming',
        'passive converted to cause',
        'effect sublated',
        'reaction',
        'passive in itself as positedness',
        'positedness posited by other',
        'reaction twofold',
        'in itself posited',
        'as posited displays as in-itself',
        'positedness in itself',
        'own in-itself',
        'own effect',
        'displays as cause',
        'reaction directed at first cause',
        'effect sublated',
        'causal substantiality sublated',
        'cause makes itself effect',
        'becomes passive',
        'reacting substance',
        'sublates effect',
        'determinate causality',
        'substance acted upon becomes cause',
        'acts against positing effect',
        'did not react',
        'posited effect in another',
        'infinite progression',
        'cause implicitly identical',
        'expires',
        'revives',
        'conditioned causality',
        'cause refers back to itself',
        'effect condition',
        'presupposition',
        'other',
        'becoming',
        'positing',
        'sublating',
        'causality as passive becomes causal',
        'first cause receives reaction',
        'comes up again',
        'activity bent around',
        'action returning to itself',
        'infinite reciprocal action',
      ],
      { section: 'The Relation of Causality', order: 13 }
    ),
  ],
  {
    sectionDescription: 'The Relation of Causality - Substance as power, cause and effect. Formal causality, cause is originative. Cause has actuality only in effect, necessity. Effect contains nothing cause does not, identity. Identity extinguished, immediacy. Determinate causality, content and form. Analytic proposition, same content. Examples: rain, color, act, movement. Contingent side-being, inadmissible applications. Substrate and substance, finite causality. Infinite regress, finite causality. Action and reaction, passive and efficient substance. Violence and power, reaction leading to infinite reciprocal action.',
  }
);

