import type { DialecticIR, DialecticState } from '@schema/dialectic';
import { INFINITY_TOPIC_MAP } from './sources/infinity-topic-map';

const state1: DialecticState = {
  id: 'infinity-concept-self-contradictory',
  title: 'Quantum as self-contradictory concept',
  concept: 'QuantitativeInfiniteConcept',
  phase: 'quantity',
  moments: [
    {
      name: 'selfContradictoryQuantum',
      definition:
        'Quantum is other than itself as limited and therefore driven beyond itself',
      type: 'negation',
    },
    {
      name: 'oughtAndBeyond',
      definition:
        'Quantum as ought is being-determined-in-other and thereby posits unlimitedness',
      type: 'mediation',
      relation: 'contains',
      relatedTo: 'selfContradictoryQuantum',
    },
  ],
  invariants: [
    {
      id: 'infinity-concept-self-contradictory-inv-1',
      constraint:
        'quantum is contradictory as finite and beyond-finite at once',
      predicate: 'contradictory(quantum)',
    },
    {
      id: 'infinity-concept-self-contradictory-inv-2',
      constraint: 'its beyond is generated by its own limit',
      predicate: 'beyondFromOwnLimit(quantum)',
    },
  ],
  forces: [
    {
      id: 'infinity-concept-self-contradictory-force-1',
      description:
        'Self-contradiction unfolds as the bad infinite process of perpetual surpassing',
      type: 'contradiction',
      trigger: 'quantum.limitPositsBeyond = true',
      effect: 'badInfinityProcess.explicit = true',
      targetState: 'infinity-process-infinitely-great-small',
    },
  ],
  transitions: [
    {
      id: 'infinity-concept-self-contradictory-trans-1',
      from: 'infinity-concept-self-contradictory',
      to: 'infinity-process-infinitely-great-small',
      mechanism: 'contradiction',
      description: 'From contradictory concept to bad infinite process',
    },
  ],
  nextStates: ['infinity-process-infinitely-great-small'],
  previousStates: ['quantum-identity-two-sides'],
  provenance: {
    topicMapId: 'infinity-concept-self-contradictory',
    lineRange: { start: 6, end: 22 },
    section: 'a. Its concept',
    order: 1,
  },
  description: INFINITY_TOPIC_MAP.entries[0]?.description,
  keyPoints: INFINITY_TOPIC_MAP.entries[0]?.keyPoints,
};

const state2: DialecticState = {
  id: 'infinity-process-infinitely-great-small',
  title: 'Bad infinite process: infinitely great and small',
  concept: 'BadInfiniteProcess',
  phase: 'quantity',
  moments: [
    {
      name: 'perpetualSurpassing',
      definition:
        'Each beyond becomes a new quantum, so increase and decrease never attain true infinity',
      type: 'process',
    },
    {
      name: 'shadowDeterminateness',
      definition:
        'Infinitely great and infinitely small are unsubstantial shadows of unresolved contradiction',
      type: 'negation',
      relation: 'contains',
      relatedTo: 'perpetualSurpassing',
    },
  ],
  invariants: [
    {
      id: 'infinity-process-infinitely-great-small-inv-1',
      constraint: 'bad infinity repeats positing and sublating without closure',
      predicate: 'perpetualCycleWithoutClosure(badInfinity)',
    },
    {
      id: 'infinity-process-infinitely-great-small-inv-2',
      constraint:
        'infinitely great and small remain quantitative determinations',
      predicate: 'remainQuantum(infinitelyGreat, infinitelySmall)',
    },
  ],
  forces: [
    {
      id: 'infinity-process-infinitely-great-small-force-1',
      description:
        'Exhaustion of bad infinity compels restoration of quantum as concept through negation of negation',
      type: 'sublation',
      trigger: 'badInfinity.contradictionExposed = true',
      effect: 'returnToQuality.explicit = true',
      targetState: 'infinity-quantum-return-quality',
    },
  ],
  transitions: [
    {
      id: 'infinity-process-infinitely-great-small-trans-1',
      from: 'infinity-process-infinitely-great-small',
      to: 'infinity-quantum-return-quality',
      mechanism: 'sublation',
      description:
        'From bad infinite process to restored qualitative determination',
    },
  ],
  nextStates: ['infinity-quantum-return-quality'],
  previousStates: ['infinity-concept-self-contradictory'],
  provenance: {
    topicMapId: 'infinity-process-infinitely-great-small',
    lineRange: { start: 131, end: 157 },
    section: 'b. The quantitative infinite process',
    order: 6,
  },
  description: INFINITY_TOPIC_MAP.entries[5]?.description,
  keyPoints: INFINITY_TOPIC_MAP.entries[5]?.keyPoints,
};

const state3: DialecticState = {
  id: 'infinity-quantum-return-quality',
  title: 'Return to quality: quantum as qualitative relation',
  concept: 'ReturnToQuality',
  phase: 'quantity',
  moments: [
    {
      name: 'negationOfNegation',
      definition:
        'Quantum restores its concept by sublating both finite quantum and abstract beyond',
      type: 'sublation',
    },
    {
      name: 'qualitativeDeterminateness',
      definition:
        'Quantum is what it is through relation to another quantum, with infinity immanent in it',
      type: 'quality',
      relation: 'transitions',
      relatedTo: 'negationOfNegation',
    },
  ],
  invariants: [
    {
      id: 'infinity-quantum-return-quality-inv-1',
      constraint: 'externality is now a moment of quantum itself',
      predicate: 'externalityAsMoment(quantum)',
    },
    {
      id: 'infinity-quantum-return-quality-inv-2',
      constraint: 'the true infinite is immanent and self-related',
      predicate: 'immanentInfinity(quantum)',
    },
  ],
  forces: [
    {
      id: 'infinity-quantum-return-quality-force-1',
      description:
        'Immanent infinity in quantum opens the ratio chapter as explicit quantitative relation',
      type: 'passover',
      trigger: 'quantum.qualitativelyDetermined = true',
      effect: 'ratioChapter.initiated = true',
      targetState: 'ratio-intro-qualitative-moment',
    },
  ],
  transitions: [
    {
      id: 'infinity-quantum-return-quality-trans-1',
      from: 'infinity-quantum-return-quality',
      to: 'ratio-intro-qualitative-moment',
      mechanism: 'passover',
      description: 'From restored quantum to quantitative ratio',
    },
  ],
  nextStates: ['ratio-intro-qualitative-moment'],
  previousStates: ['infinity-process-infinitely-great-small'],
  provenance: {
    topicMapId: 'infinity-quantum-return-quality',
    lineRange: { start: 246, end: 296 },
    section: 'c. The infinity of quantum',
    order: 10,
  },
  description: INFINITY_TOPIC_MAP.entries[9]?.description,
  keyPoints: INFINITY_TOPIC_MAP.entries[9]?.keyPoints,
};

export const infinityIR: DialecticIR = {
  id: 'infinity-ir',
  title: 'Infinity IR: Quantitative Infinity and Return to Quality',
  section: 'BEING - QUANTITY - D. Quantitative Infinity',
  states: [state1, state2, state3],
  metadata: {
    sourceFile: 'infinity.txt',
    totalStates: 3,
    cpuGpuMapping: {
      'infinity-concept-self-contradictory': 'quantity',
      'infinity-process-infinitely-great-small': 'quantity',
      'infinity-quantum-return-quality': 'quantity',
    },
  },
};

export const infinityStates = {
  'infinity-concept-self-contradictory': state1,
  'infinity-process-infinitely-great-small': state2,
  'infinity-quantum-return-quality': state3,
};
