/**
 * TopicMap for indifference-inverse-ratio.txt - Indifference as Inverse Ratio of Its Factors
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - indifference-inverse-ratio-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const INDIFFERENCE_INVERSE_RATIO_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/measure/becoming-essence/sources/indifference-inverse-ratio.txt',
  'Hegel\'s Science of Logic - Measure',
  'Indifference as Inverse Ratio of Its Factors',
  [
    createTopicMapEntry(
      'be-b-intro-posited-in-indifference',
      'Indifference posited as existing for itself',
      [3, 5],
      'Determination of indifference posited in indifference itself; indifference posited as existing for itself.',
      [
        'now',
        'see',
        'how',
        'determination',
        'indifference',
        'posited',
        'indifference itself',
        'latter',
        'posited',
        'therefore',
        'existing',
        'itself',
      ],
      { section: 'Introduction', order: 1 }
    ),

    createTopicMapEntry(
      'be-b-1-substrate-one-indivisible-measure',
      'Substrate as one indivisible independent measure',
      [7, 22],
      'Reduction of measure-relations establishes one substrate. Substrate = continuing into one another = one indivisible independent measure, wholly present in differentiation. Differentiation = quality and quantity. Substrate at first = result, in itself mediation but not posited as such, = substrate/indifference.',
      [
        'reduction',
        'at first',
        'independently',
        'accepted',
        'measure-relations',
        'establishes',
        'one substrate',
        'substrate',
        'continuing',
        'one another',
        'therefore',
        'one indivisible independent measure',
        'wholly present',
        'differentiation',
        'present',
        'differentiation',
        'two determinations',
        'contained',
        'measure',
        'quality',
        'quantity',
        'everything',
        'depends',
        'how',
        'two',
        'posited',
        'turn',
        'determined',
        'fact',
        'substrate',
        'at first',
        'posited',
        'result',
        'though',
        'itself',
        'mediation',
        'mediation',
        'not yet',
        'posited',
        'such',
        'reason',
        'first instance',
        'substrate',
        'respect',
        'determinateness',
        'indifference',
      ],
      { section: '1.', order: 2 }
    ),

    createTopicMapEntry(
      'be-b-1-inverse-ratio',
      'Inverse ratio — qualitative determination',
      [24, 52],
      'Difference = quantitative and external. Two different quanta of same substrate = their sum (quantum). Indifference = fixed measure, absolute limit, not quantum, not in opposition. Abstract determinateness falls into indifference. Two quanta alterable, restricted by fixed limit of sum, related negatively = qualitative determination. Stand in inverse ratio. Differs from formal inverted ratio: limit = real substrate, each side = whole.',
      [
        'consequently',
        'difference',
        'present',
        'at first',
        'essentially',
        'only',
        'quantitative',
        'external',
        'simply',
        'two different quanta',
        'one',
        'same substrate',
        'would',
        'thus',
        'their sum',
        'itself',
        'posited',
        'quantum',
        'indifference',
        'fixed measure',
        'implicitly',
        'existent',
        'absolute limit',
        'connected',
        'those differences',
        'would not',
        'itself',
        'quantum',
        'would not',
        'any way',
        'enter',
        'opposition',
        'others',
        'whether',
        'sum',
        'also',
        'exponent',
        'those others',
        'sums',
        'indifferences',
        'only',
        'abstract determinateness',
        'falls',
        'indifference',
        'two quanta',
        'order',
        'may',
        'posited',
        'moments',
        'alterable',
        'indifferent',
        'greater',
        'smaller',
        'relative',
        'one another',
        'however',
        'inasmuch',
        'restricted',
        'fixed limit',
        'their sum',
        'same time',
        'related',
        'each other',
        'not externally',
        'negatively',
        'now',
        'qualitative determination',
        'stand',
        'each other',
        'accordingly',
        'stand',
        'inverse ratio',
        'each other',
        'relation',
        'differs',
        'earlier',
        'formal',
        'inverted ratio',
        'inasmuch',
        'limit',
        'here',
        'real substrate',
        'each',
        'two sides',
        'posited',
        'having',
        'itself',
        'whole',
      ],
      { section: '1.', order: 3 }
    ),

    createTopicMapEntry(
      'be-b-1-two-qualities',
      'Two qualities — each side contains both',
      [54, 68],
      'Difference = two qualities. Each sublated by other, held together in unity, inseparable. Substrate = unity of two qualities. Each side contains both sides, distinguished by more of one quality, less of other. One quality predominates on one side, other on other side.',
      [
        'according',
        'qualitative determinacy',
        'just stated',
        'difference',
        'present',
        'further',
        'form',
        'two qualities',
        'each',
        'sublated',
        'other',
        'yet',
        'since',
        'two',
        'held together',
        'one unity',
        'constitute',
        'inseparable',
        'substrate itself',
        'indifference',
        'itself',
        'likewise',
        'unity',
        'two qualities',
        'consequently',
        'each',
        'sides',
        'relation',
        'equally',
        'contains',
        'both sides',
        'within',
        'itself',
        'distinguished',
        'other',
        'more',
        'one quality',
        'less',
        'other',
        'conversely',
        'one quality',
        'through',
        'quantum',
        'only',
        'predominates',
        'one side',
        'does',
        'other quality',
        'other side',
      ],
      { section: '1.', order: 4 }
    ),

    createTopicMapEntry(
      'be-b-1-inverted-relation-continuation',
      'Inverted relation recurs — continuation into each other',
      [70, 85],
      'Each side = inverted relation (formal, recurs). Sides continue into each other (qualitative determinations). Each quality relates itself in other to itself, present in both sides (different quantum). Quantitative difference = indifference, continuation = self-sameness of qualities. Sides contain whole determinations and indifference, posited as self-subsistent.',
      [
        'thus',
        'each side',
        'inverted relation',
        'formal',
        'recurs',
        'two distinguished sides',
        'sides themselves',
        'thus',
        'continue',
        'each other',
        'also',
        'according',
        'qualitative determinations',
        'each',
        'qualities',
        'relates',
        'itself',
        'other',
        'itself',
        'present',
        'each',
        'two sides',
        'only',
        'different quantum',
        'quantitative difference',
        'indifference',
        'accordance',
        'continue',
        'each other',
        'continuation',
        'self-sameness',
        'qualities',
        'each',
        'two unities',
        'sides',
        'however',
        'each',
        'containing',
        'whole',
        'determinations',
        'consequently',
        'indifference itself',
        'thus',
        'same time',
        'posited',
        'self-subsistent',
        'vis-a-vis',
        'each other',
      ],
      { section: '1.', order: 5 }
    ),

    createTopicMapEntry(
      'be-b-2-indifference-existence',
      'Indifference as existence — totality',
      [87, 108],
      'Being as indifference = determinateness of measure (developed, not immediate). Indifference = whole of determinations resolved into unity. Existence = totality of posited realization. Moments = totality of indifference existing in itself, sustained as unity. Unity held fast only as indifference (implicit), moments not determined as existing for themselves. Present = indifference of unity towards itself as developed determinateness.',
      [
        'this indifference',
        'being',
        'now',
        'determinateness',
        'measure',
        'no longer',
        'immediacy',
        'developed manner',
        'just indicated',
        'indifference',
        'because',
        'itself',
        'whole',
        'determinations',
        'being',
        'now',
        'resolved',
        'unity',
        'existence',
        'well',
        'totality',
        'posited realization',
        'moments themselves',
        'totality',
        'indifference',
        'existing',
        'itself',
        'sustained',
        'latter',
        'unity',
        'because',
        'unity',
        'held fast',
        'only',
        'indifference',
        'consequently',
        'only',
        'implicitly',
        'itself',
        'moments',
        'not yet',
        'determined',
        'existing',
        'themselves',
        'not yet',
        'determined',
        'sublating',
        'themselves',
        'unity',
        'internally',
        'through',
        'each other',
        'here',
        'present',
        'therefore',
        'simply',
        'indifference',
        'unity itself',
        'towards',
        'itself',
        'developed determinateness',
      ],
      { section: '2.', order: 6 }
    ),

    createTopicMapEntry(
      'be-b-2-a-determinacies-emerge',
      'Determinacies emerge groundlessly — external',
      [110, 128],
      'Indivisible independent measure immanent in determinations, unity with itself. (a) Determinacies sublated implicitly remain totality, emerge groundlessly. Implicit being and existence unconnected. Determinacies show up immediately, indifference same in each. Difference = sublated = quantitative, not self-repelling. Indifference not self-determining, has determinate being only externally.',
      [
        'thus',
        'indivisible independent measure',
        'now',
        'more closely',
        'examined',
        'immanent',
        'all',
        'determinations',
        'remains',
        'unity',
        'itself',
        'undisturbed',
        'since',
        'determinacies',
        'sublated',
        'implicitly',
        'remain',
        'totality',
        'emerge',
        'groundlessly',
        'implicit',
        'being',
        'indifference',
        'existence',
        'thus',
        'unconnected',
        'determinacies',
        'show up',
        'indifference',
        'immediate manner',
        'indifference',
        'each',
        'entirely',
        'same',
        'difference',
        'between',
        'thus',
        'posited',
        'at first',
        'sublated',
        'hence',
        'quantitative',
        'reason',
        'therefore',
        'not',
        'self-repelling',
        'indifference',
        'not',
        'self-determining',
        'having',
        'becoming',
        'determinate being',
        'only',
        'externally',
      ],
      { section: '2. (a)', order: 7 }
    ),

    createTopicMapEntry(
      'be-b-2-b-inverse-quantitative-relation',
      'Inverse quantitative relation — externally determined',
      [130, 144],
      '(b) Two moments = inverse quantitative relation, fluctuating on scale. Not determined by indifference (indifference of fluctuation), only externally. Determining appeal to other outside indifference. Absolute as indifference has second defect: determinateness not determined by absolute itself. First defect: differences emerge only in general (immediate, not self-mediation).',
      [
        'two moments',
        'inverse quantitative relation',
        'fluctuating',
        'scale',
        'magnitude',
        'however',
        'determined',
        'indifference',
        'precisely',
        'indifference',
        'fluctuation',
        'only',
        'externally',
        'determining appeal',
        'made',
        'other',
        'lies',
        'outside',
        'indifference',
        'absolute',
        'indifference',
        'respect',
        'second defect',
        'quantitative form',
        'namely',
        'determinateness',
        'difference',
        'determined',
        'absolute itself',
        'just',
        'first defect',
        'differences',
        'emerge',
        'only',
        'general',
        'positing',
        'something',
        'immediate',
        'not',
        'self-mediation',
      ],
      { section: '2. (b)', order: 8 }
    ),

    createTopicMapEntry(
      'be-b-2-c-quantitative-determinateness-subsistence',
      'Quantitative determinateness as subsistence — contradiction',
      [146, 169],
      '(c) Quantitative determinateness = mode of subsistence. Existence withdrawn from transitoriness of quality. But have subsistence of own (differs from quantitative existence) = indifference itself, each = unity of two qualities. Difference restricted: one quality more on one side, less on other (inverse). Each side = totality of indifference. Each quality = same sum, continues without restriction by quantitative limit. Determinations = immediate opposition, develops into contradiction.',
      [
        'quantitative determinateness',
        'moments',
        'now',
        'sides',
        'relation',
        'constitutes',
        'mode',
        'subsistence',
        'existence',
        'virtue',
        'indifference',
        'withdrawn',
        'transitoriness',
        'quality',
        'subsistence',
        'own',
        'themselves',
        'differs',
        'quantitative existence',
        'themselves',
        'indifference itself',
        'each',
        'unity itself',
        'two qualities',
        'qualitative moment',
        'splits',
        'difference',
        'two moments',
        'restricted',
        'fact',
        'one quality',
        'posited',
        'one side',
        'more',
        'other',
        'less',
        'other',
        'posited',
        'inverse order',
        'accordingly',
        'each side',
        'thus',
        'totality',
        'indifference',
        'each',
        'two qualities',
        'taken',
        'singly',
        'itself',
        'likewise',
        'remains',
        'same sum',
        'indifference',
        'continues',
        'one side',
        'other',
        'without',
        'restricted',
        'quantitative limit',
        'thereby',
        'posited',
        'determinations',
        'come',
        'immediate opposition',
        'opposition',
        'develops',
        'contradiction',
        'must',
        'now',
        'see',
      ],
      { section: '2. (c)', order: 9 }
    ),

    createTopicMapEntry(
      'be-b-3-qualitative-connection-equilibrium',
      'Qualitative connection — equilibrium',
      [171, 195],
      'Each quality enters each side in connection with other (supposed quantitative difference). If both self-subsistent, determinateness falls apart, unity/totality empty names. But determined as inseparable unity, meaning/reality only in qualitative connection. Quantitativeness = qualitative nature, each reaches only as far as other. If differ as quanta, one reaches beyond other (indifferent existence). As qualitatively connected, each only insofar as other is. Result = equilibrium: one increases/decreases, other same proportion.',
      [
        'namely',
        'each quality',
        'enters',
        'inside',
        'each side',
        'connection',
        'other',
        'does',
        'manner',
        'determined',
        'connection',
        'also',
        'supposed',
        'only',
        'quantitative difference',
        'two qualities',
        'both',
        'self-subsistent',
        'something',
        'like',
        'sensible materials',
        'independent',
        'each other',
        'whole determinateness',
        'indifference',
        'falls apart',
        'unity',
        'totality',
        'empty names',
        'same time',
        'determined',
        'comprised',
        'one unity',
        'inseparable',
        'each',
        'having',
        'meaning',
        'reality',
        'only',
        'one',
        'qualitative connecting reference',
        'other',
        'now',
        'because',
        'quantitativeness',
        'simply',
        'solely',
        'qualitative nature',
        'each',
        'reaches',
        'only',
        'far',
        'other',
        'assumed',
        'differ',
        'quanta',
        'one',
        'would',
        'reach',
        'beyond',
        'other',
        'would',
        'more',
        'indifferent existence',
        'other',
        'would not',
        'qualitatively connected',
        'however',
        'each',
        'only',
        'far',
        'other',
        'result',
        'equilibrium',
        'extent',
        'one',
        'increases',
        'decreases',
        'other',
        'likewise',
        'increases',
        'decreases',
        'would',
        'same proportion',
      ],
      { section: '3.', order: 10 }
    ),

    createTopicMapEntry(
      'be-b-3-contradiction-essence',
      'Contradiction — essence',
      [197, 229],
      'On basis of qualitative connection: no quantitative difference, no more of one quality. More exceeding other = unstable determination or other itself. In equality, neither there (existence rests on inequality). Each factor vanishes (exceeds or equal). Vanishing = disturbance of equilibrium, one factor greater, other quality sublated, first predominant, other diminishes, becomes self-subsistent factor, no longer two moments but one whole. Unity as totality of determining process, determined as indifference = contradiction all around. Must be posited as self-sublating contradiction, determined as subsistence existing for itself, unity immanently negative and absolute = essence.',
      [
        'basis',
        'therefore',
        'qualitative connection',
        'question',
        'quantitative difference',
        'more',
        'one quality',
        'more',
        'one',
        'two connected moments',
        'would',
        'exceed',
        'other',
        'would',
        'only',
        'unstable determination',
        'would',
        'only',
        'other itself',
        'equality',
        'two',
        'neither',
        'would',
        'there',
        'existence',
        'would',
        'rest',
        'inequality',
        'quantum',
        'each',
        'supposed factors',
        'vanishes',
        'whether',
        'one factor',
        'assumed',
        'exceed',
        'other',
        'equal',
        'standpoint',
        'quantitative representation',
        'vanishing',
        'appears',
        'disturbance',
        'equilibrium',
        'one factor',
        'becoming',
        'greater',
        'other',
        'sublation',
        'quality',
        'other',
        'instability',
        'thus',
        'posited',
        'first factor',
        'becomes',
        'predominant',
        'other',
        'diminishes',
        'accelerated velocity',
        'overcome',
        'turn',
        'constitutes',
        'one self-subsistent factor',
        'however',
        'no longer',
        'two specific moments',
        'factors',
        'only',
        'one whole',
        'unity',
        'thus',
        'posited',
        'totality',
        'process',
        'determining',
        'itself',
        'determined',
        'process',
        'indifference',
        'contradiction',
        'around',
        'must',
        'therefore',
        'posited',
        'self-sublating contradiction',
        'determined',
        'subsistence',
        'existing',
        'itself',
        'one',
        'no longer',
        'merely',
        'indifferent unity',
        'result',
        'unity',
        'immanently',
        'negative',
        'absolute',
        'essence',
      ],
      { section: '3.', order: 11 }
    ),
  ],
  {
    sectionDescription: 'Indifference as Inverse Ratio of Its Factors - Introduction (indifference posited as existing for itself). Section 1: Substrate as one indivisible independent measure, inverse ratio (qualitative determination), two qualities (each side contains both), inverted relation recurs (continuation into each other). Section 2: Indifference as existence (totality), (a) determinacies emerge groundlessly (external), (b) inverse quantitative relation (externally determined), (c) quantitative determinateness as subsistence (contradiction). Section 3: Qualitative connection (equilibrium), contradiction (essence).',
  }
);

