/**
 * TopicMap for transition-essence.txt - Transition into Essence
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - transition-essence-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const TRANSITION_ESSENCE_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/measure/becoming-essence/sources/transition-essence.txt',
  'Hegel\'s Science of Logic - Measure',
  'Transition into Essence',
  [
    createTopicMapEntry(
      'be-c-1-absolute-indifference-final-determination',
      'Absolute indifference as final determination — still belongs to being',
      [3, 27],
      'Absolute indifference = final determination of being before essence, does not attain essence. Still belongs to being (determined as indifferent), difference external/quantitative. Externality = existence, opposition. External reflection: determinations one and same, difference indifferent. Missing: reflection should sublate itself, become determination of difference of unity. Unity = absolute negativity, indifference towards itself and otherness.',
      [
        'absolute indifference',
        'final determination',
        'being',
        'before',
        'latter',
        'becomes',
        'essence',
        'does not',
        'attain',
        'essence',
        'shows',
        'still belongs',
        'sphere',
        'being',
        'because',
        'still',
        'determined',
        'indifferent',
        'therefore',
        'difference',
        'external',
        'quantitative',
        'externality',
        'existence',
        'finds',
        'same time',
        'opposition',
        'determined',
        'over against',
        'existing',
        'itself',
        'thought',
        'absolute',
        'exists',
        'itself',
        'again',
        'external reflection',
        'insists',
        'specific determinations',
        'whether',
        'themselves',
        'absolute',
        'one',
        'same',
        'difference',
        'only',
        'indifferent',
        'difference',
        'itself',
        'still missing',
        'reflection',
        'should',
        'sublate',
        'itself',
        'would',
        'cease',
        'external',
        'reflection',
        'thought',
        'subjective consciousness',
        'rather',
        'determination',
        'difference',
        'unity',
        'unity',
        'would',
        'prove',
        'absolute negativity',
        'unity',
        'indifference',
        'towards',
        'itself',
        'own',
        'indifference',
        'no less',
        'otherness',
      ],
      { section: 'C. TRANSITION INTO ESSENCE', order: 1 }
    ),

    createTopicMapEntry(
      'be-c-2-self-sublation-manifested',
      'Self-sublation manifested — contradiction',
      [29, 57],
      'Self-sublation already manifested. Progressive positing shows contradiction on all sides. Indifference = totality (determinations sublated/contained) = substrate (one-sided being-in-itself). Differences present as external. Contradiction of itself and determinateness (implicit vs posited). Negative totality: determinacies internally sublated, sublated one-sidedness of substrate. Indifference = simple infinitely negative self-reference, incompatibility with itself, repelling from itself. Determining/determined = own referring to itself = negativity of itself, of in-itselfness.',
      [
        'self-sublation',
        'determination',
        'indifference',
        'already',
        'manifested',
        'itself',
        'progressive',
        'positing',
        'being',
        'shown',
        'all sides',
        'contradiction',
        'indifference',
        'itself',
        'totality',
        'determinations',
        'being',
        'sublated',
        'contained',
        'thus',
        'substrate',
        'at first',
        'only',
        'one-sided',
        'determination',
        'being-in-itself',
        'consequently',
        'differences',
        'quantitative difference',
        'inverseratio',
        'factors',
        'present',
        'external',
        'thus',
        'contradiction',
        'itself',
        'determinateness',
        'implicitly',
        'existent',
        'determination',
        'posited',
        'determinateness',
        'negative totality',
        'determinacies',
        'internally',
        'sublated',
        'themselves',
        'consequently',
        'sublated',
        'one-sidedness',
        'substrate',
        'in-itselfness',
        'indifference',
        'now',
        'posited',
        'fact',
        'simple',
        'infinitely',
        'negative',
        'self-reference',
        'incompatibility',
        'itself',
        'repelling',
        'itself',
        'determining',
        'determined',
        'transition',
        'external',
        'alteration',
        'again',
        'emergence',
        'determinations',
        'own',
        'referring',
        'itself',
        'negativity',
        'itself',
        'in-itselfness',
      ],
      { section: 'C. TRANSITION INTO ESSENCE', order: 2 }
    ),

    createTopicMapEntry(
      'be-c-3-determinations-as-moments',
      'Determinations as moments — posited',
      [59, 76],
      'As repelled: determinations not self-possessed, not self-subsistent/external, but as moments. First: belonging to unity (existence implicit), borne as substrate, filled by it alone. Second: immanent to unity existing for itself, only through repulsion from themselves. Instead of existent (sphere of being), now simply as posited, sole determination = referred to unity, each to other and negation, marked by relativity.',
      [
        'repelled',
        'determinations',
        'self-possessed',
        'emerge',
        'self-subsistent',
        'external',
        'rather',
        'moments',
        'first',
        'belonging',
        'unity',
        'existence',
        'still',
        'only',
        'implicit',
        'let go',
        'borne',
        'substrate',
        'filled',
        'alone',
        'second',
        'determinations',
        'immanent',
        'unity',
        'exists',
        'itself',
        'only',
        'through',
        'repulsion',
        'themselves',
        'instead',
        'existent',
        'whole',
        'sphere',
        'being',
        'now',
        'simply',
        'solely',
        'posited',
        'sole',
        'determination',
        'significance',
        'referred',
        'unity',
        'hence',
        'each',
        'other',
        'negation',
        'marked',
        'relativity',
      ],
      { section: 'C. TRANSITION INTO ESSENCE', order: 3 }
    ),

    createTopicMapEntry(
      'be-c-4-being-determined-as-essence',
      'Being determined as essence — simple being with itself',
      [78, 91],
      'Being in general and immediacy of determinacies vanished (as in-itselfness). Unity = being, immediately presupposed totality = simple self-reference (mediated by sublation of presupposition). Pre-supposedness (immediate being) = moment of repelling. Original self-subsistence/self-identity = resulting infinite self-rejoining. Being determined as essence: being which, through sublation of being, is simple being with itself.',
      [
        'being',
        'general',
        'being',
        'immediacy',
        'different determinacies',
        'thereby',
        'vanished',
        'much',
        'in-itselfness',
        'unity',
        'being',
        'immediately',
        'presupposed',
        'totality',
        'only',
        'simple',
        'self-reference',
        'mediated',
        'sublation',
        'presupposition',
        'pre-supposedness',
        'immediate being',
        'itself',
        'only',
        'moment',
        'repelling',
        'original',
        'self-subsistence',
        'self-identity',
        'only',
        'resulting',
        'infinite',
        'self-rejoining',
        'determined',
        'essence',
        'being',
        'through',
        'sublation',
        'being',
        'simple',
        'being',
        'itself',
      ],
      { section: 'C. TRANSITION INTO ESSENCE', order: 4 }
    ),
  ],
  {
    sectionDescription: 'Transition into Essence - Absolute indifference as final determination (still belongs to being, external reflection, absolute negativity). Self-sublation manifested (contradiction, negative totality, infinitely negative self-reference, repelling). Determinations as moments (posited, referred to unity, relativity). Being determined as essence (simple being with itself, completion of Sphere of Being, transition to Sphere of Essence).',
  }
);

