#!/usr/bin/env python3
"""Project Sankara passage records into top-level Logos TypeScript unit stubs.

This keeps JSON passage records as system-of-record while generating a
machine-usable projection for reality/src/logos/sankara.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def load_record(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: root is not an object")
    return data


def find_records(path: Path) -> list[Path]:
    if path.is_file() and path.suffix == ".json":
        return [path]
    if not path.exists():
        return []
    return sorted(p for p in path.rglob("*.json") if p.is_file())


def ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def safe_get(d: dict[str, Any], *keys: str) -> str:
    cur: Any = d
    for key in keys:
        if not isinstance(cur, dict):
            return ""
        cur = cur.get(key)
    if isinstance(cur, str):
        return cur
    return ""


def build_typescript(
    records: list[dict[str, Any]], *, unit_name: str, unit_id: str, lens: str
) -> str:
    chunk_lines: list[str] = []
    hlo_lines: list[str] = []

    for idx, rec in enumerate(records, start=1):
        record_id = safe_get(rec, "record_id") or f"record-{idx:03d}"
        source_text = safe_get(rec, "text", "source_text")
        iast = safe_get(rec, "text", "transliteration_iast").strip()
        literal = safe_get(rec, "translation", "literal_translation")
        technical = safe_get(rec, "translation", "technical_translation")
        seg_note = safe_get(rec, "text", "segmentation_note")
        source_url = safe_get(rec, "source", "source_url")
        source_sha = safe_get(rec, "source", "source_sha256")
        confidence = rec.get("qa", {}).get("confidence") if isinstance(rec.get("qa"), dict) else None

        chunk_id = f"{slug(unit_name)}-chunk-{idx:03d}"
        hlo_id = f"{slug(unit_name)}-hlo-{idx:03d}"

        iast_display = iast if iast else "[IAST pending curation]"
        chunk_source = (
            f"Sanskrit (Devanagari): {source_text}\n"
            f"IAST: {iast_display}\n"
            f"English (literal): {literal}\n"
            f"English (technical): {technical}\n"
            f"Segmentation: {seg_note}"
        ).strip()

        chunk_lines.append(
            "  {\n"
            f"    id: {ts_string(chunk_id)},\n"
            f"    title: {ts_string(record_id)},\n"
            f"    source: {ts_string(chunk_source)},\n"
            "    mode: 'summary',\n"
            "  },"
        )

        clauses: list[str] = [
            f"record_id({record_id})",
            f"source_url({source_url})" if source_url else "source_url(unknown)",
            f"source_sha256({source_sha})" if source_sha else "source_sha256(unknown)",
            f"confidence({confidence})" if isinstance(confidence, (int, float)) else "confidence(unknown)",
            "transliteration_status(present)" if iast else "transliteration_status(missing)",
        ]

        hlo_lines.append(
            "  {\n"
            f"    id: {ts_string(hlo_id)},\n"
            f"    chunkId: {ts_string(chunk_id)},\n"
            f"    label: {ts_string(f'Projection clauses for {record_id}')},\n"
            "    clauses: [\n"
            + "\n".join(f"      {ts_string(c)}," for c in clauses)
            + "\n    ],\n"
            "  },"
        )

    rendered = "\n".join(
        [
            "/*",
            " Auto-generated by ref/sankara/scripts/project_records_to_ys.py.",
            " System-of-record remains Sankara JSON passage records.",
            "*/",
            "",
            f"export const {unit_name}_CHUNKS = [",
            "\n".join(chunk_lines),
            "];",
            "",
            f"export const {unit_name}_HLOS = [",
            "\n".join(hlo_lines),
            "];",
            "",
            f"export const {unit_name}_UNIT = {{",
            f"  id: {ts_string(unit_id)},",
            f"  title: {ts_string(f'{unit_name} projected from Sankara passage records')},",
            "  scope: 'idea',",
            "  logosMode: 'prajna',",
            "  synthesis: 'pre-factum',",
            "  faculty: 'buddhi',",
            f"  lens: {ts_string(lens)},",
            f"  chunks: {unit_name}_CHUNKS,",
            f"  hlos: {unit_name}_HLOS,",
            "};",
            "",
        ]
    )
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description="Project Sankara passage records to top-level Logos TS unit stubs")
    parser.add_argument(
        "--records-path",
        type=Path,
        default=Path("reality/src/logos/sankara/translation/passage_records"),
        help="Path to record JSON file or directory",
    )
    parser.add_argument(
        "--out-file",
        type=Path,
        default=Path("reality/src/logos/sankara/generated/bs_c01_projected.ts"),
        help="TypeScript output file path",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=25,
        help="Max number of records to project",
    )
    parser.add_argument(
        "--unit-name",
        type=str,
        default="BS_C01_PROJECTED",
        help="TypeScript symbol prefix for generated constants",
    )
    parser.add_argument(
        "--unit-id",
        type=str,
        default="bs:c01:projected",
        help="Dataset unit id string for projected unit",
    )
    parser.add_argument(
        "--lens",
        type=str,
        default="sanskrit",
        help="Lens field value for the projected unit",
    )
    args = parser.parse_args()

    files = find_records(args.records_path)
    if not files:
        raise SystemExit(f"no JSON records found at: {args.records_path}")

    records: list[dict[str, Any]] = []
    for p in files:
        rec = load_record(p)
        if not isinstance(rec.get("record_id"), str):
            continue
        records.append(rec)

    records = sorted(records, key=lambda x: str(x.get("record_id")))
    selected = records[: max(0, args.limit)]
    if not selected:
        raise SystemExit("no passage records available after filtering")

    ts = build_typescript(
        selected,
        unit_name=args.unit_name,
        unit_id=args.unit_id,
        lens=args.lens,
    )
    args.out_file.parent.mkdir(parents=True, exist_ok=True)
    args.out_file.write_text(ts, encoding="utf-8")

    print(f"projected {len(selected)} record(s) to {args.out_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
