// Generated by src/relative/core/compiler/generate-actuality-absolute-ir.ts

const topicmapActualityAbsoluteTopicMapSourceSourceExposition = {
  "id": "source-exposition",
  "title": "A. EXPOSITION OF THE ABSOLUTE",
  "sourceFile": "relative/essence/actuality/absolute/sources/exposition.txt",
  "totalLines": 183,
  "chunks": [
    {
      "id": "abs-a-1-absolute-not-being-nor-essence",
      "title": "Absolute not being nor essence — absolute unity",
      "sourceId": "source-exposition",
      "sourceFile": "relative/essence/actuality/absolute/sources/exposition.txt",
      "lineRange": {
        "start": 3,
        "end": 22
      },
      "description": "Absolute not = being (first unreflected immediacy) nor essence (reflected immediacy). Each = determinate totality. Being emerges in essence = concrete existence. Connection develops = relation of inner and outer. Inner = essence (referred to being, being immediately). Outer = being (connected with reflection, relationless identity with essence). Absolute = absolute unity of two, ground of essential relation.",
      "keyPoints": [
        "absolute",
        "being",
        "essence",
        "first unreflected immediacy",
        "reflected immediacy",
        "determinate totality",
        "concrete existence",
        "relation of inner and outer",
        "inner",
        "outer",
        "absolute unity",
        "ground of essential relation"
      ],
      "orderInSource": 1,
      "globalOrder": 1,
      "sourceText": "The absolute is not just being, nor even essence.\nThe former is the first unreflected immediacy;\nthe latter, the reflected immediacy;\nfurther, each is explicitly a totality,\nbut a determinate totality.\nBeing emerges in essence as concrete existence,\nand the connection of being and essence develops\ninto the relation of inner and outer.\nThe inner is essence, but as a totality\nwhose essential determination is\nto be referred to being and to be being immediately.\nThe outer is being, but with the essential determination of\nbeing immediately connected with reflection\nand, equally, in a relationless identity with essence.\nThe absolute itself is the absolute unity of the two;\nit is that which constitutes in general\nthe ground of the essential relation\nwhich, as only relation, has yet\nto return into this its identity\nand whose ground is not yet posited.",
      "tags": [
        "reflection",
        "mediation",
        "absolute"
      ]
    },
    {
      "id": "abs-a-2-absolute-form-and-content",
      "title": "Absolute form and content — each moment totality",
      "sourceId": "source-exposition",
      "sourceFile": "relative/essence/actuality/absolute/sources/exposition.txt",
      "lineRange": {
        "start": 24,
        "end": 37
      },
      "description": "Determination of absolute = absolute form. Not identity with simple determinacies, but identity whose moments = each explicitly totality, indifferent to form = complete content. Conversely, absolute = absolute content (indifferent plurality) with negative connection of form, manifold = one substantial identity.",
      "keyPoints": [
        "determination of absolute",
        "absolute form",
        "simple determinacies",
        "moments as totality",
        "indifferent to form",
        "complete content",
        "absolute content",
        "indifferent plurality",
        "negative connection of form",
        "manifold",
        "one substantial identity"
      ],
      "orderInSource": 2,
      "globalOrder": 2,
      "sourceText": "It follows that the determination of\nthe absolute is to be absolute form,\nbut at the same time not as an identity\nwhose moments only are simple determinacies,\nbut, on the contrary, as an identity\nwhose moments are each explicitly the totality\nand hence, indifferent with respect to the form,\nthe complete content of the whole.\nBut, conversely, the absolute is absolute content\nin such a way that this content,\nwhich is as such indifferent plurality,\nexplicitly has the negative connection of form\nby virtue of which its manifold is\nonly one substantial identity.",
      "tags": [
        "negation",
        "absolute"
      ]
    },
    {
      "id": "abs-a-3-absolute-identity-transparent",
      "title": "Absolute identity — transparent reflective shine",
      "sourceId": "source-exposition",
      "sourceFile": "relative/essence/actuality/absolute/sources/exposition.txt",
      "lineRange": {
        "start": 39,
        "end": 51
      },
      "description": "Identity of absolute = absolute identity because each part = whole, each determinateness = totality. Determinateness = transparent reflective shine, difference disappeared in positedness. Reflected determinations (essence, concrete existence, world, whole, parts, force) appear as true being, but absolute = ground into which they foundered.",
      "keyPoints": [
        "absolute identity",
        "each part = whole",
        "each determinateness = totality",
        "transparent reflective shine",
        "difference disappeared",
        "positedness",
        "reflected determinations",
        "essence",
        "concrete existence",
        "world existing in itself",
        "whole",
        "parts",
        "force",
        "ground",
        "foundered"
      ],
      "orderInSource": 3,
      "globalOrder": 3,
      "sourceText": "Thus the identity of the absolute is\nfor this reason absolute identity,\nbecause each of its parts is itself the whole\nor each determinateness is the totality, that is,\nbecause determinateness has become as such\na thoroughly transparent reflective shine,\na difference that has disappeared in its positedness.\nEssence, concrete existence, the world existing in itself,\nwhole, parts, force:\nthese reflected determinations appear to representation\nas true being valid in and for itself;\nbut against them the absolute is the ground\ninto which they have foundered.",
      "tags": [
        "reflection",
        "absolute"
      ]
    },
    {
      "id": "abs-a-4-absolute-does-not-determine",
      "title": "Absolute does not determine itself — movement stands over",
      "sourceId": "source-exposition",
      "sourceFile": "relative/essence/actuality/absolute/sources/exposition.txt",
      "lineRange": {
        "start": 52,
        "end": 75
      },
      "description": "In absolute: form = simple self-identity, absolute does not determine itself (determination = difference of form). But absolute contains every difference/form determination = absolute form and reflection, difference of content must come into it. Absolute = absolute identity (manifoldness sublated). No becoming, not being; not reflective determination, not essence; not externalization, identity of inner/outer. Movement of reflection stands over against absolute identity, sublated = inner, consequently outer.",
      "keyPoints": [
        "simple self-identity",
        "does not determine itself",
        "difference of form",
        "contains every difference",
        "form determination",
        "absolute form and reflection",
        "difference of content",
        "absolute identity",
        "manifoldness sublated",
        "no becoming",
        "not being",
        "not essence",
        "not externalization",
        "identity of inner and outer",
        "movement of reflection",
        "stands over against",
        "sublated",
        "inner",
        "outer"
      ],
      "orderInSource": 4,
      "globalOrder": 4,
      "sourceText": "Because in the absolute the form is\nnow only simple self-identity,\nthe absolute does not determine itself,\nfor the determination is a difference of form\nwhich is valid as such from the start.\nBut because the absolute at the same time contains\nevery difference and form determination in general,\nor because it is itself absolute form and reflection,\nthe difference of content must also come into it.\nBut the absolute itself is the absolute identity;\nto be this identity is its determination,\nfor the manifoldness of the world-in-itself\nand of the phenomenal world has all been sublated in it.\nIn the absolute itself there is no becoming,\nsince the absolute is not being;\nnor does the absolute determine itself reflectively,\nfor it is not the essence which determines itself only inwardly;\nand it also does not externalize itself,\nfor it is the identity of inner and outer.\nBut in this way the movement of reflection\nstands over against its absolute identity.\nThe movement is sublated in this identity\nand is thus only its inner;\nbut consequently its outer.",
      "tags": [
        "sublation",
        "reflection",
        "absolute"
      ]
    },
    {
      "id": "abs-a-5-negative-exposition",
      "title": "Negative exposition — beyond of differences",
      "sourceId": "source-exposition",
      "sourceFile": "relative/essence/actuality/absolute/sources/exposition.txt",
      "lineRange": {
        "start": 77,
        "end": 96
      },
      "description": "Movement = sublating its act in absolute. Beyond of manifold differences/determinations/movement, beyond at back of absolute = negative exposition. True presentation = preceding whole of logical movement (being and essence). Content not gathered from outside, not sunk by external reflection, but determined itself by inner necessity. Being's own becoming and reflection of essence returned into absolute as ground.",
      "keyPoints": [
        "movement",
        "sublating act in absolute",
        "beyond of differences",
        "beyond of determinations",
        "beyond at back of absolute",
        "negative exposition",
        "preceding whole",
        "logical movement",
        "being",
        "essence",
        "not gathered from outside",
        "not sunk by external reflection",
        "determined by inner necessity",
        "being's own becoming",
        "reflection of essence",
        "returned into absolute",
        "ground"
      ],
      "orderInSource": 5,
      "globalOrder": 5,
      "sourceText": "At first, therefore, the movement consists only\nin sublating its act in the absolute.\nIt is the beyond of the manifold differences\nand determinations and of their movement,\na beyond that lies at the back of the absolute.\nIt is thus the negative exposition of the absolute\nearlier alluded to.\nIn its true presentation, this exposition is\nthe preceding whole of the logical movement\nof the spheres of being and essence,\nthe content of which has not been gathered in\nfrom outside as something given and contingent;\nnor has it been sunk into the abyss of the absolute\nby a reflection external to it;\non the contrary, it has determined itself within it\nby virtue of its inner necessity,\nand, as being's own becoming\nand as the reflection of essence,\nhas returned into the absolute\nas into its ground.",
      "tags": [
        "negation",
        "sublation",
        "reflection",
        "absolute"
      ]
    },
    {
      "id": "abs-a-6-positive-exposition",
      "title": "Positive exposition — finite as expression of absolute",
      "sourceId": "source-exposition",
      "sourceFile": "relative/essence/actuality/absolute/sources/exposition.txt",
      "lineRange": {
        "start": 98,
        "end": 124
      },
      "description": "Exposition has positive side: finite foundering demonstrates nature = referred to absolute, contains absolute. But = exposition of determinations (absolute = abyss and ground, imparts subsistence to reflective shine). Being as shine = reflection, reference to absolute. Positive exposition halts finite before disappearing, considers it expression/copy of absolute. Transparency lets absolute transpire, ends in complete disappearance (nothing retains difference, absorbed as medium).",
      "keyPoints": [
        "positive exposition",
        "positive side",
        "finite",
        "foundering",
        "referred to absolute",
        "contains absolute",
        "exposition of determinations",
        "abyss",
        "ground",
        "imparts subsistence",
        "reflective shine",
        "being as shine",
        "reflection",
        "reference to absolute",
        "halts finite",
        "expression",
        "copy",
        "transparency",
        "complete disappearance",
        "absorbed as medium"
      ],
      "orderInSource": 6,
      "globalOrder": 6,
      "sourceText": "But this exposition has itself also a positive side,\nfor in foundering to the ground the finite demonstrates\nthat its nature is to be referred to the absolute,\nor to contain the absolute within.\nHowever, this side is not as much\nthe positive exposition of the absolute\nas it is rather the exposition of the determinations,\nnamely that these have the absolute for their abyss,\nbut also for their ground,\nor that that which imparts subsistence to them,\nto their reflective shine, is the absolute itself.\nBeing as shine is not nothing but reflection,\nreference to the absolute;\nor it is a shine inasmuch as\nthat which shines in it is the absolute.\nThis positive exposition thus halts the finite\njust before its disappearing:\nit considers it an expression and\na copy of the absolute.\nBut this transparency of the finite\nthat lets only the absolute transpire through it\nends up in complete disappearance,\nfor there is nothing in the finite\nwhich would retain for it a difference\nover against the absolute;\nas a medium, it is absorbed by\nthat through which it shines.",
      "tags": [
        "reflection",
        "absolute"
      ]
    },
    {
      "id": "abs-a-7-positive-exposition-reflective-shine",
      "title": "Positive exposition as reflective shine — absolute's own doing",
      "sourceId": "source-exposition",
      "sourceFile": "relative/essence/actuality/absolute/sources/exposition.txt",
      "lineRange": {
        "start": 126,
        "end": 167
      },
      "description": "Positive exposition = reflective shine. True positive = absolute itself (contains exposition and content). Form in which absolute shines = nullity gathered from outside, starting point. Determination has in absolute not beginning but end. Expository process = absolute act (returns to absolute) but not at starting point (external determination). But in fact: exposition = absolute's own doing, begins from itself, arrives at itself. Absolute as absolute identity = determined guise, posited by reflection over against opposition/manifoldness, negative of reflection/determination. Not just exposition incomplete but absolute itself incomplete. Absolute as absolute identity = absolute of external reflection, not absolutely absolute but absolute in determination = attribute.",
      "keyPoints": [
        "positive exposition",
        "reflective shine",
        "true positive",
        "absolute itself",
        "nullity",
        "gathered from outside",
        "starting point",
        "determination",
        "beginning",
        "end",
        "expository process",
        "absolute act",
        "returns to absolute",
        "external determination",
        "absolute's own doing",
        "begins from itself",
        "arrives at itself",
        "absolute identity",
        "determined guise",
        "identical absolute",
        "posited by reflection",
        "opposition",
        "manifoldness",
        "negative of reflection",
        "negative of determination",
        "incomplete",
        "absolute of external reflection",
        "absolutely absolute",
        "absolute in determination",
        "attribute"
      ],
      "orderInSource": 7,
      "globalOrder": 7,
      "sourceText": "This positive exposition of the absolute is\ntherefore itself only a reflective shine,\nfor the true positive, that which contains\nthe exposition and the expounded content,\nis the absolute itself.\nWhatever the further determinations that may occur,\nthe form in which the absolute reflectively shines is\na nullity which the exposition gathers up from outside\nand in which it gains for itself\na starting point for its activity.\nAny such determination has in the absolute,\nnot its beginning but its end.\nThis expository process, therefore,\nthough it is an absolute act\nbecause of its reference to\nthe absolute into which it returns,\nis not so at its starting point\nwhich is a determination\nexternal to the absolute.\n\nBut in actual fact\nthe exposition of the absolute\nis the absolute's own doing,\nan act that begins from itself\nand arrives at itself.\nThe absolute, only as absolute identity,\nis absolute in a determined guise,\nthat is, as identical absolute;\nit is posited as such by reflection\nover against opposition and manifoldness;\nor it is only the negative of\nreflection and determination in general.\nIt is not just the exposition of the absolute\nwhich is therefore something incomplete,\nbut this absolute itself\nwhich is only arrived at.\nOr again, the absolute\nwhich is only as absolute identity\nis only the absolute of an external reflection.\nIt is, therefore, not the absolutely absolute\nbut the absolute in a determination,\nor it is attribute.",
      "tags": [
        "negation",
        "reflection",
        "absolute",
        "attribute"
      ]
    },
    {
      "id": "abs-a-8-absolute-as-attribute",
      "title": "Absolute as attribute — absolute form",
      "sourceId": "source-exposition",
      "sourceFile": "relative/essence/actuality/absolute/sources/exposition.txt",
      "lineRange": {
        "start": 169,
        "end": 181
      },
      "description": "Absolute not attribute just because subject matter of external reflection. Reflection not only external but immediately internal (because external). Absolute absolute only because not abstract identity but identity of being and essence (inner and outer). Absolute = absolute form that makes it shine within itself and determines as attribute.",
      "keyPoints": [
        "attribute",
        "subject matter",
        "external reflection",
        "immediately internal",
        "abstract identity",
        "identity of being and essence",
        "identity of inner and outer",
        "absolute form",
        "reflectively shine",
        "within itself",
        "determines as attribute"
      ],
      "orderInSource": 8,
      "globalOrder": 8,
      "sourceText": "But the absolute is not attribute just because\nit is the subject matter of an external reflection\nand is consequently something determined by it.\nOr, reflection is not only external to it;\nbut, precisely because it is external to it,\nit is immediately internal to it.\nThe absolute is absolute only because\nit is not abstract identity\nbut is the identity of being and essence,\nor the identity of the inner and the outer.\nIt is therefore itself the absolute form\nthat makes it reflectively shine within itself\nand determines it as attribute.",
      "tags": [
        "reflection",
        "mediation",
        "absolute",
        "attribute"
      ]
    }
  ]
} as const;
const topicmapActualityAbsoluteTopicMapSourceSourceAttribute = {
  "id": "source-attribute",
  "title": "B. THE ABSOLUTE ATTRIBUTE",
  "sourceFile": "relative/essence/actuality/absolute/sources/attribute.txt",
  "totalLines": 98,
  "chunks": [
    {
      "id": "abs-b-1-absolute-absolute-vs-attribute",
      "title": "Absolute absolute vs attribute — relative absolute",
      "sourceId": "source-attribute",
      "sourceFile": "relative/essence/actuality/absolute/sources/attribute.txt",
      "lineRange": {
        "start": 3,
        "end": 20
      },
      "description": "\"Absolute absolute\" = absolute whose form returned into itself, form = content. Attribute = relative absolute, absolute in form determination. Form at first = internally/externally, determinate form/negation. But form = form of absolute, attribute = whole content, totality (world, side of essential relation, each = whole).",
      "keyPoints": [
        "absolute absolute",
        "form returned into itself",
        "form equals content",
        "attribute",
        "relative absolute",
        "form determination",
        "internally",
        "externally",
        "determinate form",
        "negation",
        "form of absolute",
        "whole content",
        "totality",
        "world",
        "side of essential relation",
        "each is whole"
      ],
      "orderInSource": 1,
      "globalOrder": 9,
      "sourceText": "The expression which we have used, \"the absolute absolute,\"\ndenotes the absolute which in its form\nhas returned back into itself\nor whose form is equal to its content.\nThe attribute is just the relative absolute,\na combination which only signifies the absolute\nin a form determination.\nFor at first, before its complete exposition,\nthe form is only internally\nor, which is the same, only externally;\nit is at first determinate form in general\nor negation in general.\nBut because form is at the same time\nas the form of the absolute,\nthe attribute is the whole content of the absolute;\nit is the totality which earlier appeared as a world,\nor as one of the sides of the essential relation,\neach of which is itself the whole.",
      "tags": [
        "negation",
        "absolute",
        "attribute"
      ]
    },
    {
      "id": "abs-b-2-worlds-reduced-to-shine",
      "title": "Worlds reduced to reflective shine — true subsistence",
      "sourceId": "source-attribute",
      "sourceFile": "relative/essence/actuality/absolute/sources/attribute.txt",
      "lineRange": {
        "start": 21,
        "end": 42
      },
      "description": "Both worlds opposed in essence. Each side equal to other (whole/parts, expression/force, outer/inner). But each had immediate subsistence (existent immediacy, reflected immediacy). In absolute: different immediacies reduced to reflective shine. Totality (attribute) = true single subsistence, determination = unessential subsistence.",
      "keyPoints": [
        "phenomenal world",
        "world in and for itself",
        "opposed in essence",
        "each side equal",
        "whole",
        "parts",
        "expression of force",
        "force",
        "outer",
        "inner",
        "immediate subsistence",
        "existent immediacy",
        "reflected immediacy",
        "reduced to reflective shine",
        "true single subsistence",
        "unessential subsistence"
      ],
      "orderInSource": 2,
      "globalOrder": 10,
      "sourceText": "But both worlds, the phenomenal world\nand the world that exists in and for itself,\nwere supposed to be opposed\nto each other in their essence.\nEach side of the essential relation was\nindeed equal to the other:\nthe whole as much as the parts,\nthe expression of force the same content\nas force itself,\nand the outer everywhere the same as the inner.\nBut these sides were at the same time\nsupposed each to have still\nan immediate subsistence of its own,\nthe one side as existent immediacy\nand the other as reflected immediacy.\nIn the absolute, on the contrary,\nthese different immediacies have been\nreduced to a reflective shine,\nand the totality that the attribute is\nis posited as its true and single subsistence,\nwhile the determination in which it is\nis posited as unessential subsistence.",
      "tags": [
        "reflection",
        "mediation",
        "absolute",
        "attribute"
      ]
    },
    {
      "id": "abs-b-3-attribute-as-identity-determination",
      "title": "Attribute as identity determination — absolute totality",
      "sourceId": "source-attribute",
      "sourceFile": "relative/essence/actuality/absolute/sources/attribute.txt",
      "lineRange": {
        "start": 44,
        "end": 60
      },
      "description": "Absolute = attribute because simple absolute identity in determination of identity. Other determinations can be attached (several attributes). But absolute identity = all determinations sublated, reflection sublated itself, determinations posited as sublated. Totality = absolute totality. Attribute has absolute for content/subsistence, form determination posited as mere reflective shine, negative posited as negative.",
      "keyPoints": [
        "absolute",
        "attribute",
        "simple absolute identity",
        "determination of identity",
        "other determinations",
        "several attributes",
        "all determinations sublated",
        "reflection sublated itself",
        "determinations posited as sublated",
        "absolute totality",
        "content",
        "subsistence",
        "form determination",
        "mere reflective shine",
        "negative posited as negative"
      ],
      "orderInSource": 3,
      "globalOrder": 11,
      "sourceText": "The absolute is attribute because,\nas simple absolute identity,\nit is in the determination of identity;\nnow to the determination as such\nother determinations can be attached,\nfor instance, also that there are several attributes.\nBut because absolute identity has only this meaning,\nthat not only all determinations have been sublated\nbut that reflection itself has also sublated itself,\nall determinations are thus posited in it as sublated.\nOr the totality is posited as absolute totality.\nOr again, the attribute has the absolute\nfor its content and subsistence\nand, consequently, its form determination\nby which it is attribute is also posited,\nposited immediately as mere reflective shine;\nthe negative is posited as negative.",
      "tags": [
        "negation",
        "sublation",
        "reflection",
        "absolute",
        "attribute"
      ]
    },
    {
      "id": "abs-b-4-positive-reflective-shine-sublates",
      "title": "Positive reflective shine sublates attribute",
      "sourceId": "source-attribute",
      "sourceFile": "relative/essence/actuality/absolute/sources/attribute.txt",
      "lineRange": {
        "start": 61,
        "end": 69
      },
      "description": "Positive reflective shine (exposition through attribute): does not take finite in limitation as existing in and for itself, dissolves subsistence into absolute, expands into attribute. Sublates that attribute is attribute, sinks it and differentiating act into simple absolute.",
      "keyPoints": [
        "positive reflective shine",
        "exposition",
        "attribute",
        "finite",
        "limitation",
        "existing in and for itself",
        "dissolves subsistence",
        "absolute",
        "expands into attribute",
        "sublates",
        "attribute is attribute",
        "differentiating act",
        "simple absolute"
      ],
      "orderInSource": 4,
      "globalOrder": 12,
      "sourceText": "The positive reflective shine that\nthe exposition gives itself through the attribute\nin that it does not take the finite in its limitation as\nsomething that exists in and for itself\nbut dissolves its subsistence into the absolute\nand expands it into attribute;\nsublates precisely this, that the attribute is attribute;\nit sinks it and its differentiating act\ninto the simple absolute.",
      "tags": [
        "sublation",
        "reflection",
        "absolute",
        "attribute"
      ]
    },
    {
      "id": "abs-b-5-reflection-reverts-to-identity",
      "title": "Reflection reverts to identity — not true absolute",
      "sourceId": "source-attribute",
      "sourceFile": "relative/essence/actuality/absolute/sources/attribute.txt",
      "lineRange": {
        "start": 71,
        "end": 89
      },
      "description": "Reflection reverts from differentiating act only to identity of absolute, has not left externality behind, not arrived at true absolute. Only reached indeterminate abstract identity (identity in determinateness of identity). Reflection determines absolute into attribute as inner form, determining distinct from externality, inner determination does not penetrate, attribute's expression (merely posited) to disappear into absolute.",
      "keyPoints": [
        "reflection",
        "reverts",
        "differentiating act",
        "identity of absolute",
        "externality",
        "true absolute",
        "indeterminate abstract identity",
        "identity in determinateness",
        "determines absolute",
        "inner form",
        "distinct from externality",
        "inner determination",
        "does not penetrate",
        "attribute's expression",
        "merely posited",
        "disappear into absolute"
      ],
      "orderInSource": 5,
      "globalOrder": 13,
      "sourceText": "But since reflection thus reverts\nfrom its differentiating act\nonly to the identity of the absolute,\nit has not at the same time\nleft its externality behind\nand has not arrived at the true absolute.\nIt has only reached the\nindeterminate, abstract identity,\nwhich is to say, the identity\nin the determinateness of identity.\nOr, since reflection determines the\nabsolute into attribute as inner form,\nthis determining is something\nstill distinct from externality;\nthe inner determination does not\npenetrate the absolute;\nthe attribute's expression,\nas something merely posited,\nis to disappear into the absolute.",
      "tags": [
        "reflection",
        "absolute",
        "attribute"
      ]
    },
    {
      "id": "abs-b-6-form-nullity",
      "title": "Form as nullity — external reflective shine",
      "sourceId": "source-attribute",
      "sourceFile": "relative/essence/actuality/absolute/sources/attribute.txt",
      "lineRange": {
        "start": 91,
        "end": 96
      },
      "description": "Form by which absolute would be attribute (outer or inner) = null in itself, external reflective shine, mere way and manner.",
      "keyPoints": [
        "form",
        "absolute",
        "attribute",
        "outer",
        "inner",
        "null in itself",
        "external reflective shine",
        "mere way and manner"
      ],
      "orderInSource": 6,
      "globalOrder": 14,
      "sourceText": "The form by virtue of which\nthe absolute would be attribute,\nwhether it is taken as outer or inner,\nis therefore posited as something null in itself,\nan external reflective shine,\nor a mere way and manner.",
      "tags": [
        "reflection",
        "absolute",
        "attribute"
      ]
    }
  ]
} as const;
const topicmapActualityAbsoluteTopicMapSourceSourceMode = {
  "id": "source-mode",
  "title": "C. THE MODE OF THE ABSOLUTE",
  "sourceFile": "relative/essence/actuality/absolute/sources/mode.txt",
  "totalLines": 116,
  "chunks": [
    {
      "id": "abs-c-1-attribute-two-sides",
      "title": "Attribute two sides — extremes and middle term",
      "sourceId": "source-mode",
      "sourceFile": "relative/essence/actuality/absolute/sources/mode.txt",
      "lineRange": {
        "start": 3,
        "end": 23
      },
      "description": "Attribute first = absolute in simple self-identity. Second = negation (formal immanent reflection). Two sides = two extremes, middle term = attribute itself (absolute and determinateness). Second extreme = negative as negative, reflection external to absolute. Negative as inner, determination = posit itself as mode = self-externality of absolute, loss in changeability/contingency, passed over into opposite without turning back, manifoldness lacking totality.",
      "keyPoints": [
        "attribute",
        "absolute in simple self-identity",
        "negation",
        "formal immanent reflection",
        "two sides",
        "two extremes",
        "middle term",
        "absolute",
        "determinateness",
        "negative as negative",
        "reflection external to absolute",
        "inner",
        "posit itself as mode",
        "self-externality",
        "loss",
        "changeability",
        "contingency",
        "passed over into opposite",
        "without turning back",
        "manifoldness",
        "lacks totality"
      ],
      "orderInSource": 1,
      "globalOrder": 15,
      "sourceText": "The attribute is first\nthe absolute in simple self-identity.\nSecond, it is negation,\na negation which is as such\nformal immanent reflection.\nThese two sides constitute at first\nthe two extremes of the attribute,\nthe middle term of which is the attribute itself,\nsince it is both the absolute and the determinateness.\nThe second of these extremes is the negative as negative,\nthe reflection external to the absolute.\nOr inasmuch as the negative is\ntaken as the inner of the absolute\nand its own determination is to posit itself as mode,\nit is then the self-externality of the absolute,\nthe loss of itself in the\nchangeability and contingency of being,\nits having passed over into its opposite\nwithout turning back into itself,\nthe manifoldness of form and content\ndeterminations that lacks totality.",
      "tags": [
        "negation",
        "reflection",
        "absolute",
        "attribute",
        "mode"
      ]
    },
    {
      "id": "abs-c-2-mode-externality-posited",
      "title": "Mode as externality posited — self-identity",
      "sourceId": "source-mode",
      "sourceFile": "relative/essence/actuality/absolute/sources/mode.txt",
      "lineRange": {
        "start": 25,
        "end": 35
      },
      "description": "Mode (externality of absolute) not just self-externality. Rather = externality posited as externality, mere way and manner, reflective shine as reflective shine, reflection of form into itself = self-identity (absolute). Absolute first posited as absolute identity only in mode. Self-identity only as self-referring negativity, reflective shining posited as reflective shining.",
      "keyPoints": [
        "mode",
        "externality of absolute",
        "self-externality",
        "externality posited as externality",
        "mere way and manner",
        "reflective shine as reflective shine",
        "reflection of form into itself",
        "self-identity",
        "absolute",
        "absolute identity",
        "self-referring negativity",
        "reflective shining",
        "posited as reflective shining"
      ],
      "orderInSource": 2,
      "globalOrder": 16,
      "sourceText": "But the mode, the externality of the absolute, is not just this.\nIt is rather externality posited as externality,\na mere way and manner,\nhence the reflective shine as reflective shine,\nor the reflection of form into itself;\nhence, the self-identity which is the absolute.\nIn actual fact, therefore, the absolute is first posited\nas absolute identity only in the mode;\nit is what it is, namely self-identity,\nonly as self-referring negativity,\nas reflective shining which is posited as reflective shining.",
      "tags": [
        "reflection",
        "absolute",
        "mode"
      ]
    },
    {
      "id": "abs-c-3-exposition-exhaustive",
      "title": "Exposition exhaustive — three moments",
      "sourceId": "source-mode",
      "sourceFile": "relative/essence/actuality/absolute/sources/mode.txt",
      "lineRange": {
        "start": 37,
        "end": 41
      },
      "description": "Exposition begins from absolute identity, passes to attribute, then to mode = exhaustively run through moments.",
      "keyPoints": [
        "exposition",
        "absolute identity",
        "attribute",
        "mode",
        "exhaustively run through",
        "moments"
      ],
      "orderInSource": 3,
      "globalOrder": 17,
      "sourceText": "Hence, in so far as the exposition of the absolute\nbegins from its absolute identity\nand passes over to the attribute\nand from there to the mode,\nit has therein exhaustively run through its moments.",
      "tags": [
        "absolute",
        "attribute",
        "mode"
      ]
    },
    {
      "id": "abs-c-4-reflective-movement",
      "title": "Reflective movement — absolute identity",
      "sourceId": "source-mode",
      "sourceFile": "relative/essence/actuality/absolute/sources/mode.txt",
      "lineRange": {
        "start": 43,
        "end": 47
      },
      "description": "First: course not just behaves negatively, act = reflective movement itself. Absolute truly absolute identity only as such movement.",
      "keyPoints": [
        "first",
        "course",
        "behaves negatively",
        "act",
        "reflective movement",
        "absolute truly absolute identity",
        "such movement"
      ],
      "orderInSource": 4,
      "globalOrder": 18,
      "sourceText": "But first, in this course it does not just behave\nnegatively towards these determinations;\nits act is rather the reflective movement itself,\nand it is only as such a movement that\nthe absolute truly is absolute identity.",
      "tags": [
        "negation",
        "reflection",
        "absolute"
      ]
    },
    {
      "id": "abs-c-5-mode-immanent-turning-back",
      "title": "Mode as immanent turning back — absolute being",
      "sourceId": "source-mode",
      "sourceFile": "relative/essence/actuality/absolute/sources/mode.txt",
      "lineRange": {
        "start": 49,
        "end": 54
      },
      "description": "Second: exposition not mere externality, mode not only most external externality. Mode = reflective shine as shine = immanent turning back, self-dissolving reflection. In being this reflection, absolute = absolute being.",
      "keyPoints": [
        "second",
        "exposition",
        "mere externality",
        "most external externality",
        "mode",
        "reflective shine as shine",
        "immanent turning back",
        "self-dissolving reflection",
        "absolute being"
      ],
      "orderInSource": 5,
      "globalOrder": 19,
      "sourceText": "Second, the exposition does not thereby deal with mere externality,\nand the mode is not only the most external externality.\nRather, since the mode is reflective shine as shine,\nit is an immanent turning back, the self-dissolving reflection,\nand it is in being this reflection that\nthe absolute is absolute being.",
      "tags": [
        "reflection",
        "absolute",
        "mode"
      ]
    },
    {
      "id": "abs-c-6-determinateness-from-absolute",
      "title": "Determinateness from absolute itself — absolute form",
      "sourceId": "source-mode",
      "sourceFile": "relative/essence/actuality/absolute/sources/mode.txt",
      "lineRange": {
        "start": 56,
        "end": 74
      },
      "description": "Third: reflective act seems to begin from own determinations/external, take up modes/determinations as if outside absolute, reduce to undifferentiated identity. But found determinateness in absolute itself. As first undifferentiated identity, absolute = determinate absolute/attribute (unmoved, unreflected). Determinateness belongs to reflective movement. Through movement alone: absolute determined as first identity, has absolute form, posits itself as self-equal.",
      "keyPoints": [
        "third",
        "reflective act",
        "own determinations",
        "external",
        "modes",
        "determinations",
        "outside absolute",
        "reduce to undifferentiated identity",
        "determinateness",
        "absolute itself",
        "first undifferentiated identity",
        "determinate absolute",
        "attribute",
        "unmoved",
        "unreflected",
        "reflective movement",
        "first identity",
        "absolute form",
        "posits itself as self-equal"
      ],
      "orderInSource": 6,
      "globalOrder": 20,
      "sourceText": "Third, the reflective act of exposition seems to begin\nfrom its own determinations and from something external,\nto take up the modes or even the determinations of the attribute\nas if they were found outside the absolute\nand its contribution were only to reduce them\nto undifferentiated identity.\nBut it has in fact found the determinateness\nfrom which it begins in the absolute itself.\nFor as first undifferentiated identity,\nthe absolute is itself only the determinate absolute,\nor attribute, because it is the unmoved,\nstill unreflected absolute.\nThis determinateness, since it is determinateness,\nbelongs to the reflective movement,\nand it is through this movement alone\nthat the absolute is determined as the first identity;\nthrough it alone that it has absolute form\nand does not just exist as self-equal\nbut posits itself as self-equal.",
      "tags": [
        "reflection",
        "absolute",
        "attribute",
        "mode"
      ]
    },
    {
      "id": "abs-c-7-true-meaning-of-mode",
      "title": "True meaning of mode — absolute's own reflective movement",
      "sourceId": "source-mode",
      "sourceFile": "relative/essence/actuality/absolute/sources/mode.txt",
      "lineRange": {
        "start": 76,
        "end": 88
      },
      "description": "True meaning of mode = absolute's own reflective movement. Determining by which absolute becomes what it already is (not other). Transparent externality pointing to itself. Movement out of itself, being outwardly = inwardness, positing = absolute being (not mere positedness).",
      "keyPoints": [
        "true meaning of mode",
        "absolute's own reflective movement",
        "determining",
        "becomes what it already is",
        "not other",
        "transparent externality",
        "pointing to itself",
        "movement out of itself",
        "being outwardly",
        "inwardness",
        "positing",
        "absolute being",
        "not mere positedness"
      ],
      "orderInSource": 7,
      "globalOrder": 21,
      "sourceText": "Accordingly the true meaning of mode is that\nit is the absolute's own reflective movement;\nit is a determining by virtue of which\nthe absolute would become, not an other,\nbut what it already is;\na transparent externality\nwhich is a pointing to itself;\na movement out of itself,\nbut in such a way that being outwardly is\njust as much inwardness,\nand consequently equally a positing\nwhich is not mere positedness\nbut absolute being.",
      "tags": [
        "reflection",
        "absolute",
        "mode"
      ]
    },
    {
      "id": "abs-c-8-content-of-exposition",
      "title": "Content of exposition — absolute manifests itself",
      "sourceId": "source-mode",
      "sourceFile": "relative/essence/actuality/absolute/sources/mode.txt",
      "lineRange": {
        "start": 90,
        "end": 104
      },
      "description": "Content of exposition = what absolute manifests. Distinction of form and content dissolved. Content = absolute manifests itself. Absolute = absolute form, in diremption utterly identical with itself, negative as negative rejoining itself = absolute self-identity, indifferent towards distinctions = absolute content. Content = exposition itself.",
      "keyPoints": [
        "content of exposition",
        "what absolute manifests",
        "distinction of form and content",
        "dissolved",
        "absolute manifests itself",
        "absolute form",
        "diremption",
        "utterly identical with itself",
        "negative as negative",
        "rejoining itself",
        "absolute self-identity",
        "indifferent towards distinctions",
        "absolute content",
        "exposition itself"
      ],
      "orderInSource": 8,
      "globalOrder": 22,
      "sourceText": "When therefore one asks for a content of the exposition,\nfor what the absolute manifests,\nthe reply is that the distinction of form and content\nin the absolute has been dissolved;\nor that just this is the content of the absolute,\nthat it manifests itself.\nThe absolute is the absolute form\nwhich in its diremption of itself is\nutterly identical with itself,\nis the negative as negative\nor the negative that rejoins itself\nand in this way alone is the absolute self-identity\nwhich equally is indifferent towards its distinctions\nor is absolute content.\nThe content is therefore only this exposition itself.",
      "tags": [
        "negation",
        "absolute"
      ]
    },
    {
      "id": "abs-c-9-absolute-as-actuality",
      "title": "Absolute as actuality — absolute manifestation",
      "sourceId": "source-mode",
      "sourceFile": "relative/essence/actuality/absolute/sources/mode.txt",
      "lineRange": {
        "start": 106,
        "end": 114
      },
      "description": "As self-bearing movement of exposition, way and manner = absolute identity with itself, absolute = expression (not of inner, not over against other) = absolute manifestation of itself for itself = actuality.",
      "keyPoints": [
        "self-bearing movement",
        "exposition",
        "way and manner",
        "absolute identity with itself",
        "expression",
        "not of inner",
        "not over against other",
        "absolute manifestation",
        "itself for itself",
        "actuality"
      ],
      "orderInSource": 9,
      "globalOrder": 23,
      "sourceText": "As this self-bearing movement of exposition,\nas a way and manner which is\nits absolute identity with itself,\nthe absolute is expression,\nnot of an inner,\nnor over against an other,\nbut simply as absolute manifestation\nof itself for itself.\nThus it is actuality.",
      "tags": [
        "absolute",
        "actuality"
      ]
    }
  ]
} as const;

const topicmapActualityAbsoluteTopicMapSources = [
  topicmapActualityAbsoluteTopicMapSourceSourceExposition,
  topicmapActualityAbsoluteTopicMapSourceSourceAttribute,
  topicmapActualityAbsoluteTopicMapSourceSourceMode,
] as const;

const topicmapActualityAbsoluteTopicMapTraces = [
  {
    "fromChunkId": "abs-a-1-absolute-not-being-nor-essence",
    "toChunkId": "abs-a-2-absolute-form-and-content",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-a-1-absolute-not-being-nor-essence",
    "toChunkId": "abs-a-2-absolute-form-and-content",
    "type": "NEGATES",
    "reason": "Dialectical transition inferred from abs-a-2-absolute-form-and-content semantics."
  },
  {
    "fromChunkId": "abs-a-2-absolute-form-and-content",
    "toChunkId": "abs-a-3-absolute-identity-transparent",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-a-2-absolute-form-and-content",
    "toChunkId": "abs-a-3-absolute-identity-transparent",
    "type": "REFLECTS",
    "reason": "Dialectical transition inferred from abs-a-3-absolute-identity-transparent semantics."
  },
  {
    "fromChunkId": "abs-a-3-absolute-identity-transparent",
    "toChunkId": "abs-a-4-absolute-does-not-determine",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-a-3-absolute-identity-transparent",
    "toChunkId": "abs-a-4-absolute-does-not-determine",
    "type": "SUBLATES",
    "reason": "Dialectical transition inferred from abs-a-4-absolute-does-not-determine semantics."
  },
  {
    "fromChunkId": "abs-a-4-absolute-does-not-determine",
    "toChunkId": "abs-a-5-negative-exposition",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-a-4-absolute-does-not-determine",
    "toChunkId": "abs-a-5-negative-exposition",
    "type": "NEGATES",
    "reason": "Dialectical transition inferred from abs-a-5-negative-exposition semantics."
  },
  {
    "fromChunkId": "abs-a-5-negative-exposition",
    "toChunkId": "abs-a-6-positive-exposition",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-a-5-negative-exposition",
    "toChunkId": "abs-a-6-positive-exposition",
    "type": "REFLECTS",
    "reason": "Dialectical transition inferred from abs-a-6-positive-exposition semantics."
  },
  {
    "fromChunkId": "abs-a-6-positive-exposition",
    "toChunkId": "abs-a-7-positive-exposition-reflective-shine",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-a-6-positive-exposition",
    "toChunkId": "abs-a-7-positive-exposition-reflective-shine",
    "type": "NEGATES",
    "reason": "Dialectical transition inferred from abs-a-7-positive-exposition-reflective-shine semantics."
  },
  {
    "fromChunkId": "abs-a-7-positive-exposition-reflective-shine",
    "toChunkId": "abs-a-8-absolute-as-attribute",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-a-7-positive-exposition-reflective-shine",
    "toChunkId": "abs-a-8-absolute-as-attribute",
    "type": "MEDIATES",
    "reason": "Dialectical transition inferred from abs-a-8-absolute-as-attribute semantics."
  },
  {
    "fromChunkId": "abs-b-1-absolute-absolute-vs-attribute",
    "toChunkId": "abs-b-2-worlds-reduced-to-shine",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-b-1-absolute-absolute-vs-attribute",
    "toChunkId": "abs-b-2-worlds-reduced-to-shine",
    "type": "MEDIATES",
    "reason": "Dialectical transition inferred from abs-b-2-worlds-reduced-to-shine semantics."
  },
  {
    "fromChunkId": "abs-b-2-worlds-reduced-to-shine",
    "toChunkId": "abs-b-3-attribute-as-identity-determination",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-b-2-worlds-reduced-to-shine",
    "toChunkId": "abs-b-3-attribute-as-identity-determination",
    "type": "NEGATES",
    "reason": "Dialectical transition inferred from abs-b-3-attribute-as-identity-determination semantics."
  },
  {
    "fromChunkId": "abs-b-3-attribute-as-identity-determination",
    "toChunkId": "abs-b-4-positive-reflective-shine-sublates",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-b-3-attribute-as-identity-determination",
    "toChunkId": "abs-b-4-positive-reflective-shine-sublates",
    "type": "SUBLATES",
    "reason": "Dialectical transition inferred from abs-b-4-positive-reflective-shine-sublates semantics."
  },
  {
    "fromChunkId": "abs-b-4-positive-reflective-shine-sublates",
    "toChunkId": "abs-b-5-reflection-reverts-to-identity",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-b-4-positive-reflective-shine-sublates",
    "toChunkId": "abs-b-5-reflection-reverts-to-identity",
    "type": "REFLECTS",
    "reason": "Dialectical transition inferred from abs-b-5-reflection-reverts-to-identity semantics."
  },
  {
    "fromChunkId": "abs-b-5-reflection-reverts-to-identity",
    "toChunkId": "abs-b-6-form-nullity",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-b-5-reflection-reverts-to-identity",
    "toChunkId": "abs-b-6-form-nullity",
    "type": "REFLECTS",
    "reason": "Dialectical transition inferred from abs-b-6-form-nullity semantics."
  },
  {
    "fromChunkId": "abs-c-1-attribute-two-sides",
    "toChunkId": "abs-c-2-mode-externality-posited",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-c-1-attribute-two-sides",
    "toChunkId": "abs-c-2-mode-externality-posited",
    "type": "REFLECTS",
    "reason": "Dialectical transition inferred from abs-c-2-mode-externality-posited semantics."
  },
  {
    "fromChunkId": "abs-c-2-mode-externality-posited",
    "toChunkId": "abs-c-3-exposition-exhaustive",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-c-3-exposition-exhaustive",
    "toChunkId": "abs-c-4-reflective-movement",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-c-3-exposition-exhaustive",
    "toChunkId": "abs-c-4-reflective-movement",
    "type": "NEGATES",
    "reason": "Dialectical transition inferred from abs-c-4-reflective-movement semantics."
  },
  {
    "fromChunkId": "abs-c-4-reflective-movement",
    "toChunkId": "abs-c-5-mode-immanent-turning-back",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-c-4-reflective-movement",
    "toChunkId": "abs-c-5-mode-immanent-turning-back",
    "type": "REFLECTS",
    "reason": "Dialectical transition inferred from abs-c-5-mode-immanent-turning-back semantics."
  },
  {
    "fromChunkId": "abs-c-5-mode-immanent-turning-back",
    "toChunkId": "abs-c-6-determinateness-from-absolute",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-c-5-mode-immanent-turning-back",
    "toChunkId": "abs-c-6-determinateness-from-absolute",
    "type": "REFLECTS",
    "reason": "Dialectical transition inferred from abs-c-6-determinateness-from-absolute semantics."
  },
  {
    "fromChunkId": "abs-c-6-determinateness-from-absolute",
    "toChunkId": "abs-c-7-true-meaning-of-mode",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-c-6-determinateness-from-absolute",
    "toChunkId": "abs-c-7-true-meaning-of-mode",
    "type": "REFLECTS",
    "reason": "Dialectical transition inferred from abs-c-7-true-meaning-of-mode semantics."
  },
  {
    "fromChunkId": "abs-c-7-true-meaning-of-mode",
    "toChunkId": "abs-c-8-content-of-exposition",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-c-7-true-meaning-of-mode",
    "toChunkId": "abs-c-8-content-of-exposition",
    "type": "NEGATES",
    "reason": "Dialectical transition inferred from abs-c-8-content-of-exposition semantics."
  },
  {
    "fromChunkId": "abs-c-8-content-of-exposition",
    "toChunkId": "abs-c-9-absolute-as-actuality",
    "type": "NEXT",
    "reason": "Sequential order in source text."
  },
  {
    "fromChunkId": "abs-a-8-absolute-as-attribute",
    "toChunkId": "abs-b-1-absolute-absolute-vs-attribute",
    "type": "SUBLATES",
    "reason": "Exposition of the absolute passes into the absolute attribute."
  },
  {
    "fromChunkId": "abs-b-6-form-nullity",
    "toChunkId": "abs-c-1-attribute-two-sides",
    "type": "SUBLATES",
    "reason": "Attribute passes into mode as externalized determinateness."
  }
] as const;

const topicmapActualityAbsoluteTopicMapMetadata = {
  "totalSources": 3,
  "totalChunks": 23,
  "generatedAt": "2026-02-17T22:47:21.819Z"
} as const;

export const topicmapActualityAbsoluteTopicMapIR = {
  id: "actuality-absolute-topicmap-ir",
  mode: "debug",
  title: "Actuality-Absolute TopicMap IR",
  section: "Doctrine of Essence / Actuality / Absolute",
  sourceDocuments: topicmapActualityAbsoluteTopicMapSources,
  traces: topicmapActualityAbsoluteTopicMapTraces,
  metadata: topicmapActualityAbsoluteTopicMapMetadata,
} as const;

export type ActualityAbsoluteTopicMapIR = typeof topicmapActualityAbsoluteTopicMapIR;
