import type { Chunk, LogicalOperation } from './index';

/*
  Repulsion and Attraction — C. REPULSION AND ATTRACTION

  This module covers the final development of being-for-itself:
  - a) Exclusion of the one: Many ones, mutual repulsion, self-preservation, dissolution, unity
  - b) The one one of attraction: Fragmentation, transition, mediated one, unity of repulsion/attraction
  - c) The connection: Self-presupposing, mutual mediation, transitions, completion → quantity

  PHILOSOPHICAL NOTES:

  1. **Exclusion of the One**:
     The many ones are each a being; their reference is non-reference (the void).
     They are negative reference to themselves as existent others—infinity posited in immediacy.
     Repulsion is mutual exclusion, relative, limited. Plurality is not posited otherness;
     limit is the void, yet they are in the void—repulsion is their common connecting reference.
     Mutual repulsion preserves them through their own distinguishing, yet also dissolves them.

  2. **Self-Preservation and Dissolution**:
     The ones maintain themselves through reciprocal exclusion. But in their being-in-itself,
     they are all the same (no diversity); in their reciprocal negating, they posit themselves
     as identical. According to their being and positing, they are only one affirmative unity.
     Their self-preservation through negative reference is rather their dissolution.

  3. **From Repulsion to Attraction**:
     Repulsion is itself a referring that returns to itself—a coming-together-with-oneself.
     The identity in which repelling crosses over sublates diversity and externality.
     This self-positing-in-a-one of the many ones is attraction.

  4. **The One One of Attraction**:
     Repulsion fragments the one into many (the ought of ideality), realized in attraction.
     Attraction presupposes repulsion (its material). If accomplished, only an inert one remains.
     Attraction posits the mediated one through the posited negation of immediate ones.
     The one one is realized ideality that preserves the many within (contains repulsion).

  5. **The Connection**:
     Each determination self-presupposes and contains the other as moment. One → many
     (coming-out-of-itself), many → one (falling back). Each is its own negation and continuity
     in its other. Repulsion shows attraction as ideality; attraction sublates itself into repulsion.
     The one connects to itself infinitely, repels itself as many, sublates otherness—completing
     being-for-itself. Becoming collapses into simple immediacy: quantity.
*/

// ============================================================================
// C. REPULSION AND ATTRACTION
// ============================================================================

export const CANONICAL_CHUNKS: Chunk[] = [
  {
    id: 'bfs-ra-a-exclusion-many-ones-void',
    title: 'a) Exclusion of the one — Many ones, void, and repulsion',
    text: `a. Exclusion of the one

The many ones are each a being;
their existence or their reference to one another
is a non-reference, it is external to them:
the abstract void.
But they themselves are now this negative reference
to themselves as to existent others:
the demonstrated contradiction, the infinity posited
in the immediacy of being.
With this, repulsion now finds immediately before it
that which is repelled by it.
In this determination, it is an excluding;
the one repels from itself only the many not generated by it,
the ones not posited by it.
This repelling is mutual or from all sides, relative,
limited by the being of the ones.

Plurality is not at first posited otherness;
limit is only the void, only that in which the ones are not.
But in the limit they also are;
they are in the void,
or their repulsion is their
common connecting reference.`,
    summary:
      'Many ones: their reference is non-reference (the void). They are negative reference to themselves as existent others—infinity in immediacy. Repulsion is mutual exclusion, relative, limited. Plurality is not posited otherness; limit is the void, yet they are in the void—repulsion is their common connecting reference.'
  },
  {
    id: 'bfs-ra-a-mutual-repulsion-preservation',
    title: 'a) Exclusion — Mutual repulsion as posited existence and preservation',
    text: `This mutual repulsion is the posited
existence of the many ones;
it is not their being-for-itself,
in accordance with which they would be
distinguished as many only in a third,
but is rather their own distinguishing
which preserves them.
They mutually negate themselves,
posit one another as being only for-one.
But at the same time they negate this
being only for-one just as much;
they repel the ideality that they have and are.
So the moments which in ideality are
absolutely united come apart.
In its being-for-itself, the one is also for-one;
but this one, for which it is, is itself;
its distinguishing from itself is immediately sublated.
But in the plurality the distinguished one has a being;
the being-for-one as has been determined in exclusion
is therefore a being-for-other.
Each thus comes to be repelled by an other,
is sublated and made into a one which is not for itself
but for-one, and an other one at that.`,
    summary:
      'Mutual repulsion is the posited existence of the many ones—their own distinguishing that preserves them. They mutually negate, posit each other as for-one, yet also negate this and repel their ideality. In plurality, being-for-one becomes being-for-other; each is repelled, sublated, made into a one for-another.'
  },
  {
    id: 'bfs-ra-a-self-preservation-dissolution',
    title: 'a) Exclusion — Self-preservation through mutual repulsion and dissolution',
    text: `The being-for-itself of the many ones
thus shows itself to be their self-preservation
through the mediation of their mutual repulsion
in which they sublated themselves reciprocally
and posit the others as mere being-for-another.
But the self-preservation consists at the same time
in repelling this ideality and positing the ones
as not being for-an-other.
This self-preservation of the ones
through their negative reference to one another is,
however, rather their dissolution.

The ones not only are but maintain themselves
through their reciprocal exclusion.
First, it is in their being,
and indeed their being-in-itself as
contrasted with their reference to the other,
that they should now have a firm point of support
for their diversity as against their being negated;
this in-itselfness rests on their being ones.
But they all are this;
in their being-in-itself,
instead of having there their
firm point of support for their diversity,
they are all the same.
Second, their existence and their
way of relating to one another,
that is, their positing themselves as one,
is their reciprocal negating;
this, however, is likewise one and the same determination of
all through which they therefore posit themselves as identical;
just as, by being in themselves the same,
the ideality that should be posited in them
through others is their own,
and they thus repel just as little.
According to their being and positing,
they are, consequently, only one affirmative unity.`,
    summary:
      'Self-preservation through mutual repulsion shows as dissolution. The ones maintain themselves through reciprocal exclusion, yet in their being-in-itself they are all the same (no diversity); in their reciprocal negating, they posit themselves as identical. According to their being and positing, they are only one affirmative unity.'
  },
  {
    id: 'bfs-ra-a-exclusion-to-attraction',
    title: 'a) Exclusion — From comparison to attraction',
    text: `This consideration regarding the ones:
that from either side of their determination,
whether they just are or refer to one another,
they show themselves to be only one and the same,
indistinguishable, is a comparison that belongs to us.
Also to be seen, therefore, is what is posited in them
in their mutual reference itself.
They are (this much is presupposed in this reference)
and they are only inasmuch as
they negate themselves reciprocally
and at the same time keep away this ideality,
their being negated, from themselves, that is,
they negate the reciprocal negating.
But they are only inasmuch as they negate,
and so, since their reciprocal negating is negated,
their being is negated.
To be sure, since they are,
nothing would be negated through this negating
which for them is only something external;
this negating of the other rebounds off them,
coming their way only by striking their surface.
And yet, they turn back upon themselves
only by negating the others;
they are only as this mediation,
this turning back of theirs is their self-preservation
and their being-for- itself.
Since their negating is ineffectual
because of the resistance offered by the others,
whether as existents or as negating,
they do not return back to themselves,
do not preserve themselves, and so are not.
It was previously remarked that
the ones themselves are each a one like any other.
This is not just a matter of our
connecting them by way of reference,
of bringing them together externally;
repulsion is itself a referring;
the one that excludes the ones refers itself to them,
to the ones, that is, to itself.
The negative relating of the ones to one another is consequently
only a coming-together-with-oneself.
This identity in which their repelling crosses over is
the sublation of their diversity and externality
which they should have rather asserted with respect to
each other by excluding each other.

This self-positing-in-a-one of the many ones is attraction.`,
    summary:
      "Comparison shows indistinguishability, but the inner posit is this: the ones are only insofar as they negate. If they negate the reciprocal negating, they negate their being. Though negation seems 'external,' their return-to-self is only via negating others (mediation); if ineffectual, they fail to preserve themselves. Repulsion is itself a referring that returns to self, sublating diversity/externality. The many self-posit in a one: attraction."
  },
  {
    id: 'bfs-ra-b-one-one-of-attraction',
    title: 'b) The one one of attraction (I)',
    text: `b. The one one of attraction

Repulsion is the fragmentation of the one,
first into the many of which
it is the negative relating,
since they presuppose each other as each existent;
it is only the ought of ideality;
this ideality will, however, be realized in attraction.
Repulsion passes over into attraction,
the many ones into one one.
Both, repulsion and attraction, are
at first distinguished from each other,
repulsion as the reality of the ones,
attraction as their posited ideality.
Attraction refers to repulsion
by having it for a presupposition.
Repulsion delivers the material for attraction.
If there were no ones,
there would be nothing to attract;
the representation of continuing attraction,
of the consumption of the ones,
presupposes an equally continuing generation of the ones;
the sense representation of spatial attraction
gives continuity to the flow of ones to be attracted;
to replace the atoms that vanish at the point of attraction,
another multitude comes forth from the void,
infinitely if one so wishes.
If attraction were represented as accomplished, that is,
the many as brought to the point of the one one,
the result would be just an inert one, no longer any attraction.
The ideality immediately present in attraction
still also has in it the determination of the negation of itself,
the many ones to which it refers;
attraction is inseparable from repulsion.`,
    summary:
      'Repulsion fragments the one into many (the ought of ideality), which is realized in attraction: many ones pass into one one. Repulsion = reality of ones; attraction = posited ideality and presupposes repulsion (its material). Continuous attraction presupposes continuous generation (a flow from the void). If fully accomplished, only an inert one remains (no attraction). Attraction bears its own negation (the many) and is inseparable from repulsion.'
  },
  {
    id: 'bfs-ra-b-one-one-of-attraction-ii',
    title: 'b) The one one of attraction (II)',
    text: `To attract pertains at first in equal measure
to each of the many ones as immediately present;
none has advantage over an other;
what would result then is an equilibrium in the attraction,
or more precisely, an equilibrium in the attraction
and the repulsion themselves, and an inert state of rest
without any ideality present there.
But there can be no question here of
any such immediately present one taking precedence over another,
for this would presuppose a determinate distinction between them;
attraction is rather the positing of
the given lack of distinction among the ones.
Attraction is itself the positing in the first place
of a one distinct from other ones;
these are only the immediate ones
that are to preserve themselves through repulsion;
through their posited negation, however, what proceeds
is the one of attraction
which is therefore determined as the mediated one,
the one posited as one.
The first ones, as immediate, do not in their ideality
return into themselves,
but have this ideality each in another.`,
    summary:
      'Equal applicability of attraction to all immediate ones would yield equilibrium (attraction/repulsion) and inert rest (no ideality). No precedence is presupposable; attraction posits their lack of distinction. Attraction first posits a one distinct from others: the mediated "one of attraction," arising through the posited negation of immediate ones that preserve themselves via repulsion. Immediate ones do not return to themselves in their ideality; each has it in another.'
  },
  {
    id: 'bfs-ra-b-one-one-of-attraction-iii',
    title: 'b) The one one of attraction (III)',
    text: `The one one is, however,
ideality that has been realized,
posited in the one;
it attracts through the mediation of repulsion;
it contains in itself this mediation as its determination.
It thus does not swallow the attracted ones
within it as into one point, that is,
does not sublate them abstractly.
Since it contains repulsion in its determination,
the latter equally preserves the ones as many within it;
by its attracting, it musters, so to speak,
something before it, gains an area or a filling.
Thus there is in it the unity
of repulsion and attraction in general.`,
    summary:
      'The "one one" is realized ideality posited in the one; it attracts via repulsion and contains this mediation as its determination. It does not swallow/sublate abstractly; because it contains repulsion, it preserves the many within, mustering a filling/area. It is the unity of repulsion and attraction.'
  },
  {
    id: 'bfs-ra-c-connection-1',
    title: 'c) The connection (I)',
    text: `c. The connection of repulsion and attraction

The difference of the one and the many
has determined itself as a difference
of their mutual reference connecting them
which breaks down into two, repulsion and attraction,
each of which stands at first
outside the other on its own,
in such a way that the two are
essentially joined together nevertheless.
Their still indeterminate unity
must be brought out in greater detail.

As the fundamental determination of the one,
repulsion appears first, and it appears as immediate,
like its ones which are indeed generated by it
and yet are at the same time posited as immediate,
and it is therefore indifferent to the attraction
which is added to it externally as thus presupposed.
Rather, attraction is not presupposed by repulsion:
it is not supposed to have any part in the positing
and in the being of the latter, that is,
as if repulsion were not, already in it,
the negation of itself,
or the ones were not already negated in it.
In this way, we have repulsion in abstraction, by itself,
and attraction likewise holds out to the ones,
as each an existent, the side of an immediate existence
which comes to them by itself as an other.`,
    summary:
      'Difference becomes a split of mutual reference into repulsion and attraction: initially apart yet essentially joined. Repulsion appears first and immediate, generating ones posited as immediate, seeming indifferent to an externally added attraction. This abstraction ignores that repulsion already negates itself and the ones; set thus, repulsion is taken by itself while attraction shows up as an external immediate side for the ones.'
  },
  {
    id: 'bfs-ra-c-connection-1b-repulsion-contains-attraction',
    title: 'c) The connection (I-b): Repulsion contains attraction',
    text: `If we take mere repulsion in this way, for itself,
it is then the dispersion of the many ones in indeterminacy,
outside the sphere of repulsion itself;
for repulsion is the negating of the connection
of the many to one another;
lack of connection is their determination when abstractly taken.
But repulsion is not just the void;
the ones, although unconnected,
do not repel what constitutes their determination,
do not exclude it.
Although negative, repulsion is nonetheless essentially connection;
the mutual repulsion and flight is not a liberation
from what is repelled and fled from;
that which is excluded still stands in connection
with what is excluded from it.
But this moment of connection is attraction,
which is thus within repulsion itself;
it is the negating of that abstract repulsion
by which the ones would each be an existent
referring only to itself without mutual exclusion.

But in starting with the repulsion
of the ones as immediately present there,
and with attraction consequently also posited
as intruding on them externally,
the two, repulsion and attraction,
are held apart as diverse
determinations despite their inseparability.
But it has been established that it is not
just repulsion which is presupposed by attraction,
but that there equally is present also
a reverse connection of repulsion to attraction,
and that repulsion no less has
attraction for its presupposition.

As thus determined, they are inseparable,
and at the same time each is determined
as an ought and a limitation with respect to the other.
Their ought is their abstract determinateness
as each an existent in itself,
a determinateness, however, which is thereby
directed beyond itself and refers to the other.
And so, through the mediation of the other, each is as other;
their self-subsistence consists in their being mutually posited
in this mediation as an other determining.
Thus, repulsion is the positing of the many;
attraction the positing of the one;
this latter is equally the negation of the many
and the former the negation of the ideality
of such a many in the one;
so that attraction too is attraction only through
the mediation of repulsion,
just as repulsion is repulsion
through the mediation of attraction.
In all this, however, the mediation of each with itself
through the other is in fact negated;
each of the two determinations is its own self-mediation.
This will result from a closer examination of the two determinations
and will bring us back to the unity of their concept.`,
    summary:
      'Taking repulsion for itself: dispersion in indeterminacy, lack of connection. Yet repulsion is essentially connection; the excluded stands in connection with what excludes it. This moment of connection is attraction—within repulsion itself. Despite being held apart, repulsion also presupposes attraction (reverse connection). They are inseparable, each an ought/limitation with respect to the other. Each mediates through the other, yet each is its own self-mediation—bringing us back to the unity of their concept.'
  },
  {
    id: 'bfs-ra-c-connection-2',
    title: 'c) The connection (II)',
    text: `In the first place, that each presupposes itself,
that in its presupposition each refers only to itself,
this is already present in the way the still relative
repulsion and attraction behave at first.

Relative repulsion is the mutual repulsion
of many ones which are already at hand,
supposedly immediately given.
But that there be many ones,
this is repulsion itself;
any presupposition that it would have is
only its own positing.
Moreover, the determination of the being
that would accrue to the ones
apart from their being posited
(whereby they would already be)
belongs likewise to repulsion.
Repelling is that through which
the ones manifest themselves
and maintain themselves as ones;
through which they are as such.
Their being is their repulsion itself,
which is thus not some relative
existence against another other
but relates itself throughout only to itself.

Attraction is the positing of the one as such,
of the real one, with respect to which
the existence of the many is determined
as only a vanishing idealization.
Attraction thus directly presupposes itself;
it presupposes itself in the determination namely,
of the many ones to be an idealization,
the same ones which are otherwise supposed
to have existence for themselves and to repel others,
including therefore any other that attracts.
Against this determination of repulsion,
the ones do not attain ideality only through
the relation to attraction;
on the contrary, the ideality is presupposed:
it is the ideality of the ones
as an existent in itself,
inasmuch as they, as ones
(including the one conceived as attracting),
are not distinguished from one another
but are one and the same.

This self-presupposing of the two determinations, each for itself,
implies further that each contains within itself the other as moment.
Self-presupposing in general is the positing of oneself
in a one as the negative of oneself (repulsion),
and what is presupposed in this positing is
the same as that which presupposes (attraction).
That each is in itself only a moment,
this is the transition of each from itself into the other,
the negation of itself in the other
and the positing of itself as the other of itself.
The one, as such, is thus a coming-out-of-itself;
is itself only the positing of itself as its other, as the many.
And the many, for its part, is
only the falling back upon itself
and the positing of itself as its other, as a one,
and is in this equally only the connecting of itself to itself,
each continuing itself in its other.
Therefore, the coming-out-of-itself (repulsion)
and the self-positing-as-one (attraction)
are already inherently present as undivided.
But in the repulsion and attraction which are relative, that is,
which presuppose immediate, determinedly existent ones,
it is posited that the two are each, within it, this negation of itself,
and consequently also the continuity of itself in its other.
The repulsion of the determinedly existent ones is
the self-preservation of the one
through the mutual holding off of the others,
so that (1) the other ones are negated in it
(this is the side of its existence or of its being-for-another
and is therefore attraction as the ideality of the ones);
and (2) the one is in itself,
without reference to the others
(however, not only has the in-itself in general
long since passed over into being-for-itself;
the one in itself, according to its determination,
is the coming to be of many).
The attraction of the existent ones is their ideality
and the positing of the one, and in this,
as both the negating and the producing of the one,
attraction sublates itself,
and as a positing within it of the one,
is the negative of itself:
it is repulsion.`,
    summary:
      'Each determination self-presupposes and self-refers. Repulsion: the many are its own positing; being of the ones just is repulsion, relating only to itself. Attraction: posits the real one and presupposes the many as idealization; ones (including the attracting one) are the same. Hence each contains the other as a moment: one → many (coming-out), many → one (falling back). Even in relative forms, each is its own negation and its continuity in its other. Repulsion preserves the one while negating others (thus showing attraction as ideality) and holding an in-itself that becomes many. Attraction, as negating/producing the one, sublates itself into repulsion.'
  },
  {
    id: 'bfs-ra-c-connection-3-transition-to-quantity',
    title: 'c) The connection (III): Result and transition to quantity',
    text: `With this, the development of being-for-itself
is completed and has attained its result.
In connecting itself to itself infinitely,
that is, as the posited negation of negation,
the one is the mediation by which it repels itself
as its absolute (that is, abstract) otherness (the many) from itself,
and in thus negatively connecting itself to this, its non-being,
it sublates it and is in it precisely only the connection to itself.
The one is only this becoming in which
the determination "it begins," that is,
its being posited as an immediate existent,
and equally that, as result,
it has restored itself as the one,
that is, the equally immediate and exclusive one, have vanished;
the process which it is, posits and contains it
from all sides only as something sublated.
The sublation, determined at first only as a relative sublating of
the connection to another existent,
a connection which is therefore itself not
an indifferent repulsion and attraction,
equally proves itself to pass over into
the infinite connection of mediation
through the negation of the external
connection of immediate and determinate existents,
and to have for result precisely that becoming
which, in the instability of its moments, is the collapse,
or rather the going-together-with-itself, into simple immediacy.
This being, according to the determination
which it has now acquired, is quantity.`,
    summary:
      'Result: Being-for-itself completes itself. The one, as negation-of-negation, mediates by repelling itself as many and sublating this otherness into self-connection. Both beginning and result as immediate ones vanish; the one exists only as a sublated process. Relative repulsion/attraction passes into infinite mediation; becoming collapses into simple immediacy. This new being is quantity.'
  },
  {
    id: 'bfs-ra-c-connection-4-review-transition',
    title: 'c) Review of the transition (Quality → Quantity)',
    text: `And this concludes Quality and has an interesting transition into Quantity.

If we briefly review the moments
of this transition of quality into quantity,
we find that the qualitative has being and immediacy
for its fundamental determination,
and the limit and the determinateness are
in this immediacy so identical with the being of something,
that the something itself vanishes
along with its alteration;
as thus posited, it is determined as finite.
Because of the immediacy of this unity
in which the distinction has disappeared,
although it is implicitly present in
the unity of being and nothing,
the distinction falls outside
that unity as otherness in general.
This reference to the other contradicts the immediacy
in which qualitative determinateness is self-reference.
This otherness is sublated in
the infinity of the being-for-itself,
the being-for-itself that has realized
the distinction implicitly present in it
in the negation of negation:
has realized it as the one and the many
and as their connecting references,
and has also elevated the qualitative to true unity,
that is, a unity which is no longer immediate
but posited as accordant with itself.

This unity is, therefore,
(a) being, only as affirmative, that is,
immediacy self-mediated through the negation of negation:
being is posited as a unity permeating
its determinacies, limits, etc.,
which are posited in it as sublated;
(b) existence:
in this determination it is negation
or determinateness as moment of
the affirmative being;
yet this determinateness is no longer
immediate but reflected into itself,
refers not to another but to itself;
(c) absolutely-determined-being,
(d) absolute in-itselfness,
(e) the one;
(f) otherness as such is itself being-for-itself;
(g) being-for-itself:
as that being which persists
across the determinateness
and in which the one
and even the being-determined-in-itself
are posited as sublated.
The one is simultaneously determined
as having gone beyond itself and as unity;
the one, the absolutely determined limit,
is consequently posited as a limit which is none,
a limit which is in being but is indifferent to it.`,
    summary:
      'Review: Quality's immediacy makes limit identical with being, so alteration sublates the something (finitude). Distinction falls outside as otherness, contradicting immediacy; being-for-itself (negation of negation) realizes the one, the many, and their connections, elevating quality to posited unity. Enumerated unity: (a) mediated being; (b) existence as reflected determinateness; (c) absolutely determined being; (d) absolute in-itselfness; (e) the one; (f) otherness as being-for-itself; (g) being-for-itself persisting across determinateness with one and in-itself sublated. The one as absolute limit is a limit that is none—indifferent in being—signaling quantity.'
  }
];

export const LOGICAL_OPERATIONS: LogicalOperation[] = [
  {
    id: 'bfs-op-ra-a1-many-ones-void-contradiction',
    chunkId: 'bfs-ra-a-exclusion-many-ones-void',
    label: 'Many ones: reference is non-reference (void); negative reference to themselves as existent others—infinity in immediacy',
    clauses: [
      'assert(is(ManyOnes,"each-a-being"))',
      'assert(is(Reference,"non-reference-external"))',
      'assert(is(Void,"abstract"))',
      'assert(is(NegativeReference,"to-themselves-as-existent-others"))',
      'assert(is(Contradiction,"infinity-posited-in-immediacy"))',
      'assert(is(Repulsion,"excluding"))',
      'assert(is(Repelling,"mutual-relative-limited"))',
      'assert(is(Plurality,"not-posited-otherness"))',
      'assert(is(Limit,"void"))',
      'assert(areInVoid(ManyOnes,true))',
      'assert(is(Repulsion,"common-connecting-reference"))'
    ],
    predicates: [{ name: 'RA_Exclusion_ManyOnes_Void', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-a2-mutual-repulsion-preservation',
    chunkId: 'bfs-ra-a-mutual-repulsion-preservation',
    label: 'Mutual repulsion is posited existence; their own distinguishing that preserves; moments come apart',
    clauses: [
      'assert(is(MutualRepulsion,"posited-existence-of-many-ones"))',
      'assert(isNot(MutualRepulsion,"being-for-itself"))',
      'assert(is(MutualRepulsion,"own-distinguishing-preserves"))',
      'assert(mutuallyNegate(ManyOnes,true))',
      'assert(positAsBeingForOne(ManyOnes,true))',
      'assert(negateBeingForOne(ManyOnes,true))',
      'assert(repelIdeality(ManyOnes,true))',
      'assert(comeApart(Moments,true))',
      'assert(inPlurality(BeingForOne,"being-for-other"))',
      'assert(repelledByOther(Each,true))',
      'assert(sublatedIntoOneForAnother(Each,true))'
    ],
    predicates: [{ name: 'RA_MutualRepulsion_Preservation', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-a3-self-preservation-dissolution',
    chunkId: 'bfs-ra-a-self-preservation-dissolution',
    label: 'Self-preservation through mutual repulsion shows as dissolution; ones are all the same; only one affirmative unity',
    clauses: [
      'assert(is(SelfPreservation,"through-mediation-of-mutual-repulsion"))',
      'assert(sublateThemselvesReciprocally(ManyOnes,true))',
      'assert(positOthersAsMereBeingForAnother(ManyOnes,true))',
      'assert(repelIdeality(ManyOnes,true))',
      'assert(is(SelfPreservation,"dissolution"))',
      'assert(maintainThroughReciprocalExclusion(ManyOnes,true))',
      'assert(shouldHaveFirmPointForDiversity(ManyOnes,true))',
      'assert(areAllTheSame(ManyOnes,true))',
      'assert(is(ReciprocalNegating,"one-and-same-determination"))',
      'assert(positThemselvesAsIdentical(ManyOnes,true))',
      'assert(is(Result,"one-affirmative-unity"))'
    ],
    predicates: [{ name: 'RA_SelfPreservation_Dissolution', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-a4-comparison-vs-posited-reference',
    chunkId: 'bfs-ra-a-exclusion-to-attraction',
    label: 'Beyond comparison: see what is posited in mutual reference itself',
    clauses: [
      'assert(comparisonShowsIndistinguishable(true))',
      'assert(focusOnPositedInMutualReference(true))'
    ],
    predicates: [{ name: 'RA_Posited_In_Mutual_Reference', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-a5-negating-negation-negates-being',
    chunkId: 'bfs-ra-a-exclusion-to-attraction',
    label: 'They are only insofar as they negate; negating the reciprocal negating negates their being',
    clauses: [
      'assert(onlyInsofarAsNegate(true))',
      'assert(keepAwayIdealityOfBeingNegated(true))',
      'assert(negateReciprocalNegating(true))',
      'assert(therebyBeingIsNegated(true))'
    ],
    predicates: [{ name: 'RA_Negation_of_Negation', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-a6-mediation-or-failure-to-return',
    chunkId: 'bfs-ra-a-exclusion-to-attraction',
    label: 'Return-to-self only via negating others (mediation); if negation rebounds or is resisted, no preservation (are not)',
    clauses: [
      'assert(negationSeemsExternalRebound(true))',
      'assert(returnToSelfOnlyViaNegatingOthers(true))',
      'assert(beingIsMediationOfReturn(true))',
      'assert(resistanceMakesNegationIneffectual(true))',
      'assert(noReturnNoPreservationNoBeing(true))'
    ],
    predicates: [{ name: 'RA_Mediation_vs_Ineffectual', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-a7-repulsion-as-referring-identity-sublation',
    chunkId: 'bfs-ra-a-exclusion-to-attraction',
    label: 'Repulsion is a referring that returns to itself; negative relating is a coming-together-with-oneself; diversity/externality sublated',
    clauses: [
      'assert(repulsionIsReferring(true))',
      'assert(excludingOneRefersToOnesThusToItself(true))',
      'assert(negativeRelatingIsComingTogetherWithSelf(true))',
      'assert(identityAsSublationOfDiversityExternality(true))'
    ],
    predicates: [{ name: 'RA_Repulsion_Return_Identity', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-a8-attraction-definition',
    chunkId: 'bfs-ra-a-exclusion-to-attraction',
    label: 'Self-positing-in-a-one of the many ones is attraction',
    clauses: [
      'assert(selfPositingInOneOfMany(true))',
      'assert(attraction(true))'
    ],
    predicates: [{ name: 'RA_Attraction_Definition', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b1-fragmentation-and-ought',
    chunkId: 'bfs-ra-b-one-one-of-attraction',
    label: 'Repulsion fragments the one into many; it is only the ought of ideality, realized in attraction',
    clauses: [
      'assert(fragmentsOneIntoMany("repulsion",true))',
      'assert(negativeRelatingOfMany(true))',
      'assert(oughtOfIdeality("repulsion",true))',
      'assert(idealityRealizedIn("attraction"))'
    ],
    predicates: [{ name: 'RA_Fragmentation_Ought', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b2-transition-and-roles',
    chunkId: 'bfs-ra-b-one-one-of-attraction',
    label: 'Repulsion passes over into attraction; many ones into one one; roles: repulsion=reality, attraction=posited ideality',
    clauses: [
      'assert(passesOver("repulsion","attraction"))',
      'assert(transforms("many-ones","one-one"))',
      'assert(role("repulsion","reality-of-ones"))',
      'assert(role("attraction","posited-ideality"))'
    ],
    predicates: [{ name: 'RA_Transition_Roles', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b3-presupposition-material',
    chunkId: 'bfs-ra-b-one-one-of-attraction',
    label: 'Attraction presupposes repulsion; repulsion delivers the material (the ones)',
    clauses: [
      'assert(presupposes("attraction","repulsion"))',
      'assert(deliversMaterial("repulsion","ones"))',
      'assert(ifNo("ones"),"nothingToAttract")'
    ],
    predicates: [{ name: 'RA_Presupposition_Material', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b4-continuity-flow-from-void',
    chunkId: 'bfs-ra-b-one-one-of-attraction',
    label: 'Continuing attraction presupposes continuing generation; sense-image: spatial flow of ones from the void',
    clauses: [
      'assert(continuingAttractionRequiresGeneration(true))',
      'assert(flowOfOnesFromVoid(true))',
      'assert(replacesVanishedAtomsAtPointOfAttraction(true))'
    ],
    predicates: [{ name: 'RA_Continuity_Flow', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b5-accomplished-inert-one',
    chunkId: 'bfs-ra-b-one-one-of-attraction',
    label: 'If attraction were accomplished (many → one one), result is inert one; no attraction remains',
    clauses: [
      'assert(ifAccomplishedAttractionThen("inert-one"))',
      'assert(noAttractionRemains(true))'
    ],
    predicates: [{ name: 'RA_Accomplished_Inert', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b6-bears-negation-inseparable',
    chunkId: 'bfs-ra-b-one-one-of-attraction',
    label: 'Attraction bears its own negation (the many ones) and is inseparable from repulsion',
    clauses: [
      'assert(containsDeterminationOfItsNegation("attraction","many-ones"))',
      'assert(inseparableFrom("attraction","repulsion"))'
    ],
    predicates: [{ name: 'RA_Negation_Inseparable', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b7-equilibrium-no-ideality',
    chunkId: 'bfs-ra-b-one-one-of-attraction-ii',
    label: 'Equal attraction to all immediate ones ⇒ equilibrium of attraction/repulsion ⇒ inert rest (no ideality)',
    clauses: [
      'assert(equalAttractionToAllImmediateOnes(true))',
      'assert(equilibriumAttractionAndRepulsion(true))',
      'assert(inertRestNoIdeality(true))'
    ],
    predicates: [{ name: 'RA_Equilibrium_NoIdeality', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b8-no-precedence-lack-of-distinction',
    chunkId: 'bfs-ra-b-one-one-of-attraction-ii',
    label: 'No precedence without determinate distinction; attraction posits lack of distinction among ones',
    clauses: [
      'assert(noPrecedenceWithoutDistinction(true))',
      'assert(attractionPositsLackOfDistinction(true))'
    ],
    predicates: [{ name: 'RA_NoPrecedence_LackOfDist', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b9-positing-mediated-one',
    chunkId: 'bfs-ra-b-one-one-of-attraction-ii',
    label: 'Attraction posits a one distinct from others: the mediated one (the one posited as one)',
    clauses: [
      'assert(attractionPositsOneDistinct(true))',
      'assert(mediatedOnePositedAsOne(true))'
    ],
    predicates: [{ name: 'RA_Mediated_One', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b10-immediates-preserve-via-repulsion-negation-yields-one-of-attraction',
    chunkId: 'bfs-ra-b-one-one-of-attraction-ii',
    label: 'Immediate ones preserve via repulsion; through their posited negation proceeds the one of attraction',
    clauses: [
      'assert(immediateOnesPreserveThroughRepulsion(true))',
      'assert(positedNegationGeneratesOneOfAttraction(true))'
    ],
    predicates: [{ name: 'RA_Posited_Negation_Generates_One', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b11-ideality-in-another-not-self-return',
    chunkId: 'bfs-ra-b-one-one-of-attraction-ii',
    label: 'Immediate ones do not return to self in ideality; each has its ideality in another',
    clauses: [
      'assert(noSelfReturnOfIdealityForImmediates(true))',
      'assert(idealityEachInAnother(true))'
    ],
    predicates: [{ name: 'RA_Ideality_In_Another', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b12-realized-ideality-mediated-attraction',
    chunkId: 'bfs-ra-b-one-one-of-attraction-iii',
    label: 'The one one = realized ideality posited in the one; attracts through mediation of repulsion (mediation as determination)',
    clauses: [
      'assert(realizedIdealityPositedInOne(true))',
      'assert(attractsThroughMediationOfRepulsion(true))',
      'assert(containsMediationAsDetermination(true))'
    ],
    predicates: [{ name: 'RA_Realized_Ideality_Mediated', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b13-no-abstract-sublation',
    chunkId: 'bfs-ra-b-one-one-of-attraction-iii',
    label: 'Does not swallow into a point; does not sublate the attracted ones abstractly',
    clauses: [
      'assert(doesNotSwallowIntoPoint(true))',
      'assert(doesNotSublateAbstractly(true))'
    ],
    predicates: [{ name: 'RA_No_Abstract_Sublation', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b14-preserves-many-filling',
    chunkId: 'bfs-ra-b-one-one-of-attraction-iii',
    label: 'Contains repulsion in determination; preserves the many within; musters a filling/area',
    clauses: [
      'assert(containsRepulsionInDetermination(true))',
      'assert(preservesManyWithin(true))',
      'assert(mustersFillingArea(true))'
    ],
    predicates: [{ name: 'RA_Preserves_Many_Filling', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-b15-unity-repulsion-attraction',
    chunkId: 'bfs-ra-b-one-one-of-attraction-iii',
    label: 'Unity of repulsion and attraction in general',
    clauses: [
      'assert(unityOfRepulsionAndAttraction(true))'
    ],
    predicates: [{ name: 'RA_Unity_Repulsion_Attraction', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c1-split-and-joined',
    chunkId: 'bfs-ra-c-connection-1',
    label: 'Difference of one/many → difference of mutual reference: repulsion and attraction, apart yet essentially joined',
    clauses: [
      'assert(differenceBecomesReferenceSplit(true))',
      'assert(twoDeterminations(["repulsion","attraction"]))',
      'assert(initiallyOutsideEachOther(true))',
      'assert(essentiallyJoined(true))',
      'assert(unityStillIndeterminate(true))'
    ],
    predicates: [{ name: 'RA_Connection_SplitJoined', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c2-repulsion-first-immediate',
    chunkId: 'bfs-ra-c-connection-1',
    label: 'Repulsion as fundamental appears first and immediate; its ones are generated yet posited as immediate; indifference to external attraction',
    clauses: [
      'assert(repulsionFundamental(true))',
      'assert(repulsionAppearsImmediate(true))',
      'assert(generatesOnesPositedImmediate(true))',
      'assert(indifferentToExternallyAddedAttraction(true))'
    ],
    predicates: [{ name: 'RA_Connection_RepulsionImmediate', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c3-not-presupposed-yet-already-negation',
    chunkId: 'bfs-ra-c-connection-1',
    label: 'Taking repulsion by itself denies attraction as presupposed, yet repulsion already negates itself and the ones in it',
    clauses: [
      'assert(treatAttractionAsNotPresupposed(true))',
      'assert(repulsionAlreadyNegationOfItself(true))',
      'assert(onesAlreadyNegatedInRepulsion(true))',
      'assert(repulsionInAbstraction(true))',
      'assert(attractionAsExternalImmediateSide(true))'
    ],
    predicates: [{ name: 'RA_Connection_AbstractView', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c4-repulsion-self-presupposes',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Repulsion self-presupposes: the many are its own positing; being of ones is repulsion; pure self-relation',
    clauses: [
      'assert(relativeRepulsionIsMutualAmongGivenOnes(true))',
      'assert(manyOnesAreRepulsionsOwnPositing(true))',
      'assert(anyPresuppositionBelongsToRepulsion(true))',
      'assert(beingOfOnesIsRepulsion(true))',
      'assert(repulsionRelatesOnlyToItself(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Repulsion_SelfPresupposes', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c5-attraction-self-presupposes',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Attraction posits the real one; directly presupposes itself by presupposing the many as idealization (all ones the same)',
    clauses: [
      'assert(attractionPositsRealOne(true))',
      'assert(directSelfPresupposition(true))',
      'assert(presupposesManyAsIdealization(true))',
      'assert(onesOtherwiseExistAndRepel(true))',
      'assert(onesIncludingAttractingAreSame(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Attraction_SelfPresupposes', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c6-each-contains-the-other-as-moment',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Self-presupposing ⇒ each contains the other as moment; definition of self-presupposing (repulsion/attraction)',
    clauses: [
      'assert(selfPresupposingImpliesContainsOtherMoment(true))',
      'assert(selfPresupposingIsPositingSelfAsNegativeOfSelf(true))',
      'assert(whatIsPresupposedEqualsPresupposing(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Moment_Inclusion', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c7-transitions-one-many',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Transitions: one → many (coming-out-of-itself); many → one (falling back); continuity in its other',
    clauses: [
      'assert(onePositsItselfAsMany(true))',
      'assert(manyPositThemselvesAsOne(true))',
      'assert(continuityInItsOther(true))',
      'assert(comingOutIsRepulsion(true))',
      'assert(selfPositingAsOneIsAttraction(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Transitions', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c8-relative-forms-negate-self-and-continue',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'In relative forms (with determinate ones), each is its own negation and its continuity in the other',
    clauses: [
      'assert(relativeRepulsionAndAttractionPositNegationOfSelf(true))',
      'assert(eachContinuesItselfInOther(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Relative_Negation_Continuity', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c9-repulsion-two-sides',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Repulsion of determinate ones: (1) negates others (existence/for-another = attraction as ideality); (2) the one is in-itself (yet becomes many)',
    clauses: [
      'assert(negatesOtherOnes(true))',
      'assert(sideIsExistenceOrForAnother(true))',
      'assert(thusAttractionAsIdeality(true))',
      'assert(oneIsInItselfWithoutReference(true))',
      'assert(inItselfAsBecomingMany(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Repulsion_TwoSides', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c10-attraction-sublates-into-repulsion',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Attraction (ideality/positing of the one) both negates and produces the one; it sublates itself and is the negative of itself: repulsion',
    clauses: [
      'assert(attractionIsIdealityAndPositingOfOne(true))',
      'assert(negatesAndProducesOne(true))',
      'assert(attractionSublatesItself(true))',
      'assert(attractionBecomesRepulsion(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Attraction_To_Repulsion', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c11-completion-and-mediation',
    chunkId: 'bfs-ra-c-connection-3-transition-to-quantity',
    label: 'Completion: one connects to itself infinitely (negation of negation) and mediates by repelling itself as many, sublating otherness',
    clauses: [
      'assert(beingForItselfCompleted(true))',
      'assert(infiniteSelfConnection(true))',
      'assert(negationOfNegation(true))',
      'assert(repelsItselfAsMany(true))',
      'assert(sublatesOthernessIntoSelfConnection(true))'
    ],
    predicates: [{ name: 'RA_Conn3_Completion_Mediation', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c12-process-only-as-sublated',
    chunkId: 'bfs-ra-c-connection-3-transition-to-quantity',
    label: 'Beginning/result as immediate vanish; the one is only a process that posits it as sublated from all sides',
    clauses: [
      'assert(beginningAsImmediateVanishes(true))',
      'assert(resultAsImmediateOneVanishes(true))',
      'assert(onlyAsSublatedProcess(true))'
    ],
    predicates: [{ name: 'RA_Conn3_Sublated_Process', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c13-relative-to-infinite-mediation',
    chunkId: 'bfs-ra-c-connection-3-transition-to-quantity',
    label: 'Relative sublating of external connection passes into infinite mediation (not an indifferent repulsion/attraction)',
    clauses: [
      'assert(relativeSublatingOfExternalConnection(true))',
      'assert(passesIntoInfiniteMediation(true))',
      'assert(notIndifferentRepulsionAttraction(true))'
    ],
    predicates: [{ name: 'RA_Conn3_Infinite_Mediation', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c14-becoming-collapses-into-immediacy',
    chunkId: 'bfs-ra-c-connection-3-transition-to-quantity',
    label: 'Becoming, unstable in its moments, collapses (goes-together-with-itself) into simple immediacy',
    clauses: [
      'assert(becomingWithUnstableMoments(true))',
      'assert(collapseIntoSimpleImmediacy(true))'
    ],
    predicates: [{ name: 'RA_Conn3_Collapse_Immediacy', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c15-transition-to-quantity',
    chunkId: 'bfs-ra-c-connection-3-transition-to-quantity',
    label: 'This being, in its new determination, is quantity (transition marker)',
    clauses: [
      'assert(resultingBeingIs("quantity"))',
      'tag(Transition,"to-quantity")'
    ],
    predicates: [{ name: 'RA_Conn3_Transition_Quantity', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c16-quality-immediacy-finitude',
    chunkId: 'bfs-ra-c-connection-4-review-transition',
    label: 'Quality: immediacy; limit/determinateness identical with being; alteration sublates the something (finite)',
    clauses: [
      'assert(qualitativeFundamentalImmediacy(true))',
      'assert(limitIdenticalWithBeing(true))',
      'assert(alterationSublatesSomething(true))',
      'tag(Determination,"finite")'
    ],
    predicates: [{ name: 'RA_Review_Quality_Finitude', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c17-distinction-as-external-otherness',
    chunkId: 'bfs-ra-c-connection-4-review-transition',
    label: 'Distinction falls outside unity (otherness), contradicting immediacy of qualitative self-reference',
    clauses: [
      'assert(distinctionFallsOutsideAsOtherness(true))',
      'assert(contradictsImmediacyOfSelfReference(true))'
    ],
    predicates: [{ name: 'RA_Review_Distinction_Otherness', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c18-bfi-negation-of-negation-elevation-to-unity',
    chunkId: 'bfs-ra-c-connection-4-review-transition',
    label: 'Being-for-itself as negation-of-negation realizes one/many and their connections, elevating quality to posited unity',
    clauses: [
      'assert(beingForItselfIsNegationOfNegation(true))',
      'assert(realizes(["one","many","their-connections"]))',
      'assert(elevatesQualityToPositedUnity(true))'
    ],
    predicates: [{ name: 'RA_Review_BFI_Elevation', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c19-enumeration-a-to-d',
    chunkId: 'bfs-ra-c-connection-4-review-transition',
    label: '(a–d) Being as mediated immediacy; existence as reflected determinateness; absolutely-determined-being; absolute in-itselfness',
    clauses: [
      'assert(beingAsMediatedImmediacy(true))',
      'assert(unityPermeatesDeterminaciesAsSublated(true))',
      'assert(existenceIsReflectedDeterminateness(true))',
      'assert(absolutelyDeterminedBeing(true))',
      'assert(absoluteInItselfness(true))'
    ],
    predicates: [{ name: 'RA_Review_A_to_D', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c20-enumeration-e-to-g-and-limit-none',
    chunkId: 'bfs-ra-c-connection-4-review-transition',
    label: '(e–g) The one; otherness as being-for-itself; being-for-itself persisting with one/in-itself sublated; absolute limit as limit which is none (indifferent)',
    clauses: [
      'assert(theOne(true))',
      'assert(othernessAsBeingForItself(true))',
      'assert(bfiPersistsAcrossDeterminateness(true))',
      'assert(oneAndInItselfPositedAsSublated(true))',
      'assert(absoluteLimitIsLimitWhichIsNone(true))',
      'assert(limitInBeingYetIndifferent(true))'
    ],
    predicates: [{ name: 'RA_Review_E_to_G_Limit', args: [] }],
    relations: []
  }
];

// Accessors
export function getChunk(oneBasedIndex: number): Chunk | null {
  return CANONICAL_CHUNKS[oneBasedIndex - 1] ?? null;
}

export function getChunkById(id: string): Chunk | null {
  return CANONICAL_CHUNKS.find((c) => c.id === id) ?? null;
}

export function getLogicalOpsForChunkId(chunkId: string): LogicalOperation[] {
  return LOGICAL_OPERATIONS.filter((op) => op.chunkId === chunkId);
}

export function getAllChunks(): Chunk[] {
  return CANONICAL_CHUNKS;
}

export function getLogicalOperations(): LogicalOperation[] {
  return LOGICAL_OPERATIONS;
}
