import type { Chunk, LogicalOperation } from './index'

export const CANONICAL_CHUNKS: Chunk[] = [
  {
    id: 'bfs-ra-c-connection-1',
    title: 'C. Repulsion and Attraction — c) The connection (I)',
    text: `The difference of the one and the many
has determined itself as a difference
of their mutual reference connecting them
which breaks down into two, repulsion and attraction,
each of which stands at first
outside the other on its own,
in such a way that the two are
essentially joined together nevertheless.
Their still indeterminate unity
must be brought out in greater detail.

As the fundamental determination of the one,
repulsion appears first, and it appears as immediate,
like its ones which are indeed generated by it
and yet are at the same time posited as immediate,
and it is therefore indifferent to the attraction
which is added to it externally as thus presupposed.
Rather, attraction is not presupposed by repulsion:
it is not supposed to have any part in the positing
and in the being of the latter, that is,
as if repulsion were not, already in it,
the negation of itself,
or the ones were not already negated in it.
In this way, we have repulsion in abstraction, by itself,
and attraction likewise holds out to the ones,
as each an existent, the side of an immediate existence
which comes to them by itself as an other.`,
    summary:
      'Difference becomes a split of mutual reference into repulsion and attraction: initially apart yet essentially joined. Repulsion appears first and immediate, generating ones posited as immediate, seeming indifferent to an externally added attraction. This abstraction ignores that repulsion already negates itself and the ones; set thus, repulsion is taken by itself while attraction shows up as an external immediate side for the ones.'
  },
  {
    id: 'bfs-ra-c-connection-2',
    title: 'C. Repulsion and Attraction — c) The connection (II)',
    text: `In the first place, that each presupposes itself,
that in its presupposition each refers only to itself,
this is already present in the way the still relative
repulsion and attraction behave at first.

Relative repulsion is the mutual repulsion
of many ones which are already at hand,
supposedly immediately given.
But that there be many ones,
this is repulsion itself;
any presupposition that it would have is
only its own positing.
Moreover, the determination of the being
that would accrue to the ones
apart from their being posited
(whereby they would already be)
belongs likewise to repulsion.
Repelling is that through which
the ones manifest themselves
and maintain themselves as ones;
through which they are as such.
Their being is their repulsion itself,
which is thus not some relative
existence against another other
but relates itself throughout only to itself.

Attraction is the positing of the one as such,
of the real one, with respect to which
the existence of the many is determined
as only a vanishing idealization.
Attraction thus directly presupposes itself;
it presupposes itself in the determination namely,
of the many ones to be an idealization,
the same ones which are otherwise supposed
to have existence for themselves and to repel others,
including therefore any other that attracts.
Against this determination of repulsion,
the ones do not attain ideality only through
the relation to attraction;
on the contrary, the ideality is presupposed:
it is the ideality of the ones
as an existent in itself,
inasmuch as they, as ones
(including the one conceived as attracting),
are not distinguished from one another
but are one and the same.

This self-presupposing of the two determinations, each for itself,
implies further that each contains within itself the other as moment.
Self-presupposing in general is the positing of oneself
in a one as the negative of oneself (repulsion),
and what is presupposed in this positing is
the same as that which presupposes (attraction).
That each is in itself only a moment,
this is the transition of each from itself into the other,
the negation of itself in the other
and the positing of itself as the other of itself.
The one, as such, is thus a coming-out-of-itself;
is itself only the positing of itself as its other, as the many.
And the many, for its part, is
only the falling back upon itself
and the positing of itself as its other, as a one,
and is in this equally only the connecting of itself to itself,
each continuing itself in its other.
Therefore, the coming-out-of-itself (repulsion)
and the self-positing-as-one (attraction)
are already inherently present as undivided.
But in the repulsion and attraction which are relative, that is,
which presuppose immediate, determinedly existent ones,
it is posited that the two are each, within it, this negation of itself,
and consequently also the continuity of itself in its other.
The repulsion of the determinedly existent ones is
the self-preservation of the one
through the mutual holding off of the others,
so that (1) the other ones are negated in it
(this is the side of its existence or of its being-for-another
and is therefore attraction as the ideality of the ones);
and (2) the one is in itself,
without reference to the others
(however, not only has the in-itself in general
long since passed over into being-for-itself;
the one in itself, according to its determination,
is the coming to be of many).
The attraction of the existent ones is their ideality
and the positing of the one, and in this,
as both the negating and the producing of the one,
attraction sublates itself,
and as a positing within it of the one,
is the negative of itself:
it is repulsion.`,
    summary:
      'Each determination self-presupposes and self-refers. Repulsion: the many are its own positing; being of the ones just is repulsion, relating only to itself. Attraction: posits the real one and presupposes the many as idealization; ones (including the attracting one) are the same. Hence each contains the other as a moment: one → many (coming-out), many → one (falling back). Even in relative forms, each is its own negation and its continuity in its other. Repulsion preserves the one while negating others (thus showing attraction as ideality) and holding an in-itself that becomes many. Attraction, as negating/producing the one, sublates itself into repulsion.'
  },
  {
    id: 'bfs-ra-c-connection-3-transition-to-quantity',
    title: 'C. Repulsion and Attraction — c) The connection (III): Result and transition to quantity',
    text: `With this, the development of being-for-itself
is completed and has attained its result.
In connecting itself to itself infinitely,
that is, as the posited negation of negation,
the one is the mediation by which it repels itself
as its absolute (that is, abstract) otherness (the many) from itself,
and in thus negatively connecting itself to this, its non-being,
it sublates it and is in it precisely only the connection to itself.
The one is only this becoming in which
the determination "it begins," that is,
its being posited as an immediate existent,
and equally that, as result,
it has restored itself as the one,
that is, the equally immediate and exclusive one, have vanished;
the process which it is, posits and contains it
from all sides only as something sublated.
The sublation, determined at first only as a relative sublating of
the connection to another existent,
a connection which is therefore itself not
an indifferent repulsion and attraction,
equally proves itself to pass over into
the infinite connection of mediation
through the negation of the external
connection of immediate and determinate existents,
and to have for result precisely that becoming
which, in the instability of its moments, is the collapse,
or rather the going-together-with-itself, into simple immediacy.
This being, according to the determination
which it has now acquired, is quantity.`,
    summary:
      'Result: Being-for-itself completes itself. The one, as negation-of-negation, mediates by repelling itself as many and sublating this otherness into self-connection. Both beginning and result as immediate ones vanish; the one exists only as a sublated process. Relative repulsion/attraction passes into infinite mediation; becoming collapses into simple immediacy. This new being is quantity.'
  },
  {
    id: 'bfs-ra-c-connection-4-review-transition',
    title: 'C. Repulsion and Attraction — c) Review of the transition (Quality → Quantity)',
    text: `And this concludes Quality and has an interesting transition into Quantity.

If we briefly review the moments
of this transition of quality into quantity,
we find that the qualitative has being and immediacy
for its fundamental determination,
and the limit and the determinateness are
in this immediacy so identical with the being of something,
that the something itself vanishes
along with its alteration;
as thus posited, it is determined as finite.
Because of the immediacy of this unity
in which the distinction has disappeared,
although it is implicitly present in
the unity of being and nothing,
the distinction falls outside
that unity as otherness in general.
This reference to the other contradicts the immediacy
in which qualitative determinateness is self-reference.
This otherness is sublated in
the infinity of the being-for-itself,
the being-for-itself that has realized
the distinction implicitly present in it
in the negation of negation:
has realized it as the one and the many
and as their connecting references,
and has also elevated the qualitative to true unity,
that is, a unity which is no longer immediate
but posited as accordant with itself.

This unity is, therefore,
(a) being, only as affirmative, that is,
immediacy self-mediated through the negation of negation:
being is posited as a unity permeating
its determinacies, limits, etc.,
which are posited in it as sublated;
(b) existence:
in this determination it is negation
or determinateness as moment of
the affirmative being;
yet this determinateness is no longer
immediate but reflected into itself,
refers not to another but to itself;
(c) absolutely-determined-being,
(d) absolute in-itselfness,
(e) the one;
(f) otherness as such is itself being-for-itself;
(g) being-for-itself:
as that being which persists
across the determinateness
and in which the one
and even the being-determined-in-itself
are posited as sublated.
The one is simultaneously determined
as having gone beyond itself and as unity;
the one, the absolutely determined limit,
is consequently posited as a limit which is none,
a limit which is in being but is indifferent to it.`,
    summary:
      'Review: Quality’s immediacy makes limit identical with being, so alteration sublates the something (finitude). Distinction falls outside as otherness, contradicting immediacy; being-for-itself (negation of negation) realizes the one, the many, and their connections, elevating quality to posited unity. Enumerated unity: (a) mediated being; (b) existence as reflected determinateness; (c) absolutely determined being; (d) absolute in-itselfness; (e) the one; (f) otherness as being-for-itself; (g) being-for-itself persisting across determinateness with one and in-itself sublated. The one as absolute limit is a limit that is none—indifferent in being—signaling quantity.'
  }
]

export const LOGICAL_OPERATIONS: LogicalOperation[] = [
  {
    id: 'bfs-op-ra-c1-split-and-joined',
    chunkId: 'bfs-ra-c-connection-1',
    label: 'Difference of one/many → difference of mutual reference: repulsion and attraction, apart yet essentially joined',
    clauses: [
      'assert(differenceBecomesReferenceSplit(true))',
      'assert(twoDeterminations(["repulsion","attraction"]))',
      'assert(initiallyOutsideEachOther(true))',
      'assert(essentiallyJoined(true))',
      'assert(unityStillIndeterminate(true))'
    ],
    predicates: [{ name: 'RA_Connection_SplitJoined', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c2-repulsion-first-immediate',
    chunkId: 'bfs-ra-c-connection-1',
    label: 'Repulsion as fundamental appears first and immediate; its ones are generated yet posited as immediate; indifference to external attraction',
    clauses: [
      'assert(repulsionFundamental(true))',
      'assert(repulsionAppearsImmediate(true))',
      'assert(generatesOnesPositedImmediate(true))',
      'assert(indifferentToExternallyAddedAttraction(true))'
    ],
    predicates: [{ name: 'RA_Connection_RepulsionImmediate', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c3-not-presupposed-yet-already-negation',
    chunkId: 'bfs-ra-c-connection-1',
    label: 'Taking repulsion by itself denies attraction as presupposed, yet repulsion already negates itself and the ones in it',
    clauses: [
      'assert(treatAttractionAsNotPresupposed(true))',
      'assert(repulsionAlreadyNegationOfItself(true))',
      'assert(onesAlreadyNegatedInRepulsion(true))',
      'assert(repulsionInAbstraction(true))',
      'assert(attractionAsExternalImmediateSide(true))'
    ],
    predicates: [{ name: 'RA_Connection_AbstractView', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c4-repulsion-self-presupposes',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Repulsion self-presupposes: the many are its own positing; being of ones is repulsion; pure self-relation',
    clauses: [
      'assert(relativeRepulsionIsMutualAmongGivenOnes(true))',
      'assert(manyOnesAreRepulsionsOwnPositing(true))',
      'assert(anyPresuppositionBelongsToRepulsion(true))',
      'assert(beingOfOnesIsRepulsion(true))',
      'assert(repulsionRelatesOnlyToItself(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Repulsion_SelfPresupposes', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c5-attraction-self-presupposes',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Attraction posits the real one; directly presupposes itself by presupposing the many as idealization (all ones the same)',
    clauses: [
      'assert(attractionPositsRealOne(true))',
      'assert(directSelfPresupposition(true))',
      'assert(presupposesManyAsIdealization(true))',
      'assert(onesOtherwiseExistAndRepel(true))',
      'assert(onesIncludingAttractingAreSame(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Attraction_SelfPresupposes', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c6-each-contains-the-other-as-moment',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Self-presupposing ⇒ each contains the other as moment; definition of self-presupposing (repulsion/attraction)',
    clauses: [
      'assert(selfPresupposingImpliesContainsOtherMoment(true))',
      'assert(selfPresupposingIsPositingSelfAsNegativeOfSelf(true))',
      'assert(whatIsPresupposedEqualsPresupposing(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Moment_Inclusion', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c7-transitions-one-many',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Transitions: one → many (coming-out-of-itself); many → one (falling back); continuity in its other',
    clauses: [
      'assert(onePositsItselfAsMany(true))',
      'assert(manyPositThemselvesAsOne(true))',
      'assert(continuityInItsOther(true))',
      'assert(comingOutIsRepulsion(true))',
      'assert(selfPositingAsOneIsAttraction(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Transitions', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c8-relative-forms-negate-self-and-continue',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'In relative forms (with determinate ones), each is its own negation and its continuity in the other',
    clauses: [
      'assert(relativeRepulsionAndAttractionPositNegationOfSelf(true))',
      'assert(eachContinuesItselfInOther(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Relative_Negation_Continuity', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c9-repulsion-two-sides',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Repulsion of determinate ones: (1) negates others (existence/for-another = attraction as ideality); (2) the one is in-itself (yet becomes many)',
    clauses: [
      'assert(negatesOtherOnes(true))',
      'assert(sideIsExistenceOrForAnother(true))',
      'assert(thusAttractionAsIdeality(true))',
      'assert(oneIsInItselfWithoutReference(true))',
      'assert(inItselfAsBecomingMany(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Repulsion_TwoSides', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c10-attraction-sublates-into-repulsion',
    chunkId: 'bfs-ra-c-connection-2',
    label: 'Attraction (ideality/positing of the one) both negates and produces the one; it sublates itself and is the negative of itself: repulsion',
    clauses: [
      'assert(attractionIsIdealityAndPositingOfOne(true))',
      'assert(negatesAndProducesOne(true))',
      'assert(attractionSublatesItself(true))',
      'assert(attractionBecomesRepulsion(true))'
    ],
    predicates: [{ name: 'RA_Conn2_Attraction_To_Repulsion', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c11-completion-and-mediation',
    chunkId: 'bfs-ra-c-connection-3-transition-to-quantity',
    label: 'Completion: one connects to itself infinitely (negation of negation) and mediates by repelling itself as many, sublating otherness',
    clauses: [
      'assert(beingForItselfCompleted(true))',
      'assert(infiniteSelfConnection(true))',
      'assert(negationOfNegation(true))',
      'assert(repelsItselfAsMany(true))',
      'assert(sublatesOthernessIntoSelfConnection(true))'
    ],
    predicates: [{ name: 'RA_Conn3_Completion_Mediation', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c12-process-only-as-sublated',
    chunkId: 'bfs-ra-c-connection-3-transition-to-quantity',
    label: 'Beginning/result as immediate vanish; the one is only a process that posits it as sublated from all sides',
    clauses: [
      'assert(beginningAsImmediateVanishes(true))',
      'assert(resultAsImmediateOneVanishes(true))',
      'assert(onlyAsSublatedProcess(true))'
    ],
    predicates: [{ name: 'RA_Conn3_Sublated_Process', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c13-relative-to-infinite-mediation',
    chunkId: 'bfs-ra-c-connection-3-transition-to-quantity',
    label: 'Relative sublating of external connection passes into infinite mediation (not an indifferent repulsion/attraction)',
    clauses: [
      'assert(relativeSublatingOfExternalConnection(true))',
      'assert(passesIntoInfiniteMediation(true))',
      'assert(notIndifferentRepulsionAttraction(true))'
    ],
    predicates: [{ name: 'RA_Conn3_Infinite_Mediation', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c14-becoming-collapses-into-immediacy',
    chunkId: 'bfs-ra-c-connection-3-transition-to-quantity',
    label: 'Becoming, unstable in its moments, collapses (goes-together-with-itself) into simple immediacy',
    clauses: [
      'assert(becomingWithUnstableMoments(true))',
      'assert(collapseIntoSimpleImmediacy(true))'
    ],
    predicates: [{ name: 'RA_Conn3_Collapse_Immediacy', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c15-transition-to-quantity',
    chunkId: 'bfs-ra-c-connection-3-transition-to-quantity',
    label: 'This being, in its new determination, is quantity (transition marker)',
    clauses: [
      'assert(resultingBeingIs("quantity"))',
      'tag(Transition,"to-quantity")'
    ],
    predicates: [{ name: 'RA_Conn3_Transition_Quantity', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c16-quality-immediacy-finitude',
    chunkId: 'bfs-ra-c-connection-4-review-transition',
    label: 'Quality: immediacy; limit/determinateness identical with being; alteration sublates the something (finite)',
    clauses: [
      'assert(qualitativeFundamentalImmediacy(true))',
      'assert(limitIdenticalWithBeing(true))',
      'assert(alterationSublatesSomething(true))',
      'tag(Determination,"finite")'
    ],
    predicates: [{ name: 'RA_Review_Quality_Finitude', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c17-distinction-as-external-otherness',
    chunkId: 'bfs-ra-c-connection-4-review-transition',
    label: 'Distinction falls outside unity (otherness), contradicting immediacy of qualitative self-reference',
    clauses: [
      'assert(distinctionFallsOutsideAsOtherness(true))',
      'assert(contradictsImmediacyOfSelfReference(true))'
    ],
    predicates: [{ name: 'RA_Review_Distinction_Otherness', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c18-bfi-negation-of-negation-elevation-to-unity',
    chunkId: 'bfs-ra-c-connection-4-review-transition',
    label: 'Being-for-itself as negation-of-negation realizes one/many and their connections, elevating quality to posited unity',
    clauses: [
      'assert(beingForItselfIsNegationOfNegation(true))',
      'assert(realizes(["one","many","their-connections"]))',
      'assert(elevatesQualityToPositedUnity(true))'
    ],
    predicates: [{ name: 'RA_Review_BFI_Elevation', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c19-enumeration-a-to-d',
    chunkId: 'bfs-ra-c-connection-4-review-transition',
    label: '(a–d) Being as mediated immediacy; existence as reflected determinateness; absolutely-determined-being; absolute in-itselfness',
    clauses: [
      'assert(beingAsMediatedImmediacy(true))',
      'assert(unityPermeatesDeterminaciesAsSublated(true))',
      'assert(existenceIsReflectedDeterminateness(true))',
      'assert(absolutelyDeterminedBeing(true))',
      'assert(absoluteInItselfness(true))'
    ],
    predicates: [{ name: 'RA_Review_A_to_D', args: [] }],
    relations: []
  },
  {
    id: 'bfs-op-ra-c20-enumeration-e-to-g-and-limit-none',
    chunkId: 'bfs-ra-c-connection-4-review-transition',
    label: '(e–g) The one; otherness as being-for-itself; being-for-itself persisting with one/in-itself sublated; absolute limit as limit which is none (indifferent)',
    clauses: [
      'assert(theOne(true))',
      'assert(othernessAsBeingForItself(true))',
      'assert(bfiPersistsAcrossDeterminateness(true))',
      'assert(oneAndInItselfPositedAsSublated(true))',
      'assert(absoluteLimitIsLimitWhichIsNone(true))',
      'assert(limitInBeingYetIndifferent(true))'
    ],
    predicates: [{ name: 'RA_Review_E_to_G_Limit', args: [] }],
    relations: []
  }
]
