/**
 * TopicMap for being-for-itself.txt - The Being-for-Itself in Measure
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - being-for-itself-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const BEING_FOR_ITSELF_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/measure/specific-quantity/sources/being-for-itself.txt',
  'Hegel\'s Science of Logic - Measure',
  'The Being-for-Itself in Measure',
  [
    createTopicMapEntry(
      'sq-c-1-qualities-immediate-vs-specified',
      'Qualities immediate vs specified — space and time example',
      [3, 30],
      'Specified measure: quantitative moment qualitatively determined (ratio of powers), moments of one measure-determinateness. Qualities posited immediately, diverse, not related as quantitative determinacies. Qualitative moment specifies determinateness of magnitude, not itself. Immediate quality has existence subsisting on its own. Space and time outside specification = space in general, time in general, subsisting independently.',
      [
        'specified measure',
        'quantitative moment',
        'qualitatively determined',
        'ratio of powers',
        'moments',
        'one measure-determinateness',
        'qualitative nature',
        'qualities',
        'posited immediately',
        'diverse',
        'not related',
        'manner',
        'quantitative determinacies',
        'outside their relation',
        'neither meaning nor existence',
        'qualitative moment',
        'disguises itself',
        'specifying',
        'determinateness of magnitude',
        'within the latter',
        'posited',
        'for itself',
        'immediate quality',
        'posits the magnitude',
        'non-indifferent',
        'connection with its other',
        'existence subsisting on its own',
        'space and time',
        'outside that specification',
        'quantitative determinateness',
        'motion of falling bodies',
        'absolutely free motion',
        'space in general',
        'time in general',
        'space subsisting on its own',
        'outside and without the duration of time',
        'time flowing on its own',
        'independently of space',
      ],
      { section: 'The Being-for-Itself in Measure', order: 1 }
    ),

    createTopicMapEntry(
      'sq-c-2-immediacy-and-direct-ratio',
      'Immediacy and direct ratio — moment of belonging to measure',
      [32, 50],
      'Immediacy of qualitative moment bound up with quantitative immediacy, indifference to measure-relation. Immediate quality has immediate quantum. Specific measure has external alteration in arithmetical progression (empirical determination). Quality and quantum extend outside measure but connected; immediacy = moment of belonging. Immediate qualities belong to measure, stand in direct ratio (immediate measure).',
      [
        'immediacy',
        'qualitative moment',
        'as against',
        'specific measure-relation',
        'bound up',
        'quantitative immediacy',
        'indifference',
        'measure-relation',
        'quantitative element',
        'immediate quality',
        'immediate quantum',
        'specific measure',
        'side',
        'external alteration',
        'advances',
        'merely arithmetical progression',
        'undisturbed',
        'external',
        'merely empirical',
        'determination of magnitude',
        'quality and quantum',
        'extend outside measure',
        'connected with it',
        'immediacy',
        'moment',
        'belonging to measure',
        'immediate qualities',
        'belong to measure',
        'likewise connected',
        'stand in a ratio',
        'outside the specified one',
        'power determination',
        'direct ratio',
        'immediate measure',
        'conclusion',
        'consequences',
        'must now be indicated',
      ],
      { section: 'The Being-for-Itself in Measure', order: 2 }
    ),

    createTopicMapEntry(
      'sq-c-3-empirical-coefficient',
      'Empirical coefficient — being-for-itself as immediate quantum',
      [52, 141],
      'Immediately determined quantum externally given in connection with specific measure. Immediacy = negation of qualitative measure. Negation and return to immediate quantitative determinateness present in qualitatively determined relation. Exponent = being-for-itself (absolutely determined, only in itself). As existence = simple immediate quantum (quotient/exponent of direct ratio). Appears as empirical unit. Motion of falling bodies: s = at^2 (specifically determinate ratio). Direct ratio = reflectively formal velocity (not specifically determined, no concrete existence). Empirical quantum attributed to gravity (no connection with specification/powers). Immediate measure = empirical appearances. Empirical coefficient = being-for-itself (moment, immediate). Other moment = development, specific measure-determinateness. Gravity = force of nature, ratio determined by nature of time and space, specification = ratio of powers. Direct ratio = mechanical relation, reflectively formal velocity.',
      [
        'immediately determined quantum',
        'moment of measure',
        'implicitly grounded',
        'conceptual nexus',
        'connection with specific measure',
        'externally given',
        'immediacy',
        'posited',
        'negation',
        'determination of qualitative measure',
        'same immediacy',
        'sides of the determination of measure',
        'self-subsisting qualities',
        'negation',
        'return',
        'immediate quantitative determinateness',
        'qualitatively determined relation',
        'relation of distinct terms',
        'entails',
        'connection',
        'one determinateness',
        'quantitative sphere',
        'distinction',
        'determination of the relation',
        'determinateness',
        'quantum',
        'negation of the distinct',
        'qualitatively determined sides',
        'exponent',
        'being-for-itself',
        'absolutely determined being',
        'only in itself',
        'existence',
        'simple immediate quantum',
        'quotient',
        'exponent of a ratio',
        'sides of measure',
        'taken as direct',
        'quantitative side of measure',
        'empirical unit',
        'motion of falling bodies',
        'spaces traversed',
        'proportional',
        'square of the elapsed time',
        's = at^2',
        'specifically determinate ratio',
        'space and time',
        'direct ratio',
        'mutually indifferent qualities',
        'ratio of the space traversed',
        'first moment of time',
        'coefficient',
        'a',
        'remains',
        'succeeding time-points',
        'unit of the amount',
        'determined',
        'specifying measure',
        'ordinary quantum',
        'unit counts',
        'exponent of that direct ratio',
        'merely imagined',
        'the bad',
        'reflectively formal velocity',
        'not specifically determined',
        'concept',
        'velocity',
        'does not have concrete existence',
        'previously mentioned',
        'falling body',
        'end of a moment of time',
        'velocity',
        'ascribed to',
        'first temporal moment',
        'fall',
        'so-called temporal moment',
        'assumed unit',
        'no existence',
        'atomic point',
        'beginning of the motion',
        'alleged smallness',
        'would make no difference',
        'magnitude',
        'specified',
        'law of falling bodies',
        'empirical quantum',
        'attributed to',
        'force of gravity',
        'force',
        'no connection',
        'specification at hand',
        'determinateness of powers',
        'determinateness characteristic of measure',
        'immediate moment',
        'motion of falling bodies',
        'amount',
        'fifteen spatial units',
        'assumed as feet',
        'enter into',
        'one unit of time',
        'second',
        'so-called first unit',
        'immediate measure',
        'size of human limbs',
        'distances',
        'diameters of planets',
        'determination of such measures',
        'falls elsewhere',
        'qualitative determination of measure',
        'law itself of falling bodies',
        'such numbers',
        'depend',
        'merely immediate',
        'therefore empirical',
        'appearances of a measure',
        'concrete sciences',
        'yet to give us any information',
        'concerned',
        'conceptual determination',
        'any determination of measure',
        'empirical coefficient',
        'constitutes',
        'being-for-itself',
        'moment of the being-for-itself',
        'in principle',
        'therefore as immediate',
        'other moment',
        'development',
        'being-for-itself',
        'specific measure-determinateness',
        'sides',
        'second moment',
        'ratio expressing',
        'motion of falling bodies',
        'motion',
        'still half conditioned',
        'half free',
        'gravity',
        'regarded as',
        'force of nature',
        'ratio',
        'determined by',
        'nature of time and space',
        'specification',
        'ratio of powers',
        'falls in it',
        'other moment mentioned above',
        'simple direct ratio',
        'expresses',
        'mechanical relation',
        'time and space',
        'reflectively formal velocity',
        'externally produced',
        'externally determined',
      ],
      { section: 'The Being-for-Itself in Measure', order: 3 }
    ),

    createTopicMapEntry(
      'sq-c-4-unity-of-measures',
      'Unity of immediate and specified measures — real being-for-itself',
      [143, 190],
      'Measure = specified quantitative relation, qualitative, has external quantum. Quantum = determining moment of relation, exponent (invariable, of direct ratio). Direct ratio anticipated but no concrete existence. Now realized: sides both measures (immediate/external vs internally specified), measure = unity. Measure contains relation where magnitudes posited as determined and non-indifferent. Determinateness immanent and self-subsisting, collapsed into being-for-itself (immediate quantum, exponent of direct ratio). Self-determination negated. Negative unity = real being-for-itself, something = unity of qualities in measure relation, complete self-subsistence. Twofold existence: self-subsisting whole = repulsion into distinct self-subsisting somethings, qualitative nature and subsistence in determinateness of measure.',
      [
        'measure',
        'taken on',
        'determination',
        'specified quantitative relation',
        'qualitative',
        'has within it',
        'usual external quantum',
        'quantum',
        'not a quantum in general',
        'essentially',
        'determining moment',
        'relation as such',
        'exponent',
        'immediacy',
        'determinateness',
        'invariable exponent',
        'consequently',
        'exponent',
        'already mentioned direct ratio',
        'same qualities',
        'reciprocal quantitative relation',
        'specifically determined',
        'ratio',
        'example of measure',
        'motion of falling bodies',
        'direct ratio',
        'as it were',
        'anticipated',
        'assumed as given',
        'remarked',
        'motion',
        'does not have concrete existence',
        'matter',
        'now realized',
        'sides',
        'both measures',
        'distinguished',
        'immediate and external',
        'internally specified',
        'measure itself',
        'unity of the two',
        'constitutes',
        'further determination',
        'unity of its two sides',
        'measure contains',
        'relation',
        'magnitudes',
        'by virtue of',
        'nature of the qualities',
        'posited as',
        'determined and non-indifferent',
        'determinateness',
        'entirely immanent',
        'self-subsisting',
        'collapsed into',
        'being-for-itself',
        'immediate quantum',
        'exponent of a direct ratio',
        'self-determination',
        'negated',
        'immediate quantum',
        'its other',
        'measure',
        'final self-existent determinateness',
        'conversely',
        'immediate measure',
        'ought to be',
        'internally qualitative',
        'assumes',
        'truly qualitative determinateness',
        'only in that other',
        'negative unity',
        'real being-for-itself',
        'category',
        'something',
        'unity of qualities',
        'relation of measure',
        'complete self-subsistence',
        'two resulting diverse relations',
        'immediately yield',
        'twofold existence',
        'more precisely',
        'self-subsisting whole',
        'being that exists for itself',
        'as such',
        'in itself',
        'repulsion',
        'distinct self-subsisting',
        'somethings',
        'qualitative nature',
        'subsistence',
        'materiality',
        'lies',
        'determinateness of measure',
      ],
      { section: 'The Being-for-Itself in Measure', order: 4 }
    ),
  ],
  {
    sectionDescription: 'The Being-for-Itself in Measure - Qualities immediate vs specified (space and time subsisting independently). Immediacy and direct ratio (moment of belonging to measure). Empirical coefficient (being-for-itself as immediate quantum, motion of falling bodies example). Unity of immediate and specified measures (real being-for-itself, twofold existence, repulsion into distinct somethings).',
  }
);

