import type { DialecticIR, DialecticState } from '@schema/dialectic';

// Generated by src/relative/core/compiler/generate-being-ir.ts
const stateBecoming1: DialecticState = {
  "id": "becoming-1",
  "title": "Unity of being and nothing as immediate vanishing",
  "concept": "BecomingUnity",
  "phase": "quality",
  "moments": [
    {
      "name": "sameYetDistinct",
      "definition": "Being and nothing are absolutely distinct yet inseparable and immediately vanish into one another",
      "type": "mediation"
    },
    {
      "name": "immediateTransition",
      "definition": "Their truth is not either side but the movement of passing-over",
      "type": "process",
      "relation": "contains",
      "relatedTo": "sameYetDistinct"
    }
  ],
  "invariants": [
    {
      "id": "becoming-1-inv-1",
      "constraint": "truth is movement, not isolated being or isolated nothing",
      "predicate": "truthAsMovement(being, nothing)"
    },
    {
      "id": "becoming-1-inv-2",
      "constraint": "distinction and inseparability are simultaneously maintained",
      "predicate": "distinctAndInseparable(being, nothing)"
    }
  ],
  "forces": [
    {
      "id": "becoming-1-force-1",
      "description": "Immediate vanishing requires articulation as concrete interpenetrating moments",
      "type": "mediation",
      "trigger": "movement.requiresArticulation = true",
      "effect": "interpenetratingMoments.formed = true",
      "targetState": "becoming-4"
    }
  ],
  "transitions": [
    {
      "id": "becoming-1-trans-1",
      "from": "becoming-1",
      "to": "becoming-4",
      "mechanism": "mediation",
      "description": "From abstract unity to determinate coming-to-be and ceasing-to-be"
    }
  ],
  "nextStates": [
    "becoming-4"
  ],
  "previousStates": [
    "nothing-6"
  ],
  "provenance": {
    "topicMapId": "becoming-1",
    "lineRange": {
      "start": 11,
      "end": 30
    },
    "section": "C.1. Unity of being and nothing",
    "order": 1
  },
  "description": "Pure being and pure nothing are therefore the same. The truth is neither being nor nothing, but rather that being has passed over into nothing and nothing into being; 'has passed over,' not passes over. But the truth is just as much that they are not without distinction; it is rather that they are not the same, that they are absolutely distinct yet equally unseparated and inseparable, and that each immediately vanishes in its opposite. Their truth is therefore this movement of the immediate vanishing of the one into the other: becoming, a movement in which the two are distinguished, but by a distinction which has just as immediately dissolved itself.",
  "keyPoints": [
    "Pure being and pure nothing are the same",
    "Truth is neither being nor nothing",
    "Being has passed over into nothing and nothing into being",
    "'Has passed over,' not passes over",
    "They are not without distinction",
    "They are not the same, absolutely distinct",
    "Yet equally unseparated and inseparable",
    "Each immediately vanishes in its opposite",
    "Truth is movement of immediate vanishing of one into the other",
    "Becoming: movement in which two are distinguished",
    "Distinction has just as immediately dissolved itself"
  ]
};
const stateBecoming4: DialecticState = {
  "id": "becoming-4",
  "title": "Interpenetration of coming-to-be and ceasing-to-be",
  "concept": "InterpenetratingBecoming",
  "phase": "quality",
  "moments": [
    {
      "name": "doubleDirection",
      "definition": "Coming-to-be and ceasing-to-be are opposed directions that interpenetrate and paralyze each other",
      "type": "process"
    },
    {
      "name": "selfSublation",
      "definition": "Each side sublates itself internally and thus contains its opposite in itself",
      "type": "sublation",
      "relation": "transitions",
      "relatedTo": "doubleDirection"
    }
  ],
  "invariants": [
    {
      "id": "becoming-4-inv-1",
      "constraint": "each direction includes its opposite as internal moment",
      "predicate": "internalOpposition(comingToBe, ceasingToBe)"
    },
    {
      "id": "becoming-4-inv-2",
      "constraint": "becoming remains one process across both directions",
      "predicate": "singleProcess(becoming)"
    }
  ],
  "forces": [
    {
      "id": "becoming-4-force-1",
      "description": "Self-sublation collapses unrest into a quiescent result that can stand as immediate",
      "type": "sublation",
      "trigger": "selfSublation.complete = true",
      "effect": "quiescentResult.emerges = true",
      "targetState": "becoming-7"
    }
  ],
  "transitions": [
    {
      "id": "becoming-4-trans-1",
      "from": "becoming-4",
      "to": "becoming-7",
      "mechanism": "sublation",
      "description": "From interpenetrating unrest to quiescent simplicity"
    }
  ],
  "nextStates": [
    "becoming-7"
  ],
  "previousStates": [
    "becoming-1"
  ],
  "provenance": {
    "topicMapId": "becoming-4",
    "lineRange": {
      "start": 62,
      "end": 82
    },
    "section": "C.2. The moments of becoming",
    "order": 2
  },
  "description": "Both are the same, becoming, and even as directions that are so different they interpenetrate and paralyze each other. The one is ceasing-to-be; being passes over into nothing, but nothing is just as much the opposite of itself, the passing-over into being, coming-to-be. This coming-to-be is the other direction; nothing goes over into being, but being equally sublates itself and is rather the passing-over into nothing; it is ceasing-to-be. They do not sublate themselves reciprocally [the one sublating the other externally] but each rather sublates itself in itself and is within it the opposite of itself.",
  "keyPoints": [
    "Both are the same, becoming",
    "Directions interpenetrate and paralyze each other",
    "One is ceasing-to-be: being passes over into nothing",
    "Nothing is opposite of itself: passing-over into being, coming-to-be",
    "Coming-to-be is other direction: nothing goes over into being",
    "Being equally sublates itself: passing-over into nothing, ceasing-to-be",
    "They do not sublate themselves reciprocally",
    "Each rather sublates itself in itself",
    "Each is within it the opposite of itself"
  ]
};
const stateBecoming7: DialecticState = {
  "id": "becoming-7",
  "title": "Quiescent simplicity as transition to existence",
  "concept": "ExistentResult",
  "phase": "quality",
  "moments": [
    {
      "name": "quiescentUnity",
      "definition": "The unity of being and nothing becomes simple and stands as immediate determination",
      "type": "determination"
    },
    {
      "name": "existentShape",
      "definition": "This immediate unity has the form of existence",
      "type": "quality",
      "relation": "transitions",
      "relatedTo": "quiescentUnity"
    }
  ],
  "invariants": [
    {
      "id": "becoming-7-inv-1",
      "constraint": "result is not relapse into pure being or pure nothing",
      "predicate": "notRelapse(result, pureBeing, pureNothing)"
    }
  ],
  "forces": [
    {
      "id": "becoming-7-force-1",
      "description": "The quiescent unity passes over into the chapter of existence",
      "type": "passover",
      "trigger": "unity.asImmediate = true",
      "effect": "existenceChapter.initiated = true",
      "targetState": "existence-1"
    }
  ],
  "transitions": [
    {
      "id": "becoming-7-trans-1",
      "from": "becoming-7",
      "to": "existence-1",
      "mechanism": "passover",
      "description": "Becoming sublates into existence"
    }
  ],
  "nextStates": [
    "existence-1"
  ],
  "previousStates": [
    "becoming-4"
  ],
  "provenance": {
    "topicMapId": "becoming-7",
    "lineRange": {
      "start": 101,
      "end": 108
    },
    "section": "C.3. Sublation of becoming",
    "order": 3
  },
  "description": "It is the unity of being and nothing that has become quiescent simplicity. But this quiescent simplicity is being, yet no longer for itself but as determination of the whole. Becoming, as transition into the unity of being and nothing, a unity which is as existent or has the shape of the one-sided immediate unity of these moments, is existence.",
  "keyPoints": [
    "Unity of being and nothing that has become quiescent simplicity",
    "Quiescent simplicity is being",
    "No longer for itself but as determination of whole",
    "Becoming as transition into unity of being and nothing",
    "Unity which is as existent",
    "Has shape of one-sided immediate unity of these moments",
    "Is existence"
  ]
};

export const becomingIR: DialecticIR = {
  id: "becoming-ir",
  title: "Becoming IR: Unity of Being and Nothing",
  section: "BEING - QUALITY - C. Becoming",
  states: [
    stateBecoming1,
    stateBecoming4,
    stateBecoming7,
  ],
  metadata: {
  "sourceFile": "becoming.txt",
  "totalStates": 3,
  "cpuGpuMapping": {
    "becoming-1": "quality",
    "becoming-4": "quality",
    "becoming-7": "quality"
  }
},
};

export const becomingStates = {
  "becoming-1": stateBecoming1,
  "becoming-4": stateBecoming4,
  "becoming-7": stateBecoming7,
};
