import type { DialecticIR, DialecticState } from '@schema/dialectic';

// Generated by src/tools/generate-being-ir.ts
const stateNothing1: DialecticState = {
  "id": "nothing-1",
  "title": "Pure nothing as complete emptiness",
  "concept": "PureNothing",
  "phase": "quality",
  "moments": [
    {
      "name": "emptySelfEquality",
      "definition": "Nothing is simple equality with itself as complete absence of determination",
      "type": "negation"
    },
    {
      "name": "absenceOfDistinction",
      "definition": "No internal distinction is available within pure nothing",
      "type": "quality"
    }
  ],
  "invariants": [
    {
      "id": "nothing-1-inv-1",
      "constraint": "nothing has no positive content",
      "predicate": "not(hasContent(nothing))"
    },
    {
      "id": "nothing-1-inv-2",
      "constraint": "emptiness remains complete and undifferentiated",
      "predicate": "completeUndifferentiated(emptiness)"
    }
  ],
  "forces": [
    {
      "id": "nothing-1-force-1",
      "description": "Because it is thinkable only as empty activity, nothing moves into mediated expression",
      "type": "mediation",
      "trigger": "nothing.isThoughtOrIntuited = true",
      "effect": "emptyActivity.explicit = true",
      "targetState": "nothing-4"
    }
  ],
  "transitions": [
    {
      "id": "nothing-1-trans-1",
      "from": "nothing-1",
      "to": "nothing-4",
      "mechanism": "mediation",
      "description": "From pure emptiness to empty intuiting/thinking"
    }
  ],
  "nextStates": [
    "nothing-4"
  ],
  "previousStates": [
    "being-6"
  ],
  "provenance": {
    "topicMapId": "nothing-1",
    "lineRange": {
      "start": 12,
      "end": 16
    },
    "section": "B. NOTHING",
    "order": 1
  },
  "description": "Nothing, pure nothingness; it is simple equality with itself, complete emptiness, complete absence of determination and content; lack of all distinction within.",
  "keyPoints": [
    "Nothing, pure nothingness",
    "Simple equality with itself",
    "Complete emptiness",
    "Complete absence of determination and content",
    "Lack of all distinction within"
  ]
};
const stateNothing4: DialecticState = {
  "id": "nothing-4",
  "title": "Nothing as empty intuiting and thinking",
  "concept": "ThoughtNothing",
  "phase": "quality",
  "moments": [
    {
      "name": "emptyActivity",
      "definition": "To intuit or think nothing is the empty activity of intuiting and thinking itself",
      "type": "mediation"
    },
    {
      "name": "sameAsBeing",
      "definition": "This empty activity has the same determinationlessness as pure being",
      "type": "reflection",
      "relation": "transitions",
      "relatedTo": "emptyActivity"
    }
  ],
  "invariants": [
    {
      "id": "nothing-4-inv-1",
      "constraint": "nothing and pure being share identical determinacy profile",
      "predicate": "sameDeterminacy(nothing, pureBeing)"
    },
    {
      "id": "nothing-4-inv-2",
      "constraint": "empty intuition and empty thought are coextensive",
      "predicate": "coextensive(emptyIntuition, emptyThought)"
    }
  ],
  "forces": [
    {
      "id": "nothing-4-force-1",
      "description": "Recognized identity with being requires explicit dynamic unity rather than static equality",
      "type": "contradiction",
      "trigger": "identityWithBeing.recognized = true",
      "effect": "dynamicUnity.required = true",
      "targetState": "nothing-6"
    }
  ],
  "transitions": [
    {
      "id": "nothing-4-trans-1",
      "from": "nothing-4",
      "to": "nothing-6",
      "mechanism": "contradiction",
      "description": "Static identity gives way to transition as such"
    }
  ],
  "nextStates": [
    "nothing-6"
  ],
  "previousStates": [
    "nothing-1"
  ],
  "provenance": {
    "topicMapId": "nothing-2",
    "lineRange": {
      "start": 17,
      "end": 28
    },
    "section": "B. NOTHING",
    "order": 2
  },
  "description": "In so far as mention can be made here of intuiting and thinking, it makes a difference whether something or nothing is being intuited or thought. To intuit or to think nothing has therefore a meaning; the two are distinguished and so nothing is (concretely exists) in our intuiting or thinking; or rather it is the empty intuiting and thinking itself, like pure being. Nothing is therefore the same determination or rather absence of determination, and thus altogether the same as what pure being is.",
  "keyPoints": [
    "Difference whether something or nothing is intuited or thought",
    "To intuit or think nothing has meaning",
    "Nothing is (concretely exists) in our intuiting or thinking",
    "Empty intuiting and thinking itself, like pure being",
    "Nothing is the same determination or absence of determination",
    "Altogether the same as what pure being is"
  ]
};
const stateNothing6: DialecticState = {
  "id": "nothing-6",
  "title": "Nothing passes into becoming",
  "concept": "TransitionToBecoming",
  "phase": "quality",
  "moments": [
    {
      "name": "vanishingIdentity",
      "definition": "Identity of being and nothing is true only as vanishing movement, not fixed result",
      "type": "process"
    },
    {
      "name": "becomingDemand",
      "definition": "The unity must be posited as becoming where both sides pass over into each other",
      "type": "determination",
      "relation": "transitions",
      "relatedTo": "vanishingIdentity"
    }
  ],
  "invariants": [
    {
      "id": "nothing-6-inv-1",
      "constraint": "identity of being and nothing persists only as movement",
      "predicate": "identityOnlyAsMovement(being, nothing)"
    }
  ],
  "forces": [
    {
      "id": "nothing-6-force-1",
      "description": "Nothing hands off into becoming as explicit movement",
      "type": "passover",
      "trigger": "movement.explicit = true",
      "effect": "becomingChapter.initiated = true",
      "targetState": "becoming-1"
    }
  ],
  "transitions": [
    {
      "id": "nothing-6-trans-1",
      "from": "nothing-6",
      "to": "becoming-1",
      "mechanism": "passover",
      "description": "From nothing to becoming"
    }
  ],
  "nextStates": [
    "becoming-1"
  ],
  "previousStates": [
    "nothing-4"
  ],
  "provenance": {
    "topicMapId": "nothing-2",
    "lineRange": {
      "start": 17,
      "end": 28
    },
    "section": "B. NOTHING",
    "order": 3
  },
  "description": "In so far as mention can be made here of intuiting and thinking, it makes a difference whether something or nothing is being intuited or thought. To intuit or to think nothing has therefore a meaning; the two are distinguished and so nothing is (concretely exists) in our intuiting or thinking; or rather it is the empty intuiting and thinking itself, like pure being. Nothing is therefore the same determination or rather absence of determination, and thus altogether the same as what pure being is.",
  "keyPoints": [
    "Difference whether something or nothing is intuited or thought",
    "To intuit or think nothing has meaning",
    "Nothing is (concretely exists) in our intuiting or thinking",
    "Empty intuiting and thinking itself, like pure being",
    "Nothing is the same determination or absence of determination",
    "Altogether the same as what pure being is"
  ]
};

export const nothingIR: DialecticIR = {
  id: "nothing-ir",
  title: "Nothing IR: Pure Nothing",
  section: "BEING - QUALITY - B. Nothing",
  states: [
    stateNothing1,
    stateNothing4,
    stateNothing6,
  ],
  metadata: {
  "sourceFile": "nothing.txt",
  "totalStates": 3,
  "cpuGpuMapping": {
    "nothing-1": "quality",
    "nothing-4": "quality",
    "nothing-6": "quality"
  }
},
};

export const nothingStates = {
  "nothing-1": stateNothing1,
  "nothing-4": stateNothing4,
  "nothing-6": stateNothing6,
};
