/**
 * TopicMap for powers.txt - The Ratio of Powers
 *
 * SOURCE ANALYSIS PHASE 1: Topics
 *
 * COGNITIVE SCIENCE: This is where the real cognitive work happens.
 * The skill in producing good chunks and topics is what makes everything else meaningful.
 * The TopicMap helps check and improve understanding of Hegel through step-by-step analysis.
 *
 * Architecture:
 *    Source Text → [Source Analysis: Cognitive Science] → Chunks + Topics
 *                                                              ↓
 *                    [Logical Op Generation: IR Translation] → Logical Operations (IR)
 *                                                              ↓
 *                    [Codegen: Backend] → Executable Code
 *
 * This TopicMap provides the structured plan for chunking the source text
 * into meaningful chunks. Good chunking/topic analysis makes Logical Operations meaningful
 * (not just jargon) and enables executable codegen (the backend).
 *
 * Each entry maps to:
 * - TopicMapEntry.id → Chunk.id
 * - TopicMapEntry.title → Chunk.title AND LogicalOperation.label (the "Title")
 * - TopicMapEntry.lineRange → Extract text → Chunk.text
 *
 * Reference:
 * - powers-chunks.md for detailed planning notes
 * - tools/source-analysis/SOURCE-ANALYSIS.md for workflow documentation
 * - tools/source-analysis/ARCHITECTURE.md for architectural overview
 */

import type { TopicMap } from '@schema/topic';
import { createTopicMap, createTopicMapEntry } from '@schema/topic';

export const POWERS_TOPIC_MAP: TopicMap = createTopicMap(
  'logic/src/relative/being/quantity/ratio/sources/powers.txt',
  'Hegel\'s Science of Logic - Quantity',
  'The Ratio of Powers',
  [
    createTopicMapEntry(
      'powers-being-for-itself',
      'Quantum as being-for-itself: unit is amount',
      [4, 24],
      'Ratio of powers: Quantum as being-for-itself (self-identical in otherness). Amount determined only by unit. Unit is amount as against itself as unit. Otherness (amount of units) is unit itself. Power is aggregate of units, each is aggregate itself. Quantum\'s otherness determined purely by itself. Quantum returned into itself - immediately itself and its otherness.',
      [
        'quantum',
        'positing',
        'self-identical',
        'otherness',
        'determining',
        'movement',
        'self-surpassing',
        'being-for-itself',
        'qualitative',
        'totality',
        'positing',
        'developed',
        'moments',
        'conceptual',
        'determinations',
        'number',
        'unit',
        'amount',
        'amount',
        'inverse',
        'ratio',
        'aggregate',
        'determined',
        'amount',
        'unit',
        'elsewhere',
        'third',
        'determinate',
        'aggregate',
        'posited',
        'determined',
        'unit',
        'ratio',
        'powers',
        'unit',
        'amount',
        'time',
        'amount',
        'unit',
        'otherness',
        'amount',
        'units',
        'unit',
        'power',
        'aggregate',
        'units',
        'aggregate',
        'quantum',
        'indifferent',
        'determinateness',
        'changes',
        'alteration',
        'raising',
        'power',
        'otherness',
        'quantum',
        'determined',
        'quantum',
        'posited',
        'power',
        'returned',
        'immediately',
        'otherness',
      ],
      { section: 'C. THE RATIO OF POWERS', order: 1 }
    ),

    createTopicMapEntry(
      'powers-exponent-qualitative',
      'Exponent: entirely qualitative nature',
      [26, 38],
      'Exponent: No longer immediate quantum. Entirely qualitative nature - simple determinateness that amount is unit itself, quantum self-identical in otherness. Quantitative side: limit/negation not immediate existent, existence continues in otherness. Truth of quality is quantity (immediate determinateness as sublated).',
      [
        'exponent',
        'ratio',
        'longer',
        'immediate',
        'quantum',
        'direct',
        'ratio',
        'inverse',
        'ratio',
        'ratio',
        'powers',
        'exponent',
        'entirely',
        'qualitative',
        'nature',
        'simple',
        'determinateness',
        'amount',
        'unit',
        'quantum',
        'self-identical',
        'otherness',
        'side',
        'quantitative',
        'nature',
        'limit',
        'negation',
        'immediate',
        'existent',
        'existence',
        'posited',
        'continuing',
        'otherness',
        'truth',
        'quality',
        'quantity',
        'immediate',
        'determinateness',
        'sublated',
      ],
      { section: 'C. THE RATIO OF POWERS', order: 2 }
    ),

    createTopicMapEntry(
      'powers-concept-realized',
      'Quantum\'s concept realized',
      [40, 58],
      'Concept realized: Ratio of powers displays what quantum is implicitly. Quantum has attained/realized its concept. Quantum is indifferent determinateness posited as sublated - limit that is no limit, continues in otherness, remains identical. In ratio of powers, quantum\'s otherness (surpassing into another quantum) is determined through quantum itself.',
      [
        'ratio',
        'powers',
        'appears',
        'external',
        'alteration',
        'quantum',
        'subjected',
        'connection',
        'concept',
        'quantum',
        'existence',
        'quantum',
        'developed',
        'ratio',
        'powers',
        'quantum',
        'attained',
        'concept',
        'realized',
        'concept',
        'fullest',
        'ratio',
        'powers',
        'display',
        'quantum',
        'implicitly',
        'expresses',
        'determinateness',
        'quantum',
        'quality',
        'distinguished',
        'quantum',
        'indifferent',
        'determinateness',
        'posited',
        'sublated',
        'determinateness',
        'limit',
        'determinateness',
        'continues',
        'otherness',
        'remains',
        'identical',
        'quantum',
        'posited',
        'ratio',
        'powers',
        'otherness',
        'surpassing',
        'quantum',
        'determined',
        'quantum',
      ],
      { section: 'C. THE RATIO OF POWERS', order: 3 }
    ),

    createTopicMapEntry(
      'powers-progressive-realization',
      'Progressive realization: quantum\'s quality as ratio',
      [60, 83],
      'Progressive realization: Quantum\'s quality is difference of itself from itself - that it is a ratio. Direct ratio: difference immediate, self-reference as fixity of amount. Inverse ratio: relating to itself (negation), exponent implicitly determinant. Ratio of powers: quantum in difference as difference of itself from itself. Externality is quality - quantum\'s own determining, reference to itself.',
      [
        'compare',
        'progressive',
        'realization',
        'quantum',
        'preceding',
        'ratios',
        'find',
        'quantum',
        'quality',
        'difference',
        'ratio',
        'direct',
        'ratio',
        'quantum',
        'posited',
        'difference',
        'instance',
        'immediately',
        'self-reference',
        'exponent',
        'contrast',
        'differences',
        'counts',
        'fixity',
        'amount',
        'unit',
        'inverse',
        'ratio',
        'negatively',
        'determined',
        'quantum',
        'relating',
        'negation',
        'value',
        'affirmative',
        'self-reference',
        'exponent',
        'quantum',
        'implicitly',
        'determinant',
        'moments',
        'ratio',
        'powers',
        'quantum',
        'present',
        'difference',
        'difference',
        'externality',
        'determinateness',
        'quality',
        'quantum',
        'posited',
        'conformity',
        'concept',
        'quantum',
        'determining',
        'reference',
        'quality',
      ],
      { section: 'C. THE RATIO OF POWERS', order: 4 }
    ),

    createTopicMapEntry(
      'powers-return-quality',
      'Quantum returns to quality: quantity is quality',
      [85, 115],
      'Return to quality: Quantum passed over into another determination - determination now also as determinateness, in-itself as existence. Quantum has become other of itself (quality). Externality now mediated by quantum itself, as moment - in externality quantum refers itself to itself, is being as quality. Quantity is quality itself. Truth of quality is quantity. Quantity is externality returned into itself - quality itself.',
      [
        'posited',
        'conformity',
        'concept',
        'quantum',
        'passed',
        'determination',
        'determination',
        'determinateness',
        'in-itself',
        'existence',
        'quantum',
        'externality',
        'indifference',
        'determining',
        'increased',
        'decreased',
        'accepted',
        'immediately',
        'posited',
        'become',
        'quality',
        'externality',
        'posited',
        'mediated',
        'quantum',
        'moment',
        'quantum',
        'externality',
        'quantum',
        'refers',
        'being',
        'quality',
        'quantity',
        'opposition',
        'quality',
        'quantity',
        'quality',
        'self-referring',
        'determinateness',
        'distinct',
        'determinateness',
        'quality',
        'quantity',
        'quality',
        'truth',
        'quality',
        'quantity',
        'quality',
        'demonstrated',
        'passing',
        'quantity',
        'truth',
        'externality',
        'returned',
        'indifferent',
        'quantity',
        'quality',
        'determination',
        'quality',
      ],
      { section: 'C. THE RATIO OF POWERS', order: 5 }
    ),

    createTopicMapEntry(
      'powers-double-transition-measure',
      'Double transition and measure',
      [117, 140],
      'Double transition: For totality, double transition required - (1) quality → quantity, (2) quantity → quality. First: identity in itself (quality contained in quantity). Second: quantity contained in quality (as sublated). Quantum no longer indifferent but sublated - it is quality and that by virtue of which anything is what it is. Truth of quantum is to be measure.',
      [
        'totality',
        'posited',
        'double',
        'transition',
        'required',
        'transition',
        'determinateness',
        'equally',
        'transition',
        'going',
        'transition',
        'identity',
        'present',
        'quality',
        'contained',
        'quantity',
        'latter',
        'one-sided',
        'determinateness',
        'conversely',
        'quantity',
        'equally',
        'contained',
        'quality',
        'equally',
        'sublated',
        'results',
        'transition',
        'going',
        'determinateness',
        'remark',
        'necessity',
        'double',
        'transition',
        'everywhere',
        'importance',
        'scientific',
        'method',
        'quantum',
        'henceforth',
        'indifferent',
        'external',
        'determination',
        'sublated',
        'quality',
        'virtue',
        'truth',
        'quantum',
        'measure',
      ],
      { section: 'C. THE RATIO OF POWERS', order: 6 }
    ),
  ],
  {
    sectionDescription: 'The Ratio of Powers - Quantum as being-for-itself (unit is amount, otherness is unit itself). Exponent entirely qualitative (amount is unit itself, quantum self-identical in otherness). Quantum\'s concept realized (otherness determined through quantum itself). Progressive realization (quantum\'s quality as ratio). Quantum returns to quality (quantity is quality itself). Double transition and measure (quality ↔ quantity, truth of quantum is measure).',
  }
);

