//! Top-level task runtime wiring.
//!
//! `TaskFrame` describes a shell- or subsystem-generated runtime frame.
//! `TaskRuntime` materializes the frame into an executable progress runtime.

use crate::task::concurrency::Concurrency;
use crate::task::memory::MemoryRange;
use crate::task::progress::EmptyTaskRegistryFactory;
use crate::task::progress::JobId;
use crate::task::progress::ProgressTracker;
use crate::task::progress::TaskProgressTracker;
use crate::task::progress::TaskRegistryFactory;
use crate::task::progress::Tasks;

/// Kernel-level image kind executed by a `TaskFrame`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TaskFrameKind {
    ProcedurePipeline,
    GraphAlgorithm,
    MachineLearning,
    PregelExecutionImage,
    ShellProgram,
}

/// Storage backend intent for task execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TaskFrameStorageBackend {
    PolarsPropertyStore,
    GraphStore,
    PregelState,
    RuntimeManaged,
}

/// Hardware preference for task execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TaskDeviceHint {
    Cpu,
    Gpu,
    Tpu,
    Hybrid,
}

/// Image identity and storage semantics for a task frame.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TaskFrameImageSpec {
    kind: TaskFrameKind,
    execution_image: Option<String>,
    storage_backend: TaskFrameStorageBackend,
}

impl TaskFrameImageSpec {
    pub fn new(kind: TaskFrameKind) -> Self {
        Self {
            kind,
            execution_image: None,
            storage_backend: TaskFrameStorageBackend::RuntimeManaged,
        }
    }

    pub fn kind(&self) -> TaskFrameKind {
        self.kind
    }

    pub fn execution_image(&self) -> Option<&str> {
        self.execution_image.as_deref()
    }

    pub fn storage_backend(&self) -> TaskFrameStorageBackend {
        self.storage_backend
    }
}

/// Resource contract consumed by the task runtime.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TaskFrameResourceSpec {
    concurrency: Concurrency,
    estimated_memory_range: Option<MemoryRange>,
    device_hint: TaskDeviceHint,
}

impl TaskFrameResourceSpec {
    pub fn new(concurrency: Concurrency) -> Self {
        Self {
            concurrency,
            estimated_memory_range: None,
            device_hint: TaskDeviceHint::Cpu,
        }
    }

    pub fn concurrency(&self) -> Concurrency {
        self.concurrency
    }

    pub fn estimated_memory_range(&self) -> Option<MemoryRange> {
        self.estimated_memory_range
    }

    pub fn device_hint(&self) -> TaskDeviceHint {
        self.device_hint
    }
}

/// Observability contract for progress and logs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TaskFrameObservabilitySpec {
    progress_namespace: String,
    logging_namespace: String,
}

impl TaskFrameObservabilitySpec {
    pub fn new(progress_namespace: String, logging_namespace: String) -> Self {
        Self {
            progress_namespace,
            logging_namespace,
        }
    }

    pub fn progress_namespace(&self) -> &str {
        &self.progress_namespace
    }

    pub fn logging_namespace(&self) -> &str {
        &self.logging_namespace
    }
}

/// Input/output and side-effect contract for a task frame.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TaskFrameIoSpec {
    inputs: Vec<String>,
    outputs: Vec<String>,
    side_effects: Vec<String>,
}

impl TaskFrameIoSpec {
    pub fn new() -> Self {
        Self {
            inputs: Vec::new(),
            outputs: Vec::new(),
            side_effects: Vec::new(),
        }
    }

    pub fn inputs(&self) -> &[String] {
        &self.inputs
    }

    pub fn outputs(&self) -> &[String] {
        &self.outputs
    }

    pub fn side_effects(&self) -> &[String] {
        &self.side_effects
    }
}

impl Default for TaskFrameIoSpec {
    fn default() -> Self {
        Self::new()
    }
}

/// Minimal kernel contract for a task frame.
pub trait TaskFrameContract {
    fn namespace(&self) -> &str;
    fn pipeline(&self) -> &str;
    fn steps(&self) -> &[String];
    fn estimated_volume(&self) -> usize;
    fn image_spec(&self) -> &TaskFrameImageSpec;
    fn resource_spec(&self) -> &TaskFrameResourceSpec;
    fn observability_spec(&self) -> &TaskFrameObservabilitySpec;
    fn io_spec(&self) -> &TaskFrameIoSpec;
}

/// Declarative frame generated by a top-level subsystem (for example, Shell).
#[derive(Debug, Clone)]
pub struct TaskFrame {
    namespace: String,
    pipeline: String,
    steps: Vec<String>,
    estimated_volume: usize,
    image_spec: TaskFrameImageSpec,
    resource_spec: TaskFrameResourceSpec,
    observability_spec: TaskFrameObservabilitySpec,
    io_spec: TaskFrameIoSpec,
}

impl TaskFrame {
    pub fn new(
        namespace: String,
        pipeline: String,
        steps: Vec<String>,
        estimated_volume: usize,
        concurrency: Concurrency,
    ) -> Self {
        let progress_namespace = format!("{}.{}", namespace, pipeline);
        let logging_namespace = format!("task.{}", progress_namespace);
        Self {
            namespace,
            pipeline,
            steps,
            estimated_volume: estimated_volume.max(1),
            image_spec: TaskFrameImageSpec::new(TaskFrameKind::ProcedurePipeline),
            resource_spec: TaskFrameResourceSpec::new(concurrency),
            observability_spec: TaskFrameObservabilitySpec::new(
                progress_namespace,
                logging_namespace,
            ),
            io_spec: TaskFrameIoSpec::new(),
        }
    }

    pub fn with_memory_range(mut self, estimated_memory_range: MemoryRange) -> Self {
        self.resource_spec.estimated_memory_range = Some(estimated_memory_range);
        self
    }

    pub fn with_device_hint(mut self, device_hint: TaskDeviceHint) -> Self {
        self.resource_spec.device_hint = device_hint;
        self
    }

    pub fn with_image_kind(mut self, kind: TaskFrameKind) -> Self {
        self.image_spec.kind = kind;
        self
    }

    pub fn with_execution_image(mut self, execution_image: impl Into<String>) -> Self {
        self.image_spec.execution_image = Some(execution_image.into());
        self
    }

    pub fn with_storage_backend(mut self, storage_backend: TaskFrameStorageBackend) -> Self {
        self.image_spec.storage_backend = storage_backend;
        self
    }

    pub fn with_progress_namespace(mut self, progress_namespace: impl Into<String>) -> Self {
        self.observability_spec.progress_namespace = progress_namespace.into();
        self
    }

    pub fn with_logging_namespace(mut self, logging_namespace: impl Into<String>) -> Self {
        self.observability_spec.logging_namespace = logging_namespace.into();
        self
    }

    pub fn with_inputs(mut self, inputs: Vec<String>) -> Self {
        self.io_spec.inputs = inputs;
        self
    }

    pub fn with_outputs(mut self, outputs: Vec<String>) -> Self {
        self.io_spec.outputs = outputs;
        self
    }

    pub fn with_side_effects(mut self, side_effects: Vec<String>) -> Self {
        self.io_spec.side_effects = side_effects;
        self
    }

    pub fn namespace(&self) -> &str {
        &self.namespace
    }

    pub fn pipeline(&self) -> &str {
        &self.pipeline
    }

    pub fn steps(&self) -> &[String] {
        &self.steps
    }

    pub fn estimated_volume(&self) -> usize {
        self.estimated_volume
    }

    pub fn concurrency(&self) -> Concurrency {
        self.resource_spec.concurrency
    }

    pub fn estimated_memory_range(&self) -> Option<MemoryRange> {
        self.resource_spec.estimated_memory_range
    }

    pub fn image_spec(&self) -> &TaskFrameImageSpec {
        &self.image_spec
    }

    pub fn resource_spec(&self) -> &TaskFrameResourceSpec {
        &self.resource_spec
    }

    pub fn observability_spec(&self) -> &TaskFrameObservabilitySpec {
        &self.observability_spec
    }

    pub fn io_spec(&self) -> &TaskFrameIoSpec {
        &self.io_spec
    }

    pub fn description(&self) -> String {
        format!("{}::{}", self.namespace, self.pipeline)
    }

    fn as_leaf_task(&self) -> crate::task::progress::LeafTask {
        Tasks::leaf_with_volume(self.description(), self.estimated_volume)
    }
}

impl TaskFrameContract for TaskFrame {
    fn namespace(&self) -> &str {
        self.namespace()
    }

    fn pipeline(&self) -> &str {
        self.pipeline()
    }

    fn steps(&self) -> &[String] {
        self.steps()
    }

    fn estimated_volume(&self) -> usize {
        self.estimated_volume()
    }

    fn image_spec(&self) -> &TaskFrameImageSpec {
        self.image_spec()
    }

    fn resource_spec(&self) -> &TaskFrameResourceSpec {
        self.resource_spec()
    }

    fn observability_spec(&self) -> &TaskFrameObservabilitySpec {
        self.observability_spec()
    }

    fn io_spec(&self) -> &TaskFrameIoSpec {
        self.io_spec()
    }
}

/// Executable runtime materialized from a `TaskFrame`.
#[derive(Clone)]
pub struct TaskRuntime {
    frame: TaskFrame,
    tracker: TaskProgressTracker,
}

impl TaskRuntime {
    /// Construct a runtime with a request-local empty task registry.
    pub fn from_frame(frame: TaskFrame) -> Self {
        Self::with_registry(frame, JobId::new(), &EmptyTaskRegistryFactory)
    }

    /// Construct a runtime with an explicit job identity and task registry.
    pub fn with_registry(
        frame: TaskFrame,
        job_id: JobId,
        task_registry_factory: &dyn TaskRegistryFactory,
    ) -> Self {
        let base_task = frame.as_leaf_task().base().clone();
        let mut tracker = TaskProgressTracker::with_registry(
            base_task,
            frame.concurrency(),
            job_id,
            task_registry_factory,
        );

        tracker.requested_concurrency(frame.concurrency());
        if let Some(memory_range) = frame.estimated_memory_range() {
            tracker.set_estimated_resource_footprint(memory_range);
        }

        Self { frame, tracker }
    }

    pub fn frame(&self) -> &TaskFrame {
        &self.frame
    }

    pub fn tracker(&self) -> TaskProgressTracker {
        self.tracker.clone()
    }

    pub fn begin(&mut self) {
        self.tracker.begin_subtask();
    }

    pub fn progress(&mut self, value: usize) {
        self.tracker.log_progress(value);
    }

    pub fn end(&mut self) {
        self.tracker.end_subtask();
    }

    pub fn fail(&mut self) {
        self.tracker.end_subtask_with_failure();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn frame_description_is_stable() {
        let frame = TaskFrame::new(
            "shell".to_string(),
            "pipeline::Frame".to_string(),
            vec!["dataframe.seed".to_string()],
            42,
            Concurrency::of(2),
        )
        .with_image_kind(TaskFrameKind::ShellProgram)
        .with_storage_backend(TaskFrameStorageBackend::PolarsPropertyStore)
        .with_execution_image("pregel.compute-graph")
        .with_device_hint(TaskDeviceHint::Cpu)
        .with_inputs(vec!["dataframe.seed".to_string()])
        .with_outputs(vec!["pipeline::Frame".to_string()]);

        assert_eq!(frame.description(), "shell::pipeline::Frame");
        assert_eq!(frame.estimated_volume(), 42);
        assert_eq!(
            frame.image_spec().storage_backend(),
            TaskFrameStorageBackend::PolarsPropertyStore
        );
    }

    #[test]
    fn runtime_is_constructed_with_tracker() {
        let frame = TaskFrame::new(
            "shell".to_string(),
            "pipeline::ModelFeaturePlan".to_string(),
            vec!["shell.program".to_string()],
            16,
            Concurrency::of(1),
        )
        .with_memory_range(MemoryRange::of_range(8, 32));

        let runtime = TaskRuntime::from_frame(frame);
        assert_eq!(runtime.frame().namespace(), "shell");
        assert_eq!(runtime.frame().pipeline(), "pipeline::ModelFeaturePlan");
    }

    #[test]
    fn contract_surfaces_kernel_specs() {
        let frame = TaskFrame::new(
            "proc".to_string(),
            "pipeline::NodeClassificationTrain".to_string(),
            vec!["pipeline.train".to_string()],
            8,
            Concurrency::of(4),
        )
        .with_image_kind(TaskFrameKind::MachineLearning)
        .with_storage_backend(TaskFrameStorageBackend::GraphStore)
        .with_device_hint(TaskDeviceHint::Hybrid)
        .with_side_effects(vec!["model.catalog.write".to_string()]);

        let contract: &dyn TaskFrameContract = &frame;
        assert_eq!(contract.namespace(), "proc");
        assert_eq!(contract.image_spec().kind(), TaskFrameKind::MachineLearning);
        assert_eq!(
            contract.resource_spec().device_hint(),
            TaskDeviceHint::Hybrid
        );
        assert_eq!(contract.io_spec().side_effects().len(), 1);
    }
}
