//! Top-level task runtime wiring.
//!
//! `TaskFrame` describes a shell- or subsystem-generated runtime frame.
//! `TaskRuntime` materializes the frame into an executable progress runtime.

use crate::task::concurrency::Concurrency;
use crate::task::memory::MemoryRange;
use crate::task::progress::EmptyTaskRegistryFactory;
use crate::task::progress::JobId;
use crate::task::progress::ProgressTracker;
use crate::task::progress::TaskProgressTracker;
use crate::task::progress::TaskRegistryFactory;
use crate::task::progress::Tasks;

/// Declarative frame generated by a top-level subsystem (for example, Shell).
#[derive(Debug, Clone)]
pub struct TaskFrame {
    namespace: String,
    pipeline: String,
    steps: Vec<String>,
    estimated_volume: usize,
    concurrency: Concurrency,
    estimated_memory_range: Option<MemoryRange>,
}

impl TaskFrame {
    pub fn new(
        namespace: String,
        pipeline: String,
        steps: Vec<String>,
        estimated_volume: usize,
        concurrency: Concurrency,
    ) -> Self {
        Self {
            namespace,
            pipeline,
            steps,
            estimated_volume: estimated_volume.max(1),
            concurrency,
            estimated_memory_range: None,
        }
    }

    pub fn with_memory_range(mut self, estimated_memory_range: MemoryRange) -> Self {
        self.estimated_memory_range = Some(estimated_memory_range);
        self
    }

    pub fn namespace(&self) -> &str {
        &self.namespace
    }

    pub fn pipeline(&self) -> &str {
        &self.pipeline
    }

    pub fn steps(&self) -> &[String] {
        &self.steps
    }

    pub fn estimated_volume(&self) -> usize {
        self.estimated_volume
    }

    pub fn concurrency(&self) -> Concurrency {
        self.concurrency
    }

    pub fn estimated_memory_range(&self) -> Option<MemoryRange> {
        self.estimated_memory_range
    }

    pub fn description(&self) -> String {
        format!("{}::{}", self.namespace, self.pipeline)
    }

    fn as_leaf_task(&self) -> crate::task::progress::LeafTask {
        Tasks::leaf_with_volume(self.description(), self.estimated_volume)
    }
}

/// Executable runtime materialized from a `TaskFrame`.
#[derive(Clone)]
pub struct TaskRuntime {
    frame: TaskFrame,
    tracker: TaskProgressTracker,
}

impl TaskRuntime {
    /// Construct a runtime with a request-local empty task registry.
    pub fn from_frame(frame: TaskFrame) -> Self {
        Self::with_registry(frame, JobId::new(), &EmptyTaskRegistryFactory)
    }

    /// Construct a runtime with an explicit job identity and task registry.
    pub fn with_registry(
        frame: TaskFrame,
        job_id: JobId,
        task_registry_factory: &dyn TaskRegistryFactory,
    ) -> Self {
        let base_task = frame.as_leaf_task().base().clone();
        let mut tracker = TaskProgressTracker::with_registry(
            base_task,
            frame.concurrency(),
            job_id,
            task_registry_factory,
        );

        tracker.requested_concurrency(frame.concurrency());
        if let Some(memory_range) = frame.estimated_memory_range() {
            tracker.set_estimated_resource_footprint(memory_range);
        }

        Self { frame, tracker }
    }

    pub fn frame(&self) -> &TaskFrame {
        &self.frame
    }

    pub fn tracker(&self) -> TaskProgressTracker {
        self.tracker.clone()
    }

    pub fn begin(&mut self) {
        self.tracker.begin_subtask();
    }

    pub fn progress(&mut self, value: usize) {
        self.tracker.log_progress(value);
    }

    pub fn end(&mut self) {
        self.tracker.end_subtask();
    }

    pub fn fail(&mut self) {
        self.tracker.end_subtask_with_failure();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn frame_description_is_stable() {
        let frame = TaskFrame::new(
            "shell".to_string(),
            "pipeline::Frame".to_string(),
            vec!["dataframe.seed".to_string()],
            42,
            Concurrency::of(2),
        );

        assert_eq!(frame.description(), "shell::pipeline::Frame");
        assert_eq!(frame.estimated_volume(), 42);
    }

    #[test]
    fn runtime_is_constructed_with_tracker() {
        let frame = TaskFrame::new(
            "shell".to_string(),
            "pipeline::ModelFeaturePlan".to_string(),
            vec!["shell.program".to_string()],
            16,
            Concurrency::of(1),
        )
        .with_memory_range(MemoryRange::of_range(8, 32));

        let runtime = TaskRuntime::from_frame(frame);
        assert_eq!(runtime.frame().namespace(), "shell");
        assert_eq!(runtime.frame().pipeline(), "pipeline::ModelFeaturePlan");
    }
}
